/**
 * RiskPrintView Component
 * Print-optimized view for risk register
 */

import React from 'react'

const RiskPrintView = ({ risk, project, className = '' }) => {
  if (!risk) {
    return (
      <div className={`p-8 bg-white text-black ${className}`}>
        <p className="text-center text-gray-500">No risk data to display</p>
      </div>
    )
  }

  return (
    <div className={`p-8 bg-white text-black print:p-0 ${className}`}>
      {/* Header */}
      <div className="border-b-2 border-black pb-4 mb-6">
        <h1 className="text-2xl font-bold">Risk Report</h1>
        <div className="flex justify-between mt-2 text-sm">
          <span>Risk ID: {risk.risk_id || risk.id}</span>
          <span>Print Date: {new Date().toLocaleDateString()}</span>
        </div>
      </div>

      {/* Risk Details */}
      <div className="space-y-4">
        <div>
          <h2 className="text-lg font-bold border-b border-gray-300 pb-1 mb-2">
            Risk Details
          </h2>
          <table className="w-full text-sm">
            <tbody>
              <tr>
                <td className="py-1 font-medium w-1/3">Title:</td>
                <td>{risk.title || risk.risk_title || 'N/A'}</td>
              </tr>
              <tr>
                <td className="py-1 font-medium">Category:</td>
                <td>{risk.category || risk.risk_category || 'N/A'}</td>
              </tr>
              <tr>
                <td className="py-1 font-medium">Status:</td>
                <td>{risk.status || risk.risk_status || 'N/A'}</td>
              </tr>
              <tr>
                <td className="py-1 font-medium">Owner:</td>
                <td>{risk.owner || risk.risk_owner || 'N/A'}</td>
              </tr>
              <tr>
                <td className="py-1 font-medium">Probability:</td>
                <td>{risk.probability || 'N/A'}</td>
              </tr>
              <tr>
                <td className="py-1 font-medium">Impact:</td>
                <td>{risk.impact || 'N/A'}</td>
              </tr>
              <tr>
                <td className="py-1 font-medium">Risk Score:</td>
                <td>{risk.risk_score || (risk.probability && risk.impact ? risk.probability * risk.impact : 'N/A')}</td>
              </tr>
            </tbody>
          </table>
        </div>

        {risk.description && (
          <div>
            <h2 className="text-lg font-bold border-b border-gray-300 pb-1 mb-2">
              Description
            </h2>
            <p className="text-sm whitespace-pre-wrap">{risk.description}</p>
          </div>
        )}

        {risk.cause && (
          <div>
            <h2 className="text-lg font-bold border-b border-gray-300 pb-1 mb-2">
              Cause
            </h2>
            <p className="text-sm whitespace-pre-wrap">{risk.cause}</p>
          </div>
        )}

        {risk.effect && (
          <div>
            <h2 className="text-lg font-bold border-b border-gray-300 pb-1 mb-2">
              Effect
            </h2>
            <p className="text-sm whitespace-pre-wrap">{risk.effect}</p>
          </div>
        )}

        {(risk.response || risk.mitigation) && (
          <div>
            <h2 className="text-lg font-bold border-b border-gray-300 pb-1 mb-2">
              Response/Mitigation
            </h2>
            <p className="text-sm whitespace-pre-wrap">{risk.response || risk.mitigation}</p>
          </div>
        )}
      </div>

      {/* Footer */}
      <div className="mt-8 pt-4 border-t border-gray-300 text-xs text-gray-500">
        <div className="flex justify-between">
          <span>Project: {project?.name || project?.project_name || 'N/A'}</span>
          <span>Generated by Project Nidus</span>
        </div>
      </div>
    </div>
  )
}

export default RiskPrintView
