/**
 * Project Mandate Service
 * Handles CRUD operations for Project Mandate functionality
 *
 * IMPORTANT: Project Mandate is a PRE-PROJECT document
 * - project_id is NULLABLE - mandates can exist independently before projects
 * - Once approved, mandate triggers project creation and gets linked
 */

import { platformDb } from './supabase/supabaseClient'

/**
 * Get current user's internal ID from auth user ID
 */
async function getCurrentUserId() {
  const { data: { user: authUser }, error: authError } = await platformDb.auth.getUser()

  if (authError) throw new Error('Auth error: ' + authError.message)
  if (!authUser) throw new Error('User not authenticated')

  const { data: userData, error } = await platformDb
    .from('users')
    .select('id')
    .eq('auth_user_id', authUser.id)
    .maybeSingle()

  if (error) throw new Error('Database error: ' + error.message)

  // Fallback to auth user ID if not found in users table
  return userData?.id || authUser.id
}

/**
 * Create a new mandate (no project ID required initially)
 */
export async function createMandate(mandateData) {
  const userId = await getCurrentUserId()
  
  // Extract associated documents and stakeholders (stored as JSON arrays)
  const { associated_documents, stakeholders, ...mainMandateData } = mandateData
  
  const insertData = {
    ...mainMandateData,
    // project_id can be NULL (pre-project document)
    document_status: mainMandateData.document_status || 'draft',
    version_number: mainMandateData.version_number || '1.0',
    created_date: mainMandateData.created_date || new Date().toISOString().split('T')[0],
    is_standalone: mainMandateData.is_standalone !== undefined ? mainMandateData.is_standalone : true,
    quality_priority: mainMandateData.quality_priority || 'balanced',
    is_active: mainMandateData.is_active !== undefined ? mainMandateData.is_active : true,
    created_by: userId,
    updated_by: userId,
  }
  
  // mandate_reference will be auto-generated by trigger if not provided
  
  const { data, error } = await platformDb
    .from('project_mandates')
    .insert(insertData)
    .select()
    .single()
  
  if (error) throw error
  
  const mandateId = data.id
  
  // Process associated documents (Section 10)
  if (associated_documents) {
    try {
      const documents = typeof associated_documents === 'string' 
        ? JSON.parse(associated_documents || '[]')
        : associated_documents
      
      if (Array.isArray(documents) && documents.length > 0) {
        for (const doc of documents) {
          await addAssociatedDocument(mandateId, {
            document_type: doc.document_type || 'other',
            document_title: doc.document_title,
            document_url: doc.document_url || null,
            reference_number: doc.reference_number || null,
            display_order: documents.indexOf(doc)
          })
        }
      }
    } catch (err) {
      console.warn('Error adding associated documents:', err)
      // Don't fail mandate creation if documents fail
    }
  }
  
  // Process stakeholders (Section 12)
  if (stakeholders) {
    try {
      const stakeholderList = typeof stakeholders === 'string'
        ? JSON.parse(stakeholders || '[]')
        : stakeholders
      
      if (Array.isArray(stakeholderList) && stakeholderList.length > 0) {
        for (const stakeholder of stakeholderList) {
          await addStakeholder(mandateId, {
            stakeholder_type: stakeholder.stakeholder_type || 'customer',
            stakeholder_name: stakeholder.stakeholder_name,
            stakeholder_organisation: stakeholder.stakeholder_organisation || null,
            stakeholder_role: stakeholder.stakeholder_role || null,
            contact_email: stakeholder.contact_email || null,
            is_primary: stakeholder.is_primary || false,
            display_order: stakeholderList.indexOf(stakeholder)
          })
        }
      }
    } catch (err) {
      console.warn('Error adding stakeholders:', err)
      // Don't fail mandate creation if stakeholders fail
    }
  }
  
  // Return the created mandate with related data
  return getMandateById(mandateId)
}

/** UUID v4 pattern for detecting internal IDs vs mandate codes */
const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

/**
 * Single-query fetch for the mandate view page.
 * Fetches mandate + approvals + constraints + documents + stakeholders in ONE
 * HTTP round-trip instead of 5, cutting load time from seconds to milliseconds.
 */
export async function getMandateViewData(identifier) {
  if (!identifier || typeof identifier !== 'string') return null
  const trimmed = identifier.trim()
  if (!trimmed) return null

  let query = platformDb
    .from('project_mandates')
    .select(`
      *,
      project:project_id (id, project_name, project_code, status_id),
      programme:programme_id (id, programme_name, programme_code),
      proposed_executive:proposed_executive_id (id, email, full_name),
      proposed_pm:proposed_pm_id (id, email, full_name),
      creator:created_by (id, email, full_name),
      updater:updated_by (id, email, full_name),
      mandate_approvals (
        id, approval_status, approval_comments, approval_date, approval_at,
        approval_ip_address, approver_name, created_at
      ),
      mandate_constraints (
        id, operand, value_numeric, value_min, value_max, value_text, value_date,
        unit, notes, display_order, is_active,
        constraint_category:constraint_categories (
          id, code, name, description, value_type, supports_operands,
          unit_options, operand_options, dropdown_options
        )
      ),
      mandate_associated_documents (
        id, document_type, document_title, document_url, reference_number,
        display_order, is_deleted
      ),
      mandate_customers_users (
        id, stakeholder_type, stakeholder_name, stakeholder_organisation,
        stakeholder_role, contact_email, is_primary, display_order, is_deleted
      )
    `)
    .eq('is_deleted', false)

  if (UUID_REGEX.test(trimmed)) {
    query = query.eq('id', trimmed)
  } else {
    query = query.eq('mandate_reference', trimmed)
  }

  const { data, error } = await query.single()
  if (error) throw error
  return data
}

/**
 * Resolve a mandate identifier (UUID or mandate_reference) to full mandate.
 * Enables human-readable URLs like /pmo/mandates/MAN-2026-001/edit.
 */
export async function getMandateByIdOrReference(identifier) {
  if (!identifier || typeof identifier !== 'string') return null
  const trimmed = identifier.trim()
  if (!trimmed) return null
  if (UUID_REGEX.test(trimmed)) {
    return getMandateById(trimmed)
  }
  return getMandateByReference(trimmed)
}

/** Minimal columns needed for Create Project prefill — no joins, fast. */
const MANDATE_PREFILL_COLUMNS = 'id, mandate_reference, mandate_title, purpose, background, project_objectives, outline_business_case, proposed_executive_id, proposed_executive_name'

/**
 * Fetch only the mandate fields needed for project create prefill (no joins).
 * Use this when defaulting form fields so the request completes in milliseconds.
 */
export async function getMandatePrefill(identifier) {
  if (!identifier || typeof identifier !== 'string') return null
  const trimmed = identifier.trim()
  if (!trimmed) return null
  const isUuid = UUID_REGEX.test(trimmed)
  const { data, error } = await platformDb
    .from('project_mandates')
    .select(MANDATE_PREFILL_COLUMNS)
    .eq(isUuid ? 'id' : 'mandate_reference', trimmed)
    .eq('is_deleted', false)
    .single()
  if (error) {
    if (error.code === 'PGRST116') return null
    throw error
  }
  return data
}

/**
 * Get mandate by ID (works for both linked and unlinked mandates)
 */
export async function getMandateById(mandateId) {
  const { data, error } = await platformDb
    .from('project_mandates')
    .select(`
      *,
      project:project_id (id, project_name, project_code, status_id),
      programme:programme_id (id, programme_name, programme_code),
      proposed_executive:proposed_executive_id (id, email, full_name),
      proposed_pm:proposed_pm_id (id, email, full_name),
      creator:created_by (id, email, full_name),
      updater:updated_by (id, email, full_name)
    `)
    .eq('id', mandateId)
    .eq('is_deleted', false)
    .single()

  if (error) throw error
  return data
}

/**
 * Get mandate by project ID (returns the mandate linked to a project)
 */
export async function getMandateByProject(projectId) {
  const { data, error } = await platformDb
    .from('project_mandates')
    .select(`
      *,
      programme:programme_id (id, programme_name, programme_code),
      proposed_executive:proposed_executive_id (id, email, full_name),
      proposed_pm:proposed_pm_id (id, email, full_name)
    `)
    .eq('project_id', projectId)
    .eq('is_deleted', false)
    .single()
  
  if (error && error.code !== 'PGRST116') throw error // PGRST116 = not found
  return data || null
}

/**
 * Get mandate by reference number (e.g. MAN-2026-001).
 * Returns same structure as getMandateById for consistency.
 */
export async function getMandateByReference(mandateReference) {
  const { data, error } = await platformDb
    .from('project_mandates')
    .select(`
      *,
      project:project_id (id, project_name, project_code, status_id),
      programme:programme_id (id, programme_name, programme_code),
      proposed_executive:proposed_executive_id (id, email, full_name),
      proposed_pm:proposed_pm_id (id, email, full_name),
      creator:created_by (id, email, full_name),
      updater:updated_by (id, email, full_name)
    `)
    .eq('mandate_reference', mandateReference)
    .eq('is_deleted', false)
    .single()
  
  if (error) throw error
  return data
}

/**
 * Get all approved mandates without projects (ready for project creation)
 */
export async function getUnlinkedMandates(organisationId = null) {
  let query = platformDb
    .from('project_mandates')
    .select(`
      *,
      programme:programme_id (id, programme_name),
      proposed_executive:proposed_executive_id (id, email, full_name),
      proposed_pm:proposed_pm_id (id, email, full_name),
      creator:created_by (id, email, full_name)
    `)
    .is('project_id', null)
    .eq('document_status', 'approved')
    .eq('is_deleted', false)
    .eq('is_active', true)
    .order('created_date', { ascending: false })
  
  const { data, error } = await query
  
  if (error) throw error
  return data || []
}

/**
 * Get all mandates with filtering
 */
export async function getAllMandates(organisationId = null, filters = {}) {
  let query = platformDb
    .from('project_mandates')
    .select(`
      *,
      project:project_id (id, project_name, project_code, status_id),
      programme:programme_id (id, programme_name, programme_code),
      proposed_executive:proposed_executive_id (id, email, full_name),
      proposed_pm:proposed_pm_id (id, email, full_name)
    `)
    .eq('is_deleted', false)
  
  if (filters.status) {
    query = query.eq('document_status', filters.status)
  }
  
  if (filters.is_standalone !== undefined) {
    query = query.eq('is_standalone', filters.is_standalone)
  }
  
  if (filters.programme_id) {
    query = query.eq('programme_id', filters.programme_id)
  }
  
  if (filters.project_id !== undefined) {
    if (filters.project_id === null) {
      query = query.is('project_id', null)
    } else {
      query = query.eq('project_id', filters.project_id)
    }
  }
  
  if (filters.search) {
    query = query.or(`mandate_title.ilike.%${filters.search}%,mandate_reference.ilike.%${filters.search}%,purpose.ilike.%${filters.search}%`)
  }
  
  const { data, error } = await query
    .order('created_date', { ascending: false })
  
  if (error) throw error
  return data || []
}

/**
 * Update an existing mandate
 * @param {string} mandateId - Mandate UUID
 * @param {object} updates - Mandate fields to update
 * @param {object} options - { skipEditCheck: true } when caller already verified editability (avoids redundant getMandateById)
 */
export async function updateMandate(mandateId, updates, options = {}) {
  // Run userId lookup and edit check in parallel (skip edit check when page already verified)
  const [userId, canEdit] = options.skipEditCheck
    ? [await getCurrentUserId(), true]
    : await Promise.all([
        getCurrentUserId(),
        canEditMandate(mandateId).catch(() => true)
      ])

  if (!canEdit) {
    throw new Error('Mandate cannot be edited (already approved or linked to project)')
  }

  // Extract fields stored in separate tables
  const { associated_documents, stakeholders, constraints, ...mainMandateData } = updates

  const updateData = {
    ...mainMandateData,
    updated_by: userId,
  }

  const { data: updatedMandate, error } = await platformDb
    .from('project_mandates')
    .update(updateData)
    .eq('id', mandateId)
    .select()
    .maybeSingle()

  if (error) throw error
  if (!updatedMandate) throw new Error('Mandate update did not affect any rows. Your changes may not have been saved. Check permissions or try again.')

  // Run associated_documents and stakeholders updates in parallel when both present
  const docPromise = associated_documents !== undefined && (async () => {
    try {
      await platformDb.from('mandate_associated_documents').delete().eq('mandate_id', mandateId)
      const documents = typeof associated_documents === 'string'
        ? JSON.parse(associated_documents || '[]')
        : associated_documents
      if (Array.isArray(documents) && documents.length > 0) {
        const docsToInsert = documents.map((doc, index) => ({
          mandate_id: mandateId,
          document_type: doc.document_type || 'other',
          document_title: doc.document_title,
          document_url: doc.document_url || null,
          reference_number: doc.reference_number || null,
          display_order: index,
          created_by: userId,
          updated_by: userId
        }))
        await platformDb.from('mandate_associated_documents').insert(docsToInsert)
      }
    } catch (err) {
      console.warn('Error updating associated documents:', err)
    }
  })()

  const stakeholderPromise = stakeholders !== undefined && (async () => {
    try {
      await platformDb.from('mandate_customers_users').delete().eq('mandate_id', mandateId)
      const stakeholderList = typeof stakeholders === 'string'
        ? JSON.parse(stakeholders || '[]')
        : stakeholders
      if (Array.isArray(stakeholderList) && stakeholderList.length > 0) {
        const stakeholdersToInsert = stakeholderList.map((stakeholder, index) => ({
          mandate_id: mandateId,
          stakeholder_type: stakeholder.stakeholder_type || 'customer',
          stakeholder_name: stakeholder.stakeholder_name,
          stakeholder_organisation: stakeholder.stakeholder_organisation || null,
          stakeholder_role: stakeholder.stakeholder_role || null,
          contact_email: stakeholder.contact_email || null,
          is_primary: stakeholder.is_primary || false,
          display_order: index,
          created_by: userId,
          updated_by: userId
        }))
        await platformDb.from('mandate_customers_users').insert(stakeholdersToInsert)
      }
    } catch (err) {
      console.warn('Error updating stakeholders:', err)
    }
  })()

  if (docPromise || stakeholderPromise) {
    await Promise.all([docPromise, stakeholderPromise].filter(Boolean))
  }

  return updatedMandate
}

/**
 * Delete a mandate (soft delete - only for drafts)
 */
export async function deleteMandate(mandateId) {
  const userId = await getCurrentUserId()
  
  // Only allow deletion of draft mandates
  const mandate = await getMandateById(mandateId)
  if (mandate.document_status !== 'draft') {
    throw new Error('Only draft mandates can be deleted')
  }
  
  if (mandate.project_id) {
    throw new Error('Cannot delete mandate linked to a project')
  }
  
  const { data, error } = await platformDb
    .from('project_mandates')
    .update({
      is_deleted: true,
      deleted_at: new Date().toISOString(),
      deleted_by: userId,
      updated_by: userId,
    })
    .eq('id', mandateId)
    .select()
    .single()
  
  if (error) throw error
  return data
}

/**
 * Archive a mandate (when no longer needed)
 */
export async function archiveMandate(mandateId) {
  const userId = await getCurrentUserId()
  
  const { data: result, error } = await platformDb.rpc('archive_mandate', {
    p_mandate_id: mandateId,
    p_user_id: userId
  })
  
  if (error) throw error
  
  // Return updated mandate
  return getMandateById(mandateId)
}

/**
 * Create project from approved mandate (CRITICAL FUNCTION)
 */
export async function createProjectFromMandate(mandateId) {
  const userId = await getCurrentUserId()
  
  // Call database function
  const { data: projectId, error } = await platformDb.rpc('create_project_from_mandate', {
    p_mandate_id: mandateId,
    p_user_id: userId
  })
  
  if (error) throw error
  
  // Return the new project ID
  return projectId
}

/**
 * Link an approved mandate to an existing project after project creation.
 * Called after the project is created via the standard ProjectsCreate form.
 */
export async function linkMandateToProject(mandateId, projectId) {
  const { error } = await platformDb
    .from('project_mandates')
    .update({
      project_id: projectId,
      project_created_date: new Date().toISOString()
    })
    .eq('id', mandateId)

  if (error) throw error
}

/**
 * Check if mandate can create a project
 */
export async function canCreateProject(mandateId) {
  const mandate = await getMandateById(mandateId)
  
  if (!mandate) return false
  if (mandate.document_status !== 'approved') return false
  if (mandate.project_id !== null) return false
  
  // Check minimum requirements
  const hasExecutive = mandate.proposed_executive_id || mandate.proposed_executive_name
  const hasPM = mandate.proposed_pm_id || mandate.proposed_pm_name
  if (!hasExecutive && !hasPM) return false
  
  return true
}

/**
 * Check if mandate can be edited
 */
export async function canEditMandate(mandateId, userId = null) {
  // Simple fallback check - RPC function may not exist
  // Check if mandate is in draft/rejected status and not linked to project
  try {
    const mandate = await getMandateById(mandateId)
    if (!mandate) return false

    // Can edit if: status is draft or rejected AND not linked to a project
    const canEdit = ['draft', 'rejected'].includes(mandate.document_status) && !mandate.project_id
    return canEdit
  } catch (error) {
    console.warn('canEditMandate check failed:', error)
    return false
  }
}

/**
 * Check if mandate is linked to a project
 */
export async function isLinkedToProject(mandateId) {
  const mandate = await getMandateById(mandateId)
  return mandate && mandate.project_id !== null
}

/**
 * Search objectives across all mandates
 * Returns mandates that contain objectives matching the search term
 * @param {string} searchTerm - Search term to match against objectives
 * @param {Object} filters - Additional filters (status, organisation, etc.)
 * @returns {Promise<Array>} Array of mandates with matching objectives
 */
export async function searchMandateObjectives(searchTerm, filters = {}) {
  if (!searchTerm || !searchTerm.trim()) {
    return []
  }

  let query = platformDb
    .from('project_mandates')
    .select(`
      id,
      mandate_reference,
      mandate_title,
      document_status,
      project_objectives,
      created_date,
      project:project_id (id, project_name, project_code)
    `)
    .eq('is_deleted', false)
    .ilike('project_objectives', `%${searchTerm}%`)

  if (filters.status) {
    query = query.eq('document_status', filters.status)
  }

  if (filters.organisation_id) {
    // Add organisation filter if needed
    // This would require joining through accounts/projects
  }

  const { data, error } = await query
    .order('created_date', { ascending: false })
    .limit(filters.limit || 100)

  if (error) throw error

  // Parse objectives and filter to only return mandates with matching objectives
  const results = (data || []).map(mandate => {
    let objectives = []
    try {
      const parsed = JSON.parse(mandate.project_objectives || '[]')
      objectives = Array.isArray(parsed) ? parsed : []
    } catch {
      // If not JSON, treat as single text
      objectives = mandate.project_objectives ? [mandate.project_objectives] : []
    }

    // Filter objectives that match search term
    const matchingObjectives = objectives.filter(obj => 
      obj.toLowerCase().includes(searchTerm.toLowerCase())
    )

    return {
      ...mandate,
      objectives: objectives,
      matchingObjectives: matchingObjectives,
      matchCount: matchingObjectives.length
    }
  }).filter(mandate => mandate.matchCount > 0)

  return results
}

/**
 * Search scope items (in-scope deliverables or exclusions) across all mandates
 * @param {string} searchTerm - Search term to match against scope items
 * @param {string} scopeType - 'in-scope' or 'out-of-scope'
 * @param {Object} filters - Additional filters (status, organisation, etc.)
 * @returns {Promise<Array>} Array of mandates with matching scope items
 */
export async function searchMandateScope(searchTerm, scopeType = 'in-scope', filters = {}) {
  if (!searchTerm || !searchTerm.trim()) {
    return []
  }

  const fieldName = scopeType === 'out-of-scope' ? 'scope_exclusions' : 'scope'

  let query = platformDb
    .from('project_mandates')
    .select(`
      id,
      mandate_reference,
      mandate_title,
      document_status,
      scope,
      scope_exclusions,
      created_date,
      project:project_id (id, project_name, project_code)
    `)
    .eq('is_deleted', false)
    .ilike(fieldName, `%${searchTerm}%`)

  if (filters.status) {
    query = query.eq('document_status', filters.status)
  }

  const { data, error } = await query
    .order('created_date', { ascending: false })
    .limit(filters.limit || 100)

  if (error) throw error

  // Parse scope items and filter to only return mandates with matching items
  const results = (data || []).map(mandate => {
    let scopeItems = []
    try {
      const parsed = JSON.parse(mandate[fieldName] || '[]')
      scopeItems = Array.isArray(parsed) ? parsed : []
    } catch {
      scopeItems = mandate[fieldName]?.trim() ? [mandate[fieldName]] : []
    }

    // Filter items that match search term
    const matchingItems = scopeItems.filter(item => 
      item.toLowerCase().includes(searchTerm.toLowerCase())
    )

    return {
      ...mandate,
      scopeItems: scopeItems,
      matchingItems: matchingItems,
      matchCount: matchingItems.length,
      scopeType: scopeType
    }
  }).filter(mandate => mandate.matchCount > 0)

  return results
}

/**
 * Search constraints across all mandates
 * @param {string} searchTerm - Search term to match against constraints
 * @param {Object} filters - Additional filters (status, organisation, etc.)
 * @returns {Promise<Array>} Array of mandates with matching constraints
 */
export async function searchMandateConstraints(searchTerm, filters = {}) {
  if (!searchTerm || !searchTerm.trim()) {
    return []
  }

  let query = platformDb
    .from('project_mandates')
    .select(`
      id,
      mandate_reference,
      mandate_title,
      document_status,
      constraints,
      created_date,
      project:project_id (id, project_name, project_code)
    `)
    .eq('is_deleted', false)
    .ilike('constraints', `%${searchTerm}%`)

  if (filters.status) {
    query = query.eq('document_status', filters.status)
  }

  const { data, error } = await query
    .order('created_date', { ascending: false })
    .limit(filters.limit || 100)

  if (error) throw error

  // Parse constraints and filter to only return mandates with matching constraints
  const results = (data || []).map(mandate => {
    let constraints = []
    try {
      const parsed = JSON.parse(mandate.constraints || '[]')
      constraints = Array.isArray(parsed) ? parsed : []
    } catch {
      constraints = mandate.constraints?.trim() ? [mandate.constraints] : []
    }

    // Filter constraints that match search term
    const matchingConstraints = constraints.filter(constraint => 
      constraint.toLowerCase().includes(searchTerm.toLowerCase())
    )

    return {
      ...mandate,
      constraints: constraints,
      matchingConstraints: matchingConstraints,
      matchCount: matchingConstraints.length
    }
  }).filter(mandate => mandate.matchCount > 0)

  return results
}

/**
 * Search authority items across all mandates
 * @param {string} searchTerm - Search term to match against authority items
 * @param {Object} filters - Additional filters (status, organisation, etc.)
 * @returns {Promise<Array>} Array of mandates with matching authority items
 */
export async function searchMandateAuthorities(searchTerm, filters = {}) {
  if (!searchTerm || !searchTerm.trim()) {
    return []
  }

  let query = platformDb
    .from('project_mandates')
    .select(`
      id,
      mandate_reference,
      mandate_title,
      document_status,
      authority_responsible,
      created_date,
      project:project_id (id, project_name, project_code)
    `)
    .eq('is_deleted', false)
    .ilike('authority_responsible', `%${searchTerm}%`)

  if (filters.status) {
    query = query.eq('document_status', filters.status)
  }

  const { data, error } = await query
    .order('created_date', { ascending: false })
    .limit(filters.limit || 100)

  if (error) throw error

  // Parse authorities and filter to only return mandates with matching items
  const results = (data || []).map(mandate => {
    let authorities = []
    try {
      const parsed = JSON.parse(mandate.authority_responsible || '[]')
      authorities = Array.isArray(parsed) ? parsed : []
    } catch {
      authorities = mandate.authority_responsible?.trim() ? [mandate.authority_responsible] : []
    }

    // Filter authorities that match search term
    const matchingAuthorities = authorities.filter(authority => 
      authority.toLowerCase().includes(searchTerm.toLowerCase())
    )

    return {
      ...mandate,
      authorities: authorities,
      matchingAuthorities: matchingAuthorities,
      matchCount: matchingAuthorities.length
    }
  }).filter(mandate => mandate.matchCount > 0)

  return results
}

/**
 * Search interfaces across all mandates
 * @param {string} searchTerm - Search term to match against interfaces
 * @param {Object} filters - Additional filters (status, organisation, etc.)
 * @returns {Promise<Array>} Array of mandates with matching interfaces
 */
export async function searchMandateInterfaces(searchTerm, filters = {}) {
  if (!searchTerm || !searchTerm.trim()) {
    return []
  }

  let query = platformDb
    .from('project_mandates')
    .select(`
      id,
      mandate_reference,
      mandate_title,
      document_status,
      interfaces,
      created_date,
      project:project_id (id, project_name, project_code)
    `)
    .eq('is_deleted', false)
    .ilike('interfaces', `%${searchTerm}%`)

  if (filters.status) {
    query = query.eq('document_status', filters.status)
  }

  const { data, error } = await query
    .order('created_date', { ascending: false })
    .limit(filters.limit || 100)

  if (error) throw error

  // Parse interfaces and filter to only return mandates with matching interfaces
  const results = (data || []).map(mandate => {
    let interfaces = []
    try {
      const parsed = JSON.parse(mandate.interfaces || '[]')
      interfaces = Array.isArray(parsed) ? parsed : []
    } catch {
      interfaces = mandate.interfaces?.trim() ? [mandate.interfaces] : []
    }

    // Filter interfaces that match search term
    const matchingInterfaces = interfaces.filter(interfaceItem => 
      interfaceItem.toLowerCase().includes(searchTerm.toLowerCase())
    )

    return {
      ...mandate,
      interfaces: interfaces,
      matchingInterfaces: matchingInterfaces,
      matchCount: matchingInterfaces.length
    }
  }).filter(mandate => mandate.matchCount > 0)

  return results
}

/**
 * Search quality expectations across all mandates
 * @param {string} searchTerm - Search term to match against quality expectations
 * @param {Object} filters - Additional filters (status, organisation, etc.)
 * @returns {Promise<Array>} Array of mandates with matching quality expectations
 */
export async function searchMandateQualityExpectations(searchTerm, filters = {}) {
  if (!searchTerm || !searchTerm.trim()) {
    return []
  }

  let query = platformDb
    .from('project_mandates')
    .select(`
      id,
      mandate_reference,
      mandate_title,
      document_status,
      quality_expectations,
      created_date,
      project:project_id (id, project_name, project_code)
    `)
    .eq('is_deleted', false)
    .ilike('quality_expectations', `%${searchTerm}%`)

  if (filters.status) {
    query = query.eq('document_status', filters.status)
  }

  const { data, error } = await query
    .order('created_date', { ascending: false })
    .limit(filters.limit || 100)

  if (error) throw error

  // Parse quality expectations and filter to only return mandates with matching items
  const results = (data || []).map(mandate => {
    let expectations = []
    try {
      const parsed = JSON.parse(mandate.quality_expectations || '[]')
      expectations = Array.isArray(parsed) ? parsed : []
    } catch {
      expectations = mandate.quality_expectations?.trim() ? [mandate.quality_expectations] : []
    }

    // Filter expectations that match search term
    const matchingExpectations = expectations.filter(expectation => 
      expectation.toLowerCase().includes(searchTerm.toLowerCase())
    )

    return {
      ...mandate,
      expectations: expectations,
      matchingExpectations: matchingExpectations,
      matchCount: matchingExpectations.length
    }
  }).filter(mandate => mandate.matchCount > 0)

  return results
}

// ============================================================================
// Section Management - Deliverables
// ============================================================================

export async function addDeliverable(mandateId, deliverableData) {
  const userId = await getCurrentUserId()
  
  const { data, error } = await platformDb
    .from('mandate_deliverables')
    .insert({
      ...deliverableData,
      mandate_id: mandateId,
      created_by: userId,
      updated_by: userId,
    })
    .select()
    .single()
  
  if (error) throw error
  return data
}

export async function updateDeliverable(deliverableId, updates) {
  const userId = await getCurrentUserId()
  
  const { data, error } = await platformDb
    .from('mandate_deliverables')
    .update({
      ...updates,
      updated_by: userId,
    })
    .eq('id', deliverableId)
    .select()
    .single()
  
  if (error) throw error
  return data
}

export async function deleteDeliverable(deliverableId) {
  const userId = await getCurrentUserId()
  
  const { data, error } = await platformDb
    .from('mandate_deliverables')
    .update({
      is_deleted: true,
      updated_by: userId,
    })
    .eq('id', deliverableId)
    .select()
    .single()
  
  if (error) throw error
  return data
}

export async function getDeliverables(mandateId) {
  const { data, error } = await platformDb
    .from('mandate_deliverables')
    .select('*')
    .eq('mandate_id', mandateId)
    .eq('is_deleted', false)
    .order('display_order', { ascending: true })
  
  if (error) throw error
  return data || []
}

// ============================================================================
// Section Management - Dependencies
// ============================================================================

export async function addDependency(mandateId, dependencyData) {
  const userId = await getCurrentUserId()
  
  const { data, error } = await platformDb
    .from('mandate_dependencies')
    .insert({
      ...dependencyData,
      mandate_id: mandateId,
      created_by: userId,
      updated_by: userId,
    })
    .select()
    .single()
  
  if (error) throw error
  return data
}

export async function updateDependency(dependencyId, updates) {
  const userId = await getCurrentUserId()
  
  const { data, error } = await platformDb
    .from('mandate_dependencies')
    .update({
      ...updates,
      updated_by: userId,
    })
    .eq('id', dependencyId)
    .select()
    .single()
  
  if (error) throw error
  return data
}

export async function deleteDependency(dependencyId) {
  const userId = await getCurrentUserId()
  
  const { data, error } = await platformDb
    .from('mandate_dependencies')
    .update({
      is_deleted: true,
      updated_by: userId,
    })
    .eq('id', dependencyId)
    .select()
    .single()
  
  if (error) throw error
  return data
}

export async function getDependencies(mandateId) {
  const { data, error } = await platformDb
    .from('mandate_dependencies')
    .select('*')
    .eq('mandate_id', mandateId)
    .eq('is_deleted', false)
    .order('display_order', { ascending: true })
  
  if (error) throw error
  return data || []
}

// ============================================================================
// Section Management - Associated Documents
// ============================================================================

export async function addAssociatedDocument(mandateId, documentData) {
  const userId = await getCurrentUserId()
  
  const { data, error } = await platformDb
    .from('mandate_associated_documents')
    .insert({
      ...documentData,
      mandate_id: mandateId,
      created_by: userId,
      updated_by: userId,
    })
    .select()
    .single()
  
  if (error) throw error
  return data
}

export async function updateAssociatedDocument(documentId, updates) {
  const userId = await getCurrentUserId()
  
  const { data, error } = await platformDb
    .from('mandate_associated_documents')
    .update({
      ...updates,
      updated_by: userId,
    })
    .eq('id', documentId)
    .select()
    .single()
  
  if (error) throw error
  return data
}

export async function deleteAssociatedDocument(documentId) {
  const userId = await getCurrentUserId()
  
  const { data, error } = await platformDb
    .from('mandate_associated_documents')
    .update({
      is_deleted: true,
      updated_by: userId,
    })
    .eq('id', documentId)
    .select()
    .single()
  
  if (error) throw error
  return data
}

export async function getAssociatedDocuments(mandateId) {
  const { data, error } = await platformDb
    .from('mandate_associated_documents')
    .select('*')
    .eq('mandate_id', mandateId)
    .eq('is_deleted', false)
    .order('display_order', { ascending: true })
  
  if (error) throw error
  return data || []
}

// ============================================================================
// Section Management - Stakeholders
// ============================================================================

export async function addStakeholder(mandateId, stakeholderData) {
  const userId = await getCurrentUserId()
  
  const { data, error } = await platformDb
    .from('mandate_customers_users')
    .insert({
      ...stakeholderData,
      mandate_id: mandateId,
      created_by: userId,
      updated_by: userId,
    })
    .select()
    .single()
  
  if (error) throw error
  return data
}

export async function updateStakeholder(stakeholderId, updates) {
  const userId = await getCurrentUserId()
  
  const { data, error } = await platformDb
    .from('mandate_customers_users')
    .update({
      ...updates,
      updated_by: userId,
    })
    .eq('id', stakeholderId)
    .select()
    .single()
  
  if (error) throw error
  return data
}

export async function deleteStakeholder(stakeholderId) {
  const userId = await getCurrentUserId()
  
  const { data, error } = await platformDb
    .from('mandate_customers_users')
    .update({
      is_deleted: true,
      updated_by: userId,
    })
    .eq('id', stakeholderId)
    .select()
    .single()
  
  if (error) throw error
  return data
}

export async function getStakeholders(mandateId) {
  const { data, error } = await platformDb
    .from('mandate_customers_users')
    .select('*')
    .eq('mandate_id', mandateId)
    .eq('is_deleted', false)
    .order('display_order', { ascending: true })
  
  if (error) throw error
  return data || []
}

// ============================================================================
// Validation Functions
// ============================================================================

/**
 * Validate mandate completeness
 */
export async function validateMandate(mandateId) {
  const mandate = await getMandateById(mandateId)
  const deliverables = await getDeliverables(mandateId)
  const stakeholders = await getStakeholders(mandateId)
  
  const errors = []
  
  // Required fields
  if (!mandate.mandate_title) errors.push('Mandate title is required')
  if (!mandate.purpose || mandate.purpose.length < 20) errors.push('Purpose must be at least 20 characters')
  if (!mandate.background || mandate.background.length < 100) errors.push('Background must be at least 100 characters')
  if (!mandate.project_objectives || mandate.project_objectives.length < 100) errors.push('Project objectives must be at least 100 characters')
  if (!mandate.outline_business_case || mandate.outline_business_case.length < 100) errors.push('Outline business case must be at least 100 characters')
  
  // Required for submission
  if (deliverables.length === 0) errors.push('At least one deliverable is required')
  if (stakeholders.length === 0) errors.push('At least one customer/user is required')
  
  return {
    isValid: errors.length === 0,
    errors
  }
}

/**
 * Check completeness - returns completion % for 12 sections
 */
export async function checkCompleteness(mandateId) {
  const mandate = await getMandateById(mandateId)
  const deliverables = await getDeliverables(mandateId)
  const dependencies = await getDependencies(mandateId)
  const stakeholders = await getStakeholders(mandateId)
  const documents = await getAssociatedDocuments(mandateId)
  
  const sections = {
    purpose: !!mandate.purpose && mandate.purpose.length >= 20,
    authority: !!mandate.authority_responsible,
    background: !!mandate.background && mandate.background.length >= 100,
    objectives: !!mandate.project_objectives && mandate.project_objectives.length >= 100,
    scope: deliverables.length > 0,
    constraints: !!mandate.constraints,
    interfaces: !!mandate.interfaces,
    quality: !!mandate.quality_expectations && !!mandate.quality_priority,
    businessCase: !!mandate.outline_business_case && mandate.outline_business_case.length >= 100,
    documents: documents.length > 0,
    roles: !!(mandate.proposed_executive_id || mandate.proposed_executive_name || mandate.proposed_pm_id || mandate.proposed_pm_name),
    stakeholders: stakeholders.length > 0,
  }
  
  const completed = Object.values(sections).filter(Boolean).length
  const total = Object.keys(sections).length
  
  return {
    percentage: Math.round((completed / total) * 100),
    completed,
    total,
    sections
  }
}

/**
 * Check if mandate can be submitted for review
 */
export async function canSubmitForReview(mandateId) {
  const validation = await validateMandate(mandateId)
  return validation.isValid
}

/**
 * Check if mandate can be submitted for approval
 */
export async function canSubmitForApproval(mandateId) {
  const mandate = await getMandateById(mandateId)
  
  if (mandate.document_status !== 'submitted') return false
  
  // Check if all reviewers have reviewed
  // TODO: Implement reviewer completion check
  
  return true
}

/**
 * Check if mandate is editable
 */
export async function isEditable(mandateId) {
  return await canEditMandate(mandateId)
}
