/**
 * Simulator Mandate Service
 * Handles simulated project mandate operations for learning/practice
 * 
 * IMPORTANT: Uses simDb (sim schema) - NOT platformDb (public schema)
 * These are for learning only - don't create real projects
 */

import { simDb } from './supabase/supabaseClient'

/**
 * Get current user ID from auth
 */
async function getCurrentUserId() {
  const { data: { user } } = await simDb.auth.getUser()
  if (!user) throw new Error('User not authenticated')
  return user.id
}

/**
 * Create a simulated mandate (for learning/practice)
 */
export async function createSimMandate(mandateData) {
  const userId = await getCurrentUserId()
  
  const insertData = {
    ...mandateData,
    user_id: userId,
    document_status: mandateData.document_status || 'draft',
    version_number: mandateData.version_number || '1.0',
    created_date: mandateData.created_date || new Date().toISOString().split('T')[0],
    is_standalone: mandateData.is_standalone !== undefined ? mandateData.is_standalone : true,
    quality_priority: mandateData.quality_priority || 'balanced',
    is_active: true,
    is_practice_mode: true, // Always true for simulator
  }
  
  // mandate_reference will be auto-generated by trigger if not provided
  
  const { data, error } = await simDb
    .from('project_mandates')
    .insert(insertData)
    .select()
    .single()
  
  if (error) throw error
  return data
}

/**
 * Get simulated mandate by ID
 */
export async function getSimMandateById(mandateId) {
  const { data, error } = await simDb
    .from('project_mandates')
    .select(`
      *,
      simulation_run:simulation_run_id (id, status, scenario_id, started_at)
    `)
    .eq('id', mandateId)
    .eq('is_active', true)
    .single()
  
  if (error) throw error
  return data
}

/**
 * Get all simulated mandates for current user
 */
export async function getAllSimMandates(filters = {}) {
  const userId = await getCurrentUserId()
  
  let query = simDb
    .from('project_mandates')
    .select(`
      *,
      simulation_run:simulation_run_id (id, status, scenario_id)
    `)
    .eq('user_id', userId)
    .eq('is_active', true)
  
  if (filters.status) {
    query = query.eq('document_status', filters.status)
  }
  
  if (filters.simulation_run_id) {
    query = query.eq('simulation_run_id', filters.simulation_run_id)
  }
  
  if (filters.search) {
    query = query.or(`mandate_title.ilike.%${filters.search}%,mandate_reference.ilike.%${filters.search}%`)
  }
  
  const { data, error } = await query
    .order('created_date', { ascending: false })
  
  if (error) throw error
  return data || []
}

/**
 * Update simulated mandate
 */
export async function updateSimMandate(mandateId, updates) {
  const userId = await getCurrentUserId()
  
  // Only allow updates if user owns the mandate
  const mandate = await getSimMandateById(mandateId)
  if (mandate.user_id !== userId) {
    throw new Error('You can only edit your own mandates')
  }
  
  // Can't edit if approved (unless it's practice mode - we're lenient for learning)
  if (mandate.document_status === 'approved' && !mandate.is_practice_mode) {
    throw new Error('Approved mandates cannot be edited')
  }
  
  const { data, error } = await simDb
    .from('project_mandates')
    .update({
      ...updates,
      updated_at: new Date().toISOString(),
    })
    .eq('id', mandateId)
    .select()
    .single()
  
  if (error) throw error
  return data
}

/**
 * Delete simulated mandate (practice only)
 */
export async function deleteSimMandate(mandateId) {
  const userId = await getCurrentUserId()
  
  // Only allow deletion if user owns it
  const mandate = await getSimMandateById(mandateId)
  if (mandate.user_id !== userId) {
    throw new Error('You can only delete your own mandates')
  }
  
  const { data, error } = await simDb
    .from('project_mandates')
    .update({
      is_active: false,
      updated_at: new Date().toISOString(),
    })
    .eq('id', mandateId)
    .select()
    .single()
  
  if (error) throw error
  return data
}

/**
 * Submit simulated mandate for review (practice workflow)
 */
export async function submitSimMandateForReview(mandateId) {
  return updateSimMandate(mandateId, {
    document_status: 'submitted'
  })
}

/**
 * Approve simulated mandate (practice workflow)
 */
export async function approveSimMandate(mandateId) {
  return updateSimMandate(mandateId, {
    document_status: 'approved'
  })
}

// ============================================================================
// Section Management - Deliverables
// ============================================================================

export async function addSimDeliverable(mandateId, deliverableData) {
  const { data, error } = await simDb
    .from('mandate_deliverables')
    .insert({
      ...deliverableData,
      mandate_id: mandateId,
    })
    .select()
    .single()
  
  if (error) throw error
  return data
}

export async function updateSimDeliverable(deliverableId, updates) {
  const { data, error } = await simDb
    .from('mandate_deliverables')
    .update({
      ...updates,
      updated_at: new Date().toISOString(),
    })
    .eq('id', deliverableId)
    .select()
    .single()
  
  if (error) throw error
  return data
}

export async function deleteSimDeliverable(deliverableId) {
  const { error } = await simDb
    .from('mandate_deliverables')
    .delete()
    .eq('id', deliverableId)
  
  if (error) throw error
  return true
}

export async function getSimDeliverables(mandateId) {
  const { data, error } = await simDb
    .from('mandate_deliverables')
    .select('*')
    .eq('mandate_id', mandateId)
    .order('display_order', { ascending: true })
  
  if (error) throw error
  return data || []
}

// ============================================================================
// Section Management - Stakeholders
// ============================================================================

export async function addSimStakeholder(mandateId, stakeholderData) {
  const { data, error } = await simDb
    .from('mandate_stakeholders')
    .insert({
      ...stakeholderData,
      mandate_id: mandateId,
    })
    .select()
    .single()
  
  if (error) throw error
  return data
}

export async function updateSimStakeholder(stakeholderId, updates) {
  const { data, error } = await simDb
    .from('mandate_stakeholders')
    .update({
      ...updates,
      updated_at: new Date().toISOString(),
    })
    .eq('id', stakeholderId)
    .select()
    .single()
  
  if (error) throw error
  return data
}

export async function deleteSimStakeholder(stakeholderId) {
  const { error } = await simDb
    .from('mandate_stakeholders')
    .delete()
    .eq('id', stakeholderId)
  
  if (error) throw error
  return true
}

export async function getSimStakeholders(mandateId) {
  const { data, error } = await simDb
    .from('mandate_stakeholders')
    .select('*')
    .eq('mandate_id', mandateId)
    .order('display_order', { ascending: true })
  
  if (error) throw error
  return data || []
}

// ============================================================================
// Validation Functions (for learning feedback)
// ============================================================================

/**
 * Validate simulated mandate completeness (for learning feedback)
 */
export async function validateSimMandate(mandateId) {
  const mandate = await getSimMandateById(mandateId)
  const deliverables = await getSimDeliverables(mandateId)
  const stakeholders = await getSimStakeholders(mandateId)
  
  const errors = []
  const warnings = []
  
  // Required fields
  if (!mandate.mandate_title) errors.push('Mandate title is required')
  if (!mandate.purpose || mandate.purpose.length < 20) errors.push('Purpose must be at least 20 characters')
  if (!mandate.background || mandate.background.length < 100) errors.push('Background must be at least 100 characters')
  if (!mandate.project_objectives || mandate.project_objectives.length < 100) errors.push('Project objectives must be at least 100 characters')
  if (!mandate.outline_business_case || mandate.outline_business_case.length < 100) errors.push('Outline business case must be at least 100 characters')
  
  // Learning recommendations
  if (deliverables.length === 0) warnings.push('Consider adding at least one deliverable')
  if (stakeholders.length === 0) warnings.push('Consider identifying customers/users')
  if (!mandate.proposed_executive_name && !mandate.proposed_pm_name) warnings.push('Consider identifying proposed Executive or PM')
  
  // Calculate practice score (for learning feedback)
  const totalChecks = 7
  const passedChecks = totalChecks - errors.length
  const practiceScore = Math.round((passedChecks / totalChecks) * 100)
  
  return {
    isValid: errors.length === 0,
    errors,
    warnings,
    practiceScore,
    feedback: errors.length === 0 
      ? 'Great work! Your mandate meets all requirements.' 
      : 'Review the errors above to improve your mandate.'
  }
}

/**
 * Create a practice project from an approved simulated mandate
 * @param {string} mandateId - The ID of the approved mandate
 * @param {string} simulationRunId - Optional simulation run ID for full lifecycle practice
 * @returns {Promise<string>} The ID of the newly created practice project
 */
export async function createPracticeProjectFromMandate(mandateId, simulationRunId = null) {
  const userId = await getCurrentUserId()
  
  // Validate mandate is approved
  const mandate = await getSimMandateById(mandateId)
  if (mandate.document_status !== 'approved') {
    throw new Error('Only approved practice mandates can create practice projects')
  }
  
  const { data, error } = await simDb.rpc('create_practice_project_from_mandate', {
    p_mandate_id: mandateId,
    p_user_id: userId,
    p_simulation_run_id: simulationRunId
  })
  
  if (error) throw error
  return data
}

/**
 * Check if a practice project can be created from a mandate
 * @param {string} mandateId - The ID of the mandate
 * @returns {Promise<boolean>} True if a practice project can be created
 */
export async function canCreatePracticeProject(mandateId) {
  try {
    const mandate = await getSimMandateById(mandateId)
    return (
      mandate.document_status === 'approved' &&
      mandate.is_practice_mode === true
    )
  } catch (error) {
    console.error('Error checking practice project creation eligibility:', error)
    return false
  }
}

/**
 * Get practice projects created from a mandate
 * @param {string} mandateId - The ID of the mandate
 * @returns {Promise<array>} List of practice projects
 */
export async function getPracticeProjectsFromMandate(mandateId) {
  const { data, error } = await simDb
    .from('practice_projects')
    .select('*')
    .eq('mandate_id', mandateId)
    .eq('is_practice_mode', true)
    .order('created_at', { ascending: false })
  
  if (error) throw error
  return data || []
}

/**
 * Calculate learning progress (completion %)
 */
export async function getSimMandateProgress(mandateId) {
  const mandate = await getSimMandateById(mandateId)
  const deliverables = await getSimDeliverables(mandateId)
  const stakeholders = await getSimStakeholders(mandateId)
  
  const sections = {
    purpose: !!mandate.purpose && mandate.purpose.length >= 20,
    authority: !!mandate.authority_responsible,
    background: !!mandate.background && mandate.background.length >= 100,
    objectives: !!mandate.project_objectives && mandate.project_objectives.length >= 100,
    scope: deliverables.length > 0,
    constraints: !!mandate.constraints,
    interfaces: !!mandate.interfaces,
    quality: !!mandate.quality_expectations && !!mandate.quality_priority,
    businessCase: !!mandate.outline_business_case && mandate.outline_business_case.length >= 100,
    roles: !!(mandate.proposed_executive_name || mandate.proposed_pm_name),
    stakeholders: stakeholders.length > 0,
  }
  
  const completed = Object.values(sections).filter(Boolean).length
  const total = Object.keys(sections).length
  
  return {
    percentage: Math.round((completed / total) * 100),
    completed,
    total,
    sections
  }
}
