import { Navigate, useParams, useLocation } from 'react-router-dom'
import { useState, useEffect } from 'react'
import * as LP from './lazyImports'

const LOADING_TIMEOUT_MS = 10000

/** Shows spinner first; after LOADING_TIMEOUT_MS shows "Taking too long? Refresh" so the page never hangs forever. */
function LoadingFallbackWithTimeout() {
  const [timedOut, setTimedOut] = useState(false)
  useEffect(() => {
    const id = setTimeout(() => setTimedOut(true), LOADING_TIMEOUT_MS)
    return () => clearTimeout(id)
  }, [])
  if (timedOut) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center bg-gray-50 dark:bg-gray-900 p-4">
        <p className="text-gray-600 dark:text-gray-400 text-center mb-4">Taking too long? The page may have failed to load.</p>
        <button
          type="button"
          onClick={() => window.location.reload()}
          className="px-4 py-2 rounded-lg bg-blue-600 text-white hover:bg-blue-700 focus:ring-2 focus:ring-blue-500"
        >
          Refresh page
        </button>
      </div>
    )
  }
  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-900">
      <div className="text-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto mb-4" aria-hidden="true" />
        <p className="text-gray-600 dark:text-gray-400">Loading...</p>
      </div>
    </div>
  )
}
/** Template library lives under `/platform/templates`, not `projects/:id`. */
function RedirectProjectsTemplatesToLibrary() {
  const { '*': rest } = useParams()
  const { search, hash } = useLocation()
  const suffix = rest ? `/${rest}` : ''
  return <Navigate to={{ pathname: `/platform/templates${suffix}`, search, hash }} replace />
}
// Loading fallback: spinner first, then "Refresh page" after timeout so the app never hangs forever
const LoadingFallback = () => <LoadingFallbackWithTimeout />

// Login page skeleton - renders instantly while login chunk loads
const LoginPageSkeleton = () => (
  <div className="min-h-screen bg-gray-50 dark:bg-gray-900 flex flex-col">
    <div className="h-16 bg-gray-800/90" />
    <div className="flex-1 flex items-center justify-center py-12 px-4">
      <div className="max-w-md w-full">
        <div className="flex justify-center mb-6">
          <div className="h-16 w-16 rounded-full bg-gray-200 dark:bg-gray-700 animate-pulse" />
        </div>
        <div className="h-8 w-48 mx-auto bg-gray-200 dark:bg-gray-700 rounded animate-pulse mb-2" />
        <div className="h-4 w-64 mx-auto bg-gray-100 dark:bg-gray-800 rounded animate-pulse mb-8" />
        <div className="space-y-4">
          <div className="h-12 bg-gray-200 dark:bg-gray-700 rounded-lg animate-pulse" />
          <div className="h-12 bg-gray-200 dark:bg-gray-700 rounded-lg animate-pulse" />
        </div>
        <div className="mt-6 h-10 bg-blue-600/80 rounded-lg animate-pulse" />
      </div>
    </div>
    <div className="h-48 bg-gray-900" />
  </div>
)


const {
  NidusHomepage, ThemeProvider, ToastProvider, Layout, ProtectedRoute, Home, PlatformHomepage,
  SimulatorHomepage, Documentation, FeaturesPage, BlogPage, ResourcesPage, PricingPage,
  PlatformPricing, BundlePricing, SimulatorPricing, AboutPage, ContactPage, PlatformRequestDemoPage,
  PlatformAffiliatePage, SimulatorRequestDemoPage, SimulatorAffiliatePage, Projects, ProjectsCreate, ProjectsDetail, LocalDataExtensionsRoutes,
  SimulatorLocalDataExtensionsRoutes, ProjectsEdit, ScopeManagementPlanPage, ScopeStatementPage,
  RequirementsRegisterPage, RequirementDetailPage, TraceabilityMatrixPage, WBSBuilderPage,
  ScheduleManagementPlanPage, ActivityListPage, ActivityDetailPage, ActivitySequencingPage,
  GanttChartPage, ProjectsOnHold, BenefitsOnHold, StakeholdersOnHold, IssuesOnHold, RisksOnHold,
  QualityOnHold, DraftExpiryConfig, Tasks, TasksBoard, TasksCalendar, TasksCreate, TasksDetail,
  MethodologySelection, PlatformDashboard, SimulatorDashboard, SimulationSetup,
  SimulationRunDashboard, SimEventInbox, SimStageGateReview, SimExceptionReportFlow, SimEVMDashboard,
  SimulationRunHistory, SimulationDebrief, SimLiveRunRedirect, SimAIWorkspace, AIWorkspace,
  SubmitFeedback, PMODashboard, PMDashboard, PMOLayout, PMLayout, PMOGovernanceMandateTemplate,
  PMOGovernanceCMS, PMOGovernanceConfigMS, PMOGovernanceQMS, PMOGovernanceRMS,
  PMOInitiationBusinessCase, PMOInitiationProjectBrief, PMOInitiationBenefitsReviewPlan,
  PMOOversightRiskRegister, PMOOversightIssueRegister, PMOOversightQualityRegister,
  PMOOversightChangeRegister, PMOOversightLessonsLog, PMOOversightScope, PMOOversightSchedules,
  PMOReportingHighlight, PMOReportingException, PMOReportingEndStage, PMOReportingEndProject,
  PMOProcurementRFP, PMORFPView, PMORFPCreate, PMORFPEdit, PMORFPBulkImport, PMORFPPrint,
  PMORFPOnHold, PMGovernanceMandateTemplate, PMGovernanceCMS, PMGovernanceConfigMS, PMGovernanceQMS,
  PMGovernanceRMS, PMInitiationBusinessCase, PMInitiationProjectBrief, PMInitiationPID,
  PMInitiationBenefitsReviewPlan, PMDeliveryWorkPackages, PMDeliveryProductDescription,
  PMDeliveryProjectProductDescription, PMDeliveryProductStatusAccount, PMDeliveryDailyLog,
  PMControlsRiskRegister, PMControlsIssueRegister, PMControlsQualityRegister, PMControlsConfigItems,
  PMControlsLessonsLog, PMReportingCheckpoint, PMReportingHighlight, PMReportingIssueReports,
  PMReportingException, PMReportingEndStage, PMClosureLessonsReport, PMClosureEndProjectReport,
  Dashboard, Teams, MyTeam, Governance, Portfolio, PortfolioCreatePage, PortfolioFormPage,
  PortfolioDashboard, PortfolioProjects, PortfolioResources, PortfolioFinancial, PortfolioReports,
  PortfolioGovernance, PortfolioCategories, Programme, ProgrammeDetailPage, ProgrammeCreatePage,
  ProgrammeEditPage, ProgrammeDashboardOverview, ProgrammeProjectsPage, ProgrammeDependenciesPage,
  ProgrammeBenefitsPage, ProgrammeTimelinePage, ProgrammeReportsPage, Strategy, StrategicObjectives,
  StrategicAlignment, StrategicContribution, StrategicPortfolio, StrategicReports, Quality,
  QualityManagement, QualityReviews, QualityInspections, QualityReports, QualityActivityView,
  MyQualityActions, Stakeholders, StakeholderRegisterPage, StakeholderFormPage,
  StakeholderProfilePage, StakeholderAnalysisPage, StakeholderEngagementPage, CommunicationPlanPage,
  StakeholderMonitoringPage, StakeholderAssessmentMatrixPage, StakeholdersAssessmentMatrixOnHold,
  TestDashboard, TestSuites, TestSuiteDetail, TestCases, TestCaseCreate, TestCaseDetail,
  TestCaseBulkUpload, TestRuns, TestRunDetail, TestRunExecute, DefectListPage, DefectDetailPage,
  DefectDashboardPage, SimTestDashboard, SimTestSuites, SimTestSuiteDetail, SimTestCases,
  SimTestCaseCreate, SimTestCaseDetail, SimTestCaseBulkUpload, SimTestRuns, SimTestRunDetail,
  SimTestRunExecute, SimDefectListPage, SimDefectDetailPage, SimDefectDashboardPage,
  BrandingSettings, BrandingHistory, PMOAdmin, PmoAdminUserManagement, ProjectTypes, ProjectStatuses, FundingSources,
  BudgetCategories, ManagerAssignments, AppointmentDashboard, MyAppointments,
  TeamAppointmentDashboard, MyTeamAppointments, SimAppointmentDashboard, SimMyAppointments,
  SimTeamAppointmentDashboard, SimMyTeamAppointments, PortfolioManagerAssignments,
  ProgrammeManagerAssignments, ManagerAssignmentSettings, PMORoleMenuManagement,
  AdminRoleMenuManagement, AuthenticationSettings, SecuritySettings, PWASettingsV675,
  ExecutiveDashboard, SubscriptionManagement, OrganisationProfile, StageGateList, StageGateForm,
  StageGateView, GovernanceFrameworkList, GovernanceFrameworkForm, PoliciesComplianceList,
  PoliciesComplianceForm, PoliciesComplianceView, IntelligenceRulesPage, GovernanceRulesConfigPage,
  CustomMetricsPage, WorkstreamPlanList, WorkstreamPlanForm, LeaderboardAdmin, CertificateAdmin,
  ScenarioAdmin, SimUserManagement, DocumentationAdminList, DocumentationAdminEditor, ProjectCostManagement, ProjectBudgetBaseline, ProjectEVMPage, ProjectsEVMLandingPage,
  ProgrammeEVMPage, ProgrammeEVMLandingPage, PortfolioEVMPage, ProgrammeFinancialDashboard, ProjectProfitability, MyExpenses,
  ExpenseApproval, ExpenseApprovalThresholds, FinancialReportingHub, SimProjectCostManagement,
  SimProjectBudgetBaseline, SimProjectEVMPage, SimProgrammeEVMPage, SimPortfolioEVMPage,
  SimProgrammeFinancialDashboard, SimProjectProfitability, SimMyExpenses, SimExpenseApproval,
  SimExpenseApprovalThresholds, SimFinancialReportingHub, SimSprintMetricsDashboard,
  SimAgileTemplates, SimStoryMap, SimAgileReleases, SimAgileReleaseDetail, SimAgileRoadmap,
  SimXPDashboard, SimValueStreamMap, SimKaizenBoard, SimLeanMetrics, SimScrumOfScrums,
  SimAgileMetricsHub, SimKanbanMetrics, LifecycleTemplates, Reports, OrgKnowledgeHub, EEFList,
  EEFCreate, EEFDetail, EEFEdit, EEFOnHold, EEFBulkUpload, ITTOTemplateList, ProjectITTOList,
  ITTODraftsQueue, IndustryTemplateList, LegacyTemplateUploadPage, LegacyReferenceTemplatesPage,
  PMOInvitationTracker, PMInvitationTracker,
  InvitationDetailPage, IndustryTemplateForm, IndustryTemplateDetail, IndustryTemplateOnHold,
  IndustryTemplateBrowser, IndustryPlanCopyWizard, ProjectIndustryPlanView,
  SimIndustryTemplateBrowser, SimIndustryPlanCopy, SimPracticeIndustryPlan, SimITTOTemplateList,
  SimProjectITTOList, SimITTODraftsQueue, DelayRegister, DelayTemplates, SimDelayRegister,
  SimDelayTemplates, PlanningHub, PlanningIntelligenceDashboard, ScenarioList, PBSBuilder,
  PlanHealthDashboard, AIPlanGenerator, ExecutivePlanView, PortfolioCollisionDashboard,
  RecoveryPlanningView, ConfidenceForecastView, GovernanceGateChecklist, MicroPlanList,
  MicroPlanDetail, MicroPlanDraftQueue, MicroPlanForm, TeamCharterPage, TeamCharterEditPage,
  DecisionLogPage, DecisionLogForm, DecisionLogDetail, MyTimesheetsPage, TimesheetEntryForm,
  TimesheetEntryDetail, TeamTimesheetsPage, TeamChatPage, VideoCallsPage, VoiceCallsPage, OPAList,
  OPACreate, OPADetail, OPAEdit, OPAOnHold, OPABulkUpload, SimEEFList, SimEEFCreate, SimEEFDetail,
  SimEEFEdit, SimEEFOnHold, SimEEFBulkUpload, SimOPAList, SimOPACreate, SimOPADetail, SimOPAEdit,
  SimOPAOnHold, SimOPABulkUpload, TemplateLibraryList, TemplateLibraryManage, PmOrganisationalTemplatesPage, PmOrganisationalTemplateDetailPage, ProjectTemplatesEntry, OrganisationalTemplatesEntry, ProjectDocumentsEntry, DocumentOversightPortfolioPage, DocumentOversightProgrammePage, DocumentOversightPmoPage, TemplateCreate,
  TemplateEdit, TemplateDetail, TemplateMasterVersionHistory, TemplateCategories, TemplateBulkUpload,
  TemplateUpdateNotifications, ProjectTemplateCopyList, ProjectTemplateCopyCreate,
  ProjectTemplateCopyEdit, ProjectTemplateCopyDetail, ProjectTemplateCopyVersionHistory,
  ProjectOPATemplates, ProjectOPACopy, ProjectOPACustomisationDetail, TemplateOnHold,
  SimTemplateLibraryList, SimTemplateLibraryManage, SimTemplateCreate, SimTemplateEdit,
  SimTemplateDetail, SimTemplateMasterVersionHistory, SimTemplateCategories, SimTemplateBulkUpload,
  SimTemplateUpdateNotifications, SimProjectTemplateCopyList, SimProjectTemplateCopyCreate,
  SimProjectTemplateCopyEdit, SimProjectTemplateCopyDetail, SimProjectTemplateCopyVersionHistory,
  SimTemplateOnHold, CommsHub, DirectMessages, ChannelView, MeetingList, MeetingSchedule,
  MeetingRoom, MeetingDetail, MeetingSummaryView, PendingAIReview, MeetingExtractionReview,
  ExtractedIssueEnrich, ExtractedRiskEnrich, DocumentGovernance, DocumentRegister,
  DocumentCompliance, ProgrammeDocuments, MethodologyDashboard, StartingUpProject, InitiatingProject,
  StageGates, ControllingStage, ManagingProductDelivery, DirectingProject, PlansDashboard,
  ProjectPlanCreate, ProjectPlanEdit, ProjectPlanViewPage, StagePlanCreate, StagePlanEdit,
  StagePlanViewPage, ProductDescriptionList, ProductDescriptionCreate, ProductDescriptionEdit,
  ProductDescriptionViewPage, ProductDescriptionTemplates, ProductStatusAccountList,
  ProductStatusAccountViewPage, ProductStatusAccountCreate, ProductStatusAccountEdit,
  ProductStatusAccountDashboard, Issues, IssueRegisterView, IssueDetailView, IssueAnalytics,
  MyIssueActions, PendingDecisions, IssueScaleConfig, IssueReportCreate, IssueReportEdit,
  IssueReportView, IssueReportsList, PPDView, PPDList, PIDView, WorkPackageView,
  CheckpointReportList, CheckpointReportCreate, CheckpointReportView, CheckpointReportEdit,
  ClosingProject, EndProjectReportView, EndProjectReportWizard, EPRComparisonView, StageBoundaries,
  EndStageReportView, EndStageReportCreate, EndStageReportEdit, ExceptionReportList,
  ExceptionReportCreate, ExceptionReportEdit, ExceptionReportView, ExceptionReportDashboard,
  HighlightReportCreate, HighlightReportView, HighlightReportEdit, AcceptanceTestingPage, QMSView,
  QMSList, QMSTemplates, RMSView, RMSList, CMSView, CMSCreate, CMSEdit, CMSList, CMSTemplates,
  CommunicationActivitiesCalendar, ConfigurationMSView, ConfigurationMSCreate, ConfigurationMSEdit,
  ConfigurationMSList, ConfigurationItemRegister, ConfigurationItemRecordView,
  ConfigurationItemRecordCreate, ConfigurationItemRecordEdit, Risks, RiskDetail, RAIDLog,
  ProductBacklog, SprintPlanning, SprintBoard, DailyScrum, SprintReview, SprintRetrospective,
  SprintMetricsDashboard, AgileTemplates, StoryMap, AgileReleases, AgileReleaseDetail, AgileRoadmap,
  ScrumOfScrums, XPDashboard, ValueStreamMap, KaizenBoard, LeanMetrics, AgileMetricsHub,
  KanbanBoards, KanbanBoard, MetricsDashboard, Resources, ResourceCapacity, ResourceDetail,
  ResourceConflicts, ReportBuilder, AnalyticsDashboard, Benefits, BenefitsRegisterPage,
  BenefitsRealizationPage, BenefitMeasurementsPage, BenefitCreatePage, BenefitDetailPage,
  BenefitsReviewPlan, Dependencies, DependencyCreatePage, DependencyMap, DependencyImpacts,
  BenefitsRealization, DependenciesLegacy, IntegrationSync, Login, PlatformLogin, SimulatorLogin,
  Register, PlatformRegister, SimulatorRegister, EmailConfirmation, InvitationAccept, RoleSelection,
  PlatformAccountSetup, PlatformChoice, OrganisationSetup, OrganisationVerificationNotice,
  VerifyOrganisation, ProjectTypeSelection, TrialProjectSetup, PaidProjectSetup, FreeTrialDashboard,
  TrialUpgrade, RoleAssignment, ManageRoles, OrgRoleDetail, ManageMenuBundles, MenuBundleDetail, SystemRoleCatalog, SystemRoleEditPage, AssignRolesToProjects, SendRoleInvites, InvitationExpirySettingsPage,
  EmailSettings, EmailSenderProfiles, ChangeLogPage, WorkAuthorisationListPage,
  WorkAuthorisationDraftsPage, WorkAuthorisationCreatePage, WorkAuthorisationDetailPage,
  TestingCentreRoutesPlatform, TestingCentreRoutesPm, TestingCentreRoutesPmo, TestingCentreRoutesSim,
  TestingCentreRoutesSimPm, TestingCentreRoutesSimPmo, ProcessTemplatesRoutesPmo,
  ProcessTemplatesRoutesPm, ProcessTemplatesRoutesSimPmo, ProcessTemplatesRoutesSimPm, FormsGallery,
  ProjectFieldTemplates,
  FormNew, FormEdit, FormView, FormTemplateAdmin, FormTemplateBuilder, ProjectMemberInvitation, Settings, PWASettings,
  PWAInstallPrompt, BusinessCaseListPage, BusinessCaseCreate, BusinessCaseViewPage, BusinessCaseEdit,
  ProjectMandateCreate, ProjectMandateView, ProjectMandateEdit, MandateList, UnlinkedMandatesList,
  ProjectCreationWizard, MandateApprovalDashboard, SimMandateCreate, SimMandateView, SimMandateEdit,
  SimMandateList, SimScopeManagementPlanPage, SimScopeStatementPage, SimRequirementsRegisterPage,
  SimRequirementDetailPage, SimTraceabilityMatrixPage, SimWBSBuilderPage,
  SimScheduleManagementPlanPage, SimActivityListPage, SimActivityDetailPage,
  SimActivitySequencingPage, SimGanttChartPage, PracticeProjects, SimProjectMembers, ProjectUsers,
  InvitationTemplatesPage, PracticeProjectCreate, PracticeProjectDetail, PracticeTasks,
  PracticeTaskDetail, PracticeBriefList, PracticeBriefCreate, PracticeBriefView, PracticeBriefEdit,
  PracticeBusinessCaseList, PracticeBusinessCaseCreate, PracticeBusinessCaseView,
  PracticeBusinessCaseEdit, PracticePIDList, PracticePIDCreate, PracticePIDView,
  PracticeBenefitsReviewPlan, PracticeBenefitsReviewPlanList, PracticeBenefitsReviewPlanViewPage,
  PracticeBenefitsReviewPlanEditPage, PracticeWorkPackageList, PracticeWorkPackageCreate,
  PracticeWorkPackageView, PracticeWorkPackageEdit, PracticeProductDescriptionList,
  PracticeProductDescriptionCreate, PracticeProductDescriptionView, PracticePPDList, PracticePPDView,
  PracticePSAList, PracticePSAView, PracticePlanList, PracticePlanCreate, PracticePlanView,
  PracticePlanEdit, SimPlansDashboard, SimProjectPlanView, SimProjectPlanCreate, SimStagePlanCreate,
  PracticeDailyLog, PracticeDailyLogEntry, PracticeRiskRegister, PracticeRiskDetail, PracticeRMSList,
  PracticeRMSCreate, PracticeRMSView, PracticeIssueRegister, PracticeIssueDetail,
  PracticeIssueReportList, PracticeIssueReportCreate, PracticeIssueReportView,
  PracticeQualityRegister, PracticeQualityActivityView, PracticeQualityReviews,
  PracticeQualityInspections, PracticeQualityReports, PracticeQMSList, PracticeQMSCreate,
  PracticeQMSView, PracticeLessonsLog, PracticeLessonDetail, PracticeConfigItemList,
  PracticeConfigItemCreate, PracticeConfigItemView, PracticeCMSList, PracticeCMSCreate,
  PracticeCMSView, PracticeCMSEdit, PracticeConfigMSList, PracticeConfigMSCreate,
  PracticeConfigMSView, PracticeConfigMSEdit, PracticeCheckpointReportList,
  PracticeCheckpointReportCreate, PracticeCheckpointReportView, PracticeHighlightReportList,
  PracticeHighlightReportCreate, PracticeHighlightReportView, PracticeExceptionReportList,
  PracticeExceptionReportCreate, PracticeExceptionReportView, PracticeEndStageReportList,
  PracticeEndStageReportCreate, PracticeEndStageReportView, PracticeEndProjectReportList,
  PracticeEndProjectReportCreate, PracticeEndProjectReportView, PracticeLessonsReportList,
  PracticeLessonsReportCreate, PracticeLessonsReportView, PracticeStartingUp, PracticeInitiating,
  PracticeControllingStage, PracticeManagingDelivery, PracticeStageBoundaries,
  PracticeClosingProject, PracticePortfolio, PracticePortfolioCreate, PracticeProgramme,
  PracticeProgrammeDashboardOverview, PracticeProgrammeProjectsPage,
  PracticeProgrammeDependenciesPage, PracticeProgrammeBenefitsPage, PracticeProgrammeTimelinePage,
  PracticeBenefitsAll, PracticeBenefitsRegister, PracticeBenefitsMeasurements,
  PracticeBenefitsRealization, PracticeBenefitsRedirectPage, PracticeProgrammeCreate,
  PracticeProgrammeDetail, PracticeDependencies, PracticeStakeholders,
  PracticeStakeholderRegisterPage, PracticeStakeholderAnalysis, PracticeEngagementPlanning,
  PracticeCommunicationPlans, PracticeStakeholderMonitoring, PracticeStakeholderSEAM,
  PracticeStakeholderAssessmentMatrixPage, PracticeStakeholdersAssessmentMatrixOnHold,
  PracticeEngagementActionsPage, PracticeSaliencePage, PracticeStakeholdersOnHold,
  PracticeStakeholderCreatePage, PracticeTeams, SimMyTeam, PracticeGovernance,
  SimPortfolioCategories, SimPortfolioDashboard, SimPortfolioProjects, SimPortfolioResources,
  SimPortfolioFinancial, SimPortfolioReports, SimPortfolioGovernance, SimulatorPMODashboard,
  SimManagerAssignments, SimPortfolioManagerAssignments, SimProgrammeManagerAssignments,
  SimManagerAssignmentSettings, SimulatorPMDashboard, SimulatorPMOLayout,
  SimulatorPMOInvitationTracker, SimulatorPMLayout, SimulatorTMLayout, SimulatorTMDashboard,
  SimVoiceCallsPage, SimulatorPMInvitationTracker, SimulatorPMOGovernanceMandateTemplate,
  SimulatorPMOGovernanceCMS, SimulatorPMOGovernanceConfigMS, SimulatorPMOGovernanceQMS,
  SimulatorPMOGovernanceRMS, SimulatorPMOInitiationBusinessCase, SimulatorPMOInitiationProjectBrief,
  SimulatorPMOInitiationBenefitsReviewPlan, SimulatorPMOOversightRiskRegister,
  SimulatorPMOOversightIssueRegister, SimulatorPMOOversightQualityRegister,
  SimulatorPMOOversightLessonsLog, SimulatorPMOReportingHighlight, SimulatorPMOReportingException,
  SimulatorPMOReportingEndStage, SimulatorPMOReportingEndProject, SimulatorPMOProcurementRFP,
  SimulatorPMORFPView, SimulatorPMORFPCreate, SimulatorPMORFPEdit, SimulatorPMORFPBulkImport,
  SimulatorPMORFPPrint, SimulatorPMORFPOnHold, SimulatorPMGovernanceMandateTemplate,
  SimulatorPMGovernanceCMS, SimulatorPMGovernanceConfigMS, SimulatorPMGovernanceQMS,
  SimulatorPMGovernanceRMS, SimulatorPMInitiationBusinessCase, SimulatorPMInitiationProjectBrief,
  SimulatorPMInitiationPID, SimulatorPMInitiationBenefitsReviewPlan, SimulatorPMDeliveryWorkPackages,
  SimulatorPMDeliveryProductDescription, SimulatorPMDeliveryProjectProductDescription,
  SimulatorPMDeliveryProductStatusAccount, SimulatorPMDeliveryDailyLog,
  SimulatorPMControlsRiskRegister, SimulatorPMControlsIssueRegister,
  SimulatorPMControlsQualityRegister, SimulatorPMControlsConfigItems, SimulatorPMControlsLessonsLog,
  SimulatorPMControlsWorkAuthorisation, SimulatorPMReportingCheckpoint,
  SimulatorPMReportingHighlight, SimulatorPMReportingIssueReports, SimulatorPMReportingException,
  SimulatorPMReportingEndStage, SimulatorPMClosureLessonsReport, SimulatorPMClosureEndProjectReport,
  ProjectBriefCreate, ProjectBriefView, ProjectBriefEdit, BriefList, BriefApprovalDashboard,
  DailyLogView, MyDailyLogEntries, LessonsLogView, LessonDetailView, LessonFormPage, CorporateLessonsLibrary,
  MyLessonActions, LessonsReport, LessonsReportCreate, LessonsReportEdit, LessonsReportView,
  LessonsReportsList, RiskRegisterView
} = LP

export {
  LoadingFallbackWithTimeout,
  LoadingFallback,
  LoginPageSkeleton,
  RedirectProjectsTemplatesToLibrary,
  NidusHomepage,
  ThemeProvider,
  ToastProvider,
  Layout,
  ProtectedRoute,
  Home,
  PlatformHomepage,
  SimulatorHomepage,
  Documentation,
  FeaturesPage,
  BlogPage,
  ResourcesPage,
  PricingPage,
  PlatformPricing,
  BundlePricing,
  SimulatorPricing,
  AboutPage,
  ContactPage,
  PlatformRequestDemoPage,
  PlatformAffiliatePage,
  SimulatorRequestDemoPage,
  SimulatorAffiliatePage,
  Projects,
  ProjectsCreate,
  ProjectsDetail,
  LocalDataExtensionsRoutes,
  SimulatorLocalDataExtensionsRoutes,
  ProjectsEdit,
  ScopeManagementPlanPage,
  ScopeStatementPage,
  RequirementsRegisterPage,
  RequirementDetailPage,
  TraceabilityMatrixPage,
  WBSBuilderPage,
  ScheduleManagementPlanPage,
  ActivityListPage,
  ActivityDetailPage,
  ActivitySequencingPage,
  GanttChartPage,
  ProjectsOnHold,
  BenefitsOnHold,
  StakeholdersOnHold,
  IssuesOnHold,
  RisksOnHold,
  QualityOnHold,
  DraftExpiryConfig,
  Tasks,
  TasksBoard,
  TasksCalendar,
  TasksCreate,
  TasksDetail,
  MethodologySelection,
  PlatformDashboard,
  SimulatorDashboard,
  SimulationSetup,
  SimulationRunDashboard,
  SimEventInbox,
  SimStageGateReview,
  SimExceptionReportFlow,
  SimEVMDashboard,
  SimulationRunHistory,
  SimulationDebrief,
  SimLiveRunRedirect,
  SimAIWorkspace,
  AIWorkspace,
  SubmitFeedback,
  PMODashboard,
  PMDashboard,
  PMOLayout,
  PMLayout,
  PMOGovernanceMandateTemplate,
  PMOGovernanceCMS,
  PMOGovernanceConfigMS,
  PMOGovernanceQMS,
  PMOGovernanceRMS,
  PMOInitiationBusinessCase,
  PMOInitiationProjectBrief,
  PMOInitiationBenefitsReviewPlan,
  PMOOversightRiskRegister,
  PMOOversightIssueRegister,
  PMOOversightQualityRegister,
  PMOOversightChangeRegister,
  PMOOversightLessonsLog,
  PMOOversightScope,
  PMOOversightSchedules,
  PMOReportingHighlight,
  PMOReportingException,
  PMOReportingEndStage,
  PMOReportingEndProject,
  PMOProcurementRFP,
  PMORFPView,
  PMORFPCreate,
  PMORFPEdit,
  PMORFPBulkImport,
  PMORFPPrint,
  PMORFPOnHold,
  PMGovernanceMandateTemplate,
  PMGovernanceCMS,
  PMGovernanceConfigMS,
  PMGovernanceQMS,
  PMGovernanceRMS,
  PMInitiationBusinessCase,
  PMInitiationProjectBrief,
  PMInitiationPID,
  PMInitiationBenefitsReviewPlan,
  PMDeliveryWorkPackages,
  PMDeliveryProductDescription,
  PMDeliveryProjectProductDescription,
  PMDeliveryProductStatusAccount,
  PMDeliveryDailyLog,
  PMControlsRiskRegister,
  PMControlsIssueRegister,
  PMControlsQualityRegister,
  PMControlsConfigItems,
  PMControlsLessonsLog,
  PMReportingCheckpoint,
  PMReportingHighlight,
  PMReportingIssueReports,
  PMReportingException,
  PMReportingEndStage,
  PMClosureLessonsReport,
  PMClosureEndProjectReport,
  Dashboard,
  Teams,
  MyTeam,
  Governance,
  Portfolio,
  PortfolioCreatePage,
  PortfolioFormPage,
  PortfolioDashboard,
  PortfolioProjects,
  PortfolioResources,
  PortfolioFinancial,
  PortfolioReports,
  PortfolioGovernance,
  PortfolioCategories,
  Programme,
  ProgrammeDetailPage,
  ProgrammeCreatePage,
  ProgrammeEditPage,
  ProgrammeDashboardOverview,
  ProgrammeProjectsPage,
  ProgrammeDependenciesPage,
  ProgrammeBenefitsPage,
  ProgrammeTimelinePage,
  ProgrammeReportsPage,
  Strategy,
  StrategicObjectives,
  StrategicAlignment,
  StrategicContribution,
  StrategicPortfolio,
  StrategicReports,
  Quality,
  QualityManagement,
  QualityReviews,
  QualityInspections,
  QualityReports,
  QualityActivityView,
  MyQualityActions,
  Stakeholders,
  StakeholderRegisterPage,
  StakeholderFormPage,
  StakeholderProfilePage,
  StakeholderAnalysisPage,
  StakeholderEngagementPage,
  CommunicationPlanPage,
  StakeholderMonitoringPage,
  StakeholderAssessmentMatrixPage,
  StakeholdersAssessmentMatrixOnHold,
  TestDashboard,
  TestSuites,
  TestSuiteDetail,
  TestCases,
  TestCaseCreate,
  TestCaseDetail,
  TestCaseBulkUpload,
  TestRuns,
  TestRunDetail,
  TestRunExecute,
  DefectListPage,
  DefectDetailPage,
  DefectDashboardPage,
  SimTestDashboard,
  SimTestSuites,
  SimTestSuiteDetail,
  SimTestCases,
  SimTestCaseCreate,
  SimTestCaseDetail,
  SimTestCaseBulkUpload,
  SimTestRuns,
  SimTestRunDetail,
  SimTestRunExecute,
  SimDefectListPage,
  SimDefectDetailPage,
  SimDefectDashboardPage,
  BrandingSettings,
  BrandingHistory,
  PMOAdmin,
  PmoAdminUserManagement,
  ProjectTypes,
  ProjectStatuses,
  FundingSources,
  BudgetCategories,
  ManagerAssignments,
  AppointmentDashboard,
  MyAppointments,
  TeamAppointmentDashboard,
  MyTeamAppointments,
  SimAppointmentDashboard,
  SimMyAppointments,
  SimTeamAppointmentDashboard,
  SimMyTeamAppointments,
  PortfolioManagerAssignments,
  ProgrammeManagerAssignments,
  ManagerAssignmentSettings,
  PMORoleMenuManagement,
  AdminRoleMenuManagement,
  AuthenticationSettings,
  SecuritySettings,
  PWASettingsV675,
  ExecutiveDashboard,
  SubscriptionManagement,
  OrganisationProfile,
  StageGateList,
  StageGateForm,
  StageGateView,
  GovernanceFrameworkList,
  GovernanceFrameworkForm,
  PoliciesComplianceList,
  PoliciesComplianceForm,
  PoliciesComplianceView,
  IntelligenceRulesPage,
  GovernanceRulesConfigPage,
  CustomMetricsPage,
  WorkstreamPlanList,
  WorkstreamPlanForm,
  LeaderboardAdmin,
  CertificateAdmin,
  ScenarioAdmin,
  SimUserManagement,
  DocumentationAdminList,
  DocumentationAdminEditor,
  ProjectCostManagement,
  ProjectBudgetBaseline,
  ProjectEVMPage,
  ProjectsEVMLandingPage,
  ProgrammeEVMPage,
  ProgrammeEVMLandingPage,
  PortfolioEVMPage,
  ProgrammeFinancialDashboard,
  ProjectProfitability,
  MyExpenses,
  ExpenseApproval,
  ExpenseApprovalThresholds,
  FinancialReportingHub,
  SimProjectCostManagement,
  SimProjectBudgetBaseline,
  SimProjectEVMPage,
  SimProgrammeEVMPage,
  SimPortfolioEVMPage,
  SimProgrammeFinancialDashboard,
  SimProjectProfitability,
  SimMyExpenses,
  SimExpenseApproval,
  SimExpenseApprovalThresholds,
  SimFinancialReportingHub,
  SimSprintMetricsDashboard,
  SimAgileTemplates,
  SimStoryMap,
  SimAgileReleases,
  SimAgileReleaseDetail,
  SimAgileRoadmap,
  SimXPDashboard,
  SimValueStreamMap,
  SimKaizenBoard,
  SimLeanMetrics,
  SimScrumOfScrums,
  SimAgileMetricsHub,
  SimKanbanMetrics,
  LifecycleTemplates,
  Reports,
  OrgKnowledgeHub,
  EEFList,
  EEFCreate,
  EEFDetail,
  EEFEdit,
  EEFOnHold,
  EEFBulkUpload,
  ITTOTemplateList,
  ProjectITTOList,
  ITTODraftsQueue,
  IndustryTemplateList,
  LegacyTemplateUploadPage,
  LegacyReferenceTemplatesPage,
  PMOInvitationTracker,
  PMInvitationTracker,
  InvitationDetailPage,
  IndustryTemplateForm,
  IndustryTemplateDetail,
  IndustryTemplateOnHold,
  IndustryTemplateBrowser,
  IndustryPlanCopyWizard,
  ProjectIndustryPlanView,
  SimIndustryTemplateBrowser,
  SimIndustryPlanCopy,
  SimPracticeIndustryPlan,
  SimITTOTemplateList,
  SimProjectITTOList,
  SimITTODraftsQueue,
  DelayRegister,
  DelayTemplates,
  SimDelayRegister,
  SimDelayTemplates,
  PlanningHub,
  PlanningIntelligenceDashboard,
  ScenarioList,
  PBSBuilder,
  PlanHealthDashboard,
  AIPlanGenerator,
  ExecutivePlanView,
  PortfolioCollisionDashboard,
  RecoveryPlanningView,
  ConfidenceForecastView,
  GovernanceGateChecklist,
  MicroPlanList,
  MicroPlanDetail,
  MicroPlanDraftQueue,
  MicroPlanForm,
  TeamCharterPage,
  TeamCharterEditPage,
  DecisionLogPage,
  DecisionLogForm,
  DecisionLogDetail,
  MyTimesheetsPage,
  TimesheetEntryForm,
  TimesheetEntryDetail,
  TeamTimesheetsPage,
  TeamChatPage,
  VideoCallsPage,
  VoiceCallsPage,
  OPAList,
  OPACreate,
  OPADetail,
  OPAEdit,
  OPAOnHold,
  OPABulkUpload,
  SimEEFList,
  SimEEFCreate,
  SimEEFDetail,
  SimEEFEdit,
  SimEEFOnHold,
  SimEEFBulkUpload,
  SimOPAList,
  SimOPACreate,
  SimOPADetail,
  SimOPAEdit,
  SimOPAOnHold,
  SimOPABulkUpload,
  TemplateLibraryList,
  TemplateLibraryManage,
  PmOrganisationalTemplatesPage,
  PmOrganisationalTemplateDetailPage,
  ProjectTemplatesEntry,
  OrganisationalTemplatesEntry,
  ProjectDocumentsEntry,
  DocumentOversightPortfolioPage,
  DocumentOversightProgrammePage,
  DocumentOversightPmoPage,
  TemplateCreate,
  TemplateEdit,
  TemplateDetail,
  TemplateMasterVersionHistory,
  TemplateCategories,
  TemplateBulkUpload,
  TemplateUpdateNotifications,
  ProjectTemplateCopyList,
  ProjectTemplateCopyCreate,
  ProjectTemplateCopyEdit,
  ProjectTemplateCopyDetail,
  ProjectTemplateCopyVersionHistory,
  ProjectOPATemplates,
  ProjectOPACopy,
  ProjectOPACustomisationDetail,
  TemplateOnHold,
  SimTemplateLibraryList,
  SimTemplateLibraryManage,
  SimTemplateCreate,
  SimTemplateEdit,
  SimTemplateDetail,
  SimTemplateMasterVersionHistory,
  SimTemplateCategories,
  SimTemplateBulkUpload,
  SimTemplateUpdateNotifications,
  SimProjectTemplateCopyList,
  SimProjectTemplateCopyCreate,
  SimProjectTemplateCopyEdit,
  SimProjectTemplateCopyDetail,
  SimProjectTemplateCopyVersionHistory,
  SimTemplateOnHold,
  CommsHub,
  DirectMessages,
  ChannelView,
  MeetingList,
  MeetingSchedule,
  MeetingRoom,
  MeetingDetail,
  MeetingSummaryView,
  PendingAIReview,
  MeetingExtractionReview,
  ExtractedIssueEnrich,
  ExtractedRiskEnrich,
  DocumentGovernance,
  DocumentRegister,
  DocumentCompliance,
  ProgrammeDocuments,
  MethodologyDashboard,
  StartingUpProject,
  InitiatingProject,
  StageGates,
  ControllingStage,
  ManagingProductDelivery,
  DirectingProject,
  PlansDashboard,
  ProjectPlanCreate,
  ProjectPlanEdit,
  ProjectPlanViewPage,
  StagePlanCreate,
  StagePlanEdit,
  StagePlanViewPage,
  ProductDescriptionList,
  ProductDescriptionCreate,
  ProductDescriptionEdit,
  ProductDescriptionViewPage,
  ProductDescriptionTemplates,
  ProductStatusAccountList,
  ProductStatusAccountViewPage,
  ProductStatusAccountCreate,
  ProductStatusAccountEdit,
  ProductStatusAccountDashboard,
  Issues,
  IssueRegisterView,
  IssueDetailView,
  IssueAnalytics,
  MyIssueActions,
  PendingDecisions,
  IssueScaleConfig,
  IssueReportCreate,
  IssueReportEdit,
  IssueReportView,
  IssueReportsList,
  PPDView,
  PPDList,
  PIDView,
  WorkPackageView,
  CheckpointReportList,
  CheckpointReportCreate,
  CheckpointReportView,
  CheckpointReportEdit,
  ClosingProject,
  EndProjectReportView,
  EndProjectReportWizard,
  EPRComparisonView,
  StageBoundaries,
  EndStageReportView,
  EndStageReportCreate,
  EndStageReportEdit,
  ExceptionReportList,
  ExceptionReportCreate,
  ExceptionReportEdit,
  ExceptionReportView,
  ExceptionReportDashboard,
  HighlightReportCreate,
  HighlightReportView,
  HighlightReportEdit,
  AcceptanceTestingPage,
  QMSView,
  QMSList,
  QMSTemplates,
  RMSView,
  RMSList,
  CMSView,
  CMSCreate,
  CMSEdit,
  CMSList,
  CMSTemplates,
  CommunicationActivitiesCalendar,
  ConfigurationMSView,
  ConfigurationMSCreate,
  ConfigurationMSEdit,
  ConfigurationMSList,
  ConfigurationItemRegister,
  ConfigurationItemRecordView,
  ConfigurationItemRecordCreate,
  ConfigurationItemRecordEdit,
  Risks,
  RiskDetail,
  RAIDLog,
  ProductBacklog,
  SprintPlanning,
  SprintBoard,
  DailyScrum,
  SprintReview,
  SprintRetrospective,
  SprintMetricsDashboard,
  AgileTemplates,
  StoryMap,
  AgileReleases,
  AgileReleaseDetail,
  AgileRoadmap,
  ScrumOfScrums,
  XPDashboard,
  ValueStreamMap,
  KaizenBoard,
  LeanMetrics,
  AgileMetricsHub,
  KanbanBoards,
  KanbanBoard,
  MetricsDashboard,
  Resources,
  ResourceCapacity,
  ResourceDetail,
  ResourceConflicts,
  ReportBuilder,
  AnalyticsDashboard,
  Benefits,
  BenefitsRegisterPage,
  BenefitsRealizationPage,
  BenefitMeasurementsPage,
  BenefitCreatePage,
  BenefitDetailPage,
  BenefitsReviewPlan,
  Dependencies,
  DependencyCreatePage,
  DependencyMap,
  DependencyImpacts,
  BenefitsRealization,
  DependenciesLegacy,
  IntegrationSync,
  Login,
  PlatformLogin,
  SimulatorLogin,
  Register,
  PlatformRegister,
  SimulatorRegister,
  EmailConfirmation,
  InvitationAccept,
  RoleSelection,
  PlatformAccountSetup,
  PlatformChoice,
  OrganisationSetup,
  OrganisationVerificationNotice,
  VerifyOrganisation,
  ProjectTypeSelection,
  TrialProjectSetup,
  PaidProjectSetup,
  FreeTrialDashboard,
  TrialUpgrade,
  RoleAssignment,
  ManageRoles,
  OrgRoleDetail,
  ManageMenuBundles,
  MenuBundleDetail,
  SystemRoleCatalog,
  SystemRoleEditPage,
  AssignRolesToProjects,
  SendRoleInvites,
  InvitationExpirySettingsPage,
  EmailSettings,
  EmailSenderProfiles,
  ChangeLogPage,
  WorkAuthorisationListPage,
  WorkAuthorisationDraftsPage,
  WorkAuthorisationCreatePage,
  WorkAuthorisationDetailPage,
  TestingCentreRoutesPlatform,
  TestingCentreRoutesPm,
  TestingCentreRoutesPmo,
  TestingCentreRoutesSim,
  TestingCentreRoutesSimPm,
  TestingCentreRoutesSimPmo,
  ProcessTemplatesRoutesPmo,
  ProcessTemplatesRoutesPm,
  ProcessTemplatesRoutesSimPmo,
  ProcessTemplatesRoutesSimPm,
  FormsGallery,
  ProjectFieldTemplates,
  FormNew,
  FormEdit,
  FormView,
  FormTemplateAdmin,
  FormTemplateBuilder,
  ProjectMemberInvitation,
  Settings,
  PWASettings,
  PWAInstallPrompt,
  BusinessCaseListPage,
  BusinessCaseCreate,
  BusinessCaseViewPage,
  BusinessCaseEdit,
  ProjectMandateCreate,
  ProjectMandateView,
  ProjectMandateEdit,
  MandateList,
  UnlinkedMandatesList,
  ProjectCreationWizard,
  MandateApprovalDashboard,
  SimMandateCreate,
  SimMandateView,
  SimMandateEdit,
  SimMandateList,
  SimScopeManagementPlanPage,
  SimScopeStatementPage,
  SimRequirementsRegisterPage,
  SimRequirementDetailPage,
  SimTraceabilityMatrixPage,
  SimWBSBuilderPage,
  SimScheduleManagementPlanPage,
  SimActivityListPage,
  SimActivityDetailPage,
  SimActivitySequencingPage,
  SimGanttChartPage,
  PracticeProjects,
  SimProjectMembers,
  ProjectUsers,
  InvitationTemplatesPage,
  PracticeProjectCreate,
  PracticeProjectDetail,
  PracticeTasks,
  PracticeTaskDetail,
  PracticeBriefList,
  PracticeBriefCreate,
  PracticeBriefView,
  PracticeBriefEdit,
  PracticeBusinessCaseList,
  PracticeBusinessCaseCreate,
  PracticeBusinessCaseView,
  PracticeBusinessCaseEdit,
  PracticePIDList,
  PracticePIDCreate,
  PracticePIDView,
  PracticeBenefitsReviewPlan,
  PracticeBenefitsReviewPlanList,
  PracticeBenefitsReviewPlanViewPage,
  PracticeBenefitsReviewPlanEditPage,
  PracticeWorkPackageList,
  PracticeWorkPackageCreate,
  PracticeWorkPackageView,
  PracticeWorkPackageEdit,
  PracticeProductDescriptionList,
  PracticeProductDescriptionCreate,
  PracticeProductDescriptionView,
  PracticePPDList,
  PracticePPDView,
  PracticePSAList,
  PracticePSAView,
  PracticePlanList,
  PracticePlanCreate,
  PracticePlanView,
  PracticePlanEdit,
  SimPlansDashboard,
  SimProjectPlanView,
  SimProjectPlanCreate,
  SimStagePlanCreate,
  PracticeDailyLog,
  PracticeDailyLogEntry,
  PracticeRiskRegister,
  PracticeRiskDetail,
  PracticeRMSList,
  PracticeRMSCreate,
  PracticeRMSView,
  PracticeIssueRegister,
  PracticeIssueDetail,
  PracticeIssueReportList,
  PracticeIssueReportCreate,
  PracticeIssueReportView,
  PracticeQualityRegister,
  PracticeQualityActivityView,
  PracticeQualityReviews,
  PracticeQualityInspections,
  PracticeQualityReports,
  PracticeQMSList,
  PracticeQMSCreate,
  PracticeQMSView,
  PracticeLessonsLog,
  PracticeLessonDetail,
  PracticeConfigItemList,
  PracticeConfigItemCreate,
  PracticeConfigItemView,
  PracticeCMSList,
  PracticeCMSCreate,
  PracticeCMSView,
  PracticeCMSEdit,
  PracticeConfigMSList,
  PracticeConfigMSCreate,
  PracticeConfigMSView,
  PracticeConfigMSEdit,
  PracticeCheckpointReportList,
  PracticeCheckpointReportCreate,
  PracticeCheckpointReportView,
  PracticeHighlightReportList,
  PracticeHighlightReportCreate,
  PracticeHighlightReportView,
  PracticeExceptionReportList,
  PracticeExceptionReportCreate,
  PracticeExceptionReportView,
  PracticeEndStageReportList,
  PracticeEndStageReportCreate,
  PracticeEndStageReportView,
  PracticeEndProjectReportList,
  PracticeEndProjectReportCreate,
  PracticeEndProjectReportView,
  PracticeLessonsReportList,
  PracticeLessonsReportCreate,
  PracticeLessonsReportView,
  PracticeStartingUp,
  PracticeInitiating,
  PracticeControllingStage,
  PracticeManagingDelivery,
  PracticeStageBoundaries,
  PracticeClosingProject,
  PracticePortfolio,
  PracticePortfolioCreate,
  PracticeProgramme,
  PracticeProgrammeDashboardOverview,
  PracticeProgrammeProjectsPage,
  PracticeProgrammeDependenciesPage,
  PracticeProgrammeBenefitsPage,
  PracticeProgrammeTimelinePage,
  PracticeBenefitsAll,
  PracticeBenefitsRegister,
  PracticeBenefitsMeasurements,
  PracticeBenefitsRealization,
  PracticeBenefitsRedirectPage,
  PracticeProgrammeCreate,
  PracticeProgrammeDetail,
  PracticeDependencies,
  PracticeStakeholders,
  PracticeStakeholderRegisterPage,
  PracticeStakeholderAnalysis,
  PracticeEngagementPlanning,
  PracticeCommunicationPlans,
  PracticeStakeholderMonitoring,
  PracticeStakeholderSEAM,
  PracticeStakeholderAssessmentMatrixPage,
  PracticeStakeholdersAssessmentMatrixOnHold,
  PracticeEngagementActionsPage,
  PracticeSaliencePage,
  PracticeStakeholdersOnHold,
  PracticeStakeholderCreatePage,
  PracticeTeams,
  SimMyTeam,
  PracticeGovernance,
  SimPortfolioCategories,
  SimPortfolioDashboard,
  SimPortfolioProjects,
  SimPortfolioResources,
  SimPortfolioFinancial,
  SimPortfolioReports,
  SimPortfolioGovernance,
  SimulatorPMODashboard,
  SimManagerAssignments,
  SimPortfolioManagerAssignments,
  SimProgrammeManagerAssignments,
  SimManagerAssignmentSettings,
  SimulatorPMDashboard,
  SimulatorPMOLayout,
  SimulatorPMOInvitationTracker,
  SimulatorPMLayout,
  SimulatorTMLayout,
  SimulatorTMDashboard,
  SimVoiceCallsPage,
  SimulatorPMInvitationTracker,
  SimulatorPMOGovernanceMandateTemplate,
  SimulatorPMOGovernanceCMS,
  SimulatorPMOGovernanceConfigMS,
  SimulatorPMOGovernanceQMS,
  SimulatorPMOGovernanceRMS,
  SimulatorPMOInitiationBusinessCase,
  SimulatorPMOInitiationProjectBrief,
  SimulatorPMOInitiationBenefitsReviewPlan,
  SimulatorPMOOversightRiskRegister,
  SimulatorPMOOversightIssueRegister,
  SimulatorPMOOversightQualityRegister,
  SimulatorPMOOversightLessonsLog,
  SimulatorPMOReportingHighlight,
  SimulatorPMOReportingException,
  SimulatorPMOReportingEndStage,
  SimulatorPMOReportingEndProject,
  SimulatorPMOProcurementRFP,
  SimulatorPMORFPView,
  SimulatorPMORFPCreate,
  SimulatorPMORFPEdit,
  SimulatorPMORFPBulkImport,
  SimulatorPMORFPPrint,
  SimulatorPMORFPOnHold,
  SimulatorPMGovernanceMandateTemplate,
  SimulatorPMGovernanceCMS,
  SimulatorPMGovernanceConfigMS,
  SimulatorPMGovernanceQMS,
  SimulatorPMGovernanceRMS,
  SimulatorPMInitiationBusinessCase,
  SimulatorPMInitiationProjectBrief,
  SimulatorPMInitiationPID,
  SimulatorPMInitiationBenefitsReviewPlan,
  SimulatorPMDeliveryWorkPackages,
  SimulatorPMDeliveryProductDescription,
  SimulatorPMDeliveryProjectProductDescription,
  SimulatorPMDeliveryProductStatusAccount,
  SimulatorPMDeliveryDailyLog,
  SimulatorPMControlsRiskRegister,
  SimulatorPMControlsIssueRegister,
  SimulatorPMControlsQualityRegister,
  SimulatorPMControlsConfigItems,
  SimulatorPMControlsLessonsLog,
  SimulatorPMControlsWorkAuthorisation,
  SimulatorPMReportingCheckpoint,
  SimulatorPMReportingHighlight,
  SimulatorPMReportingIssueReports,
  SimulatorPMReportingException,
  SimulatorPMReportingEndStage,
  SimulatorPMClosureLessonsReport,
  SimulatorPMClosureEndProjectReport,
  ProjectBriefCreate,
  ProjectBriefView,
  ProjectBriefEdit,
  BriefList,
  BriefApprovalDashboard,
  DailyLogView,
  MyDailyLogEntries,
  LessonsLogView,
  LessonDetailView,
  LessonFormPage,
  CorporateLessonsLibrary,
  MyLessonActions,
  LessonsReport,
  LessonsReportCreate,
  LessonsReportEdit,
  LessonsReportView,
  LessonsReportsList,
  RiskRegisterView
}
