/**
 * Unified menu registry — build-time source of truth for sidebar items.
 * Runtime menus come from DB (menu_items + role_menu_items); this file seeds and validates them.
 *
 * @see projectplan/v638_Unified_Sidebar_Menu_Implementation_Plan.md
 * @see projectplan/v631_PMIS_Gap_Analysis_Implementation_Plan.md (pmisGapMenuRegistry.js)
 * @deprecated-runtime pmoMenuConfig.js, pmDashboardMenuConfig.js — registry only after v638
 */

import { PMIS_GAP_MENU_REGISTRY } from './pmisGapMenuRegistry.js'
import { RECORD_LIFECYCLE_MENU_REGISTRY } from './recordLifecycleMenuRegistry.js'

/** @typedef {'platform' | 'simulator'} MenuDomain */

/**
 * @typedef {Object} MenuRegistryEntry
 * @property {string} menu_code
 * @property {string} menu_label
 * @property {string|null} route_path
 * @property {string|null} parent_code
 * @property {string} menu_icon
 * @property {number} sort_order
 * @property {MenuDomain} domain
 * @property {string[]} roles
 * @property {string|null} [category] — PMO layout grouping hint (pmo-cat-*)
 * @property {boolean} [is_container]
 * @property {boolean} [registry_fallback] — inject via useMenu when missing from DB
 */

/** @type {MenuRegistryEntry[]} */
export const MENU_REGISTRY = [
  // ── Initiation & Business Justification (Platform PMO) ─────────────────────
  {
    menu_code: 'pmo_section_initiation',
    menu_label: 'Initiation & Business Justification',
    route_path: null,
    parent_code: null,
    menu_icon: 'briefcase',
    sort_order: 50,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-initiation',
    is_container: true,
  },
  {
    menu_code: 'pmo_init_business_case',
    menu_label: 'Business Case',
    route_path: '/pmo/initiation/business-case',
    parent_code: 'pmo_section_initiation',
    menu_icon: 'briefcase',
    sort_order: 1,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-initiation',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_init_project_brief',
    menu_label: 'Project Brief',
    route_path: '/pmo/initiation/project-brief',
    parent_code: 'pmo_section_initiation',
    menu_icon: 'file-text',
    sort_order: 2,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-initiation',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_init_benefits_review_plan',
    menu_label: 'Benefits Review Plan',
    route_path: '/pmo/initiation/benefits-review-plan',
    parent_code: 'pmo_section_initiation',
    menu_icon: 'book-open',
    sort_order: 3,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-initiation',
    registry_fallback: true,
  },

  // ── Governance & Standards (Platform PMO) ────────────────────────────────
  {
    menu_code: 'pmo_section_governance',
    menu_label: 'Governance & Standards',
    route_path: null,
    parent_code: null,
    menu_icon: 'shield',
    sort_order: 40,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    is_container: true,
  },
  {
    menu_code: 'pmo_gov_mandate',
    menu_label: 'Project Mandate',
    route_path: '/pmo/governance/mandate',
    parent_code: 'pmo_section_governance',
    menu_icon: 'file-text',
    sort_order: 1,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_gov_mandate_approval',
    menu_label: 'Approval / Authorisation',
    route_path: '/pmo/mandates/approvals',
    parent_code: 'pmo_section_governance',
    menu_icon: 'file-check',
    sort_order: 2,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_gov_communication_strategy',
    menu_label: 'Communication Management Strategy',
    route_path: '/pmo/governance/communication-strategy',
    parent_code: 'pmo_section_governance',
    menu_icon: 'megaphone',
    sort_order: 3,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_gov_configuration_strategy',
    menu_label: 'Configuration Management Strategy',
    route_path: '/pmo/governance/configuration-strategy',
    parent_code: 'pmo_section_governance',
    menu_icon: 'settings-2',
    sort_order: 4,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_gov_quality_strategy',
    menu_label: 'Quality Management Strategy',
    route_path: '/pmo/governance/quality-strategy',
    parent_code: 'pmo_section_governance',
    menu_icon: 'check-square',
    sort_order: 5,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_gov_risk_strategy',
    menu_label: 'Risk Management Strategy',
    route_path: '/pmo/governance/risk-strategy',
    parent_code: 'pmo_section_governance',
    menu_icon: 'alert-triangle',
    sort_order: 6,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_gov_itto_templates',
    menu_label: 'ITTO Templates',
    route_path: '/pmo/itto/templates',
    parent_code: 'pmo_section_governance',
    menu_icon: 'git-branch',
    sort_order: 7,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_gov_itto_drafts',
    menu_label: 'ITTO Drafts',
    route_path: '/pmo/itto/drafts',
    parent_code: 'pmo_section_governance',
    menu_icon: 'pause',
    sort_order: 8,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },

  // ── Project Oversight (Platform PMO) ───────────────────────────────────────
  {
    menu_code: 'pmo_section_oversight',
    menu_label: 'Project Oversight',
    route_path: null,
    parent_code: null,
    menu_icon: 'eye',
    sort_order: 55,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-project-oversight',
    is_container: true,
  },
  {
    menu_code: 'pmo_oversight_risk_register',
    menu_label: 'Risk Register',
    route_path: '/pmo/oversight/risk-register',
    parent_code: 'pmo_section_oversight',
    menu_icon: 'alert-triangle',
    sort_order: 1,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-project-oversight',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_oversight_issue_register',
    menu_label: 'Issue Register',
    route_path: '/pmo/oversight/issue-register',
    parent_code: 'pmo_section_oversight',
    menu_icon: 'alert-circle',
    sort_order: 2,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-project-oversight',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_oversight_quality_register',
    menu_label: 'Quality Register',
    route_path: '/pmo/oversight/quality-register',
    parent_code: 'pmo_section_oversight',
    menu_icon: 'clipboard-list',
    sort_order: 3,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-project-oversight',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_oversight_lessons_log',
    menu_label: 'Lessons Log',
    route_path: '/pmo/oversight/lessons-log',
    parent_code: 'pmo_section_oversight',
    menu_icon: 'graduation-cap',
    sort_order: 4,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-project-oversight',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_oversight_delays',
    menu_label: 'Delay Register',
    route_path: '/pmo/oversight/delays',
    parent_code: 'pmo_section_oversight',
    menu_icon: 'file-clock',
    sort_order: 5,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-project-oversight',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_oversight_delay_templates',
    menu_label: 'Delay Templates',
    route_path: '/pmo/delays/templates',
    parent_code: 'pmo_section_oversight',
    menu_icon: 'layers',
    sort_order: 6,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-project-oversight',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_oversight_scope',
    menu_label: 'Scope Oversight',
    route_path: '/pmo/oversight/scope',
    parent_code: 'pmo_section_oversight',
    menu_icon: 'clipboard-list',
    sort_order: 7,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-project-oversight',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_oversight_schedules',
    menu_label: 'Schedule Oversight',
    route_path: '/pmo/oversight/schedules',
    parent_code: 'pmo_section_oversight',
    menu_icon: 'file-clock',
    sort_order: 8,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-project-oversight',
    registry_fallback: true,
  },
  // Change Register (All) — route pending; see pmoMenuConfig pmo-oversight-changes

  // ── Process Templates (Platform PMO) — v629 codes preserved ────────────────
  {
    menu_code: 'pmo_process_templates_section',
    menu_label: 'Process Templates',
    route_path: null,
    parent_code: null,
    menu_icon: 'layers',
    sort_order: 75,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-process-templates',
    is_container: true,
  },
  {
    menu_code: 'pmo_pt_hub',
    menu_label: 'Hub Overview',
    route_path: '/pmo/process-templates',
    parent_code: 'pmo_process_templates_section',
    menu_icon: 'layers',
    sort_order: 1,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-process-templates',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_pt_pre',
    menu_label: 'Pre-Project',
    route_path: '/pmo/process-templates/pre-project',
    parent_code: 'pmo_process_templates_section',
    menu_icon: 'file-text',
    sort_order: 2,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-process-templates',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_pt_init',
    menu_label: 'Initiating',
    route_path: '/pmo/process-templates/initiating',
    parent_code: 'pmo_process_templates_section',
    menu_icon: 'play-circle',
    sort_order: 3,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-process-templates',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_pt_plan',
    menu_label: 'Planning',
    route_path: '/pmo/process-templates/planning',
    parent_code: 'pmo_process_templates_section',
    menu_icon: 'map',
    sort_order: 4,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-process-templates',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_pt_exec',
    menu_label: 'Executing',
    route_path: '/pmo/process-templates/executing',
    parent_code: 'pmo_process_templates_section',
    menu_icon: 'zap',
    sort_order: 5,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-process-templates',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_pt_mon',
    menu_label: 'Monitoring & Control',
    route_path: '/pmo/process-templates/monitoring-controlling',
    parent_code: 'pmo_process_templates_section',
    menu_icon: 'activity',
    sort_order: 6,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-process-templates',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_pt_close',
    menu_label: 'Closing',
    route_path: '/pmo/process-templates/closing',
    parent_code: 'pmo_process_templates_section',
    menu_icon: 'check-circle',
    sort_order: 7,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-process-templates',
    registry_fallback: true,
  },

  // ── Initiation (Platform PM dashboard) ─────────────────────────────────────
  {
    menu_code: 'pm_section_initiation',
    menu_label: 'Initiation & Business Justification',
    route_path: null,
    parent_code: null,
    menu_icon: 'briefcase',
    sort_order: 27,
    domain: 'platform',
    roles: ['project_manager'],
    category: null,
    is_container: true,
  },
  {
    menu_code: 'pm_init_business_case',
    menu_label: 'Business Case',
    route_path: '/pm/initiation/business-case',
    parent_code: 'pm_section_initiation',
    menu_icon: 'briefcase',
    sort_order: 1,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'pm_init_project_brief',
    menu_label: 'Project Brief',
    route_path: '/pm/initiation/project-brief',
    parent_code: 'pm_section_initiation',
    menu_icon: 'file-text',
    sort_order: 2,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'pm_init_pid',
    menu_label: 'Project Initiation Document (PID)',
    route_path: '/pm/initiation/pid',
    parent_code: 'pm_section_initiation',
    menu_icon: 'file-box',
    sort_order: 3,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'pm_init_benefits_review_plan',
    menu_label: 'Benefits Review Plan',
    route_path: '/pm/initiation/benefits-review-plan',
    parent_code: 'pm_section_initiation',
    menu_icon: 'book-open',
    sort_order: 4,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },

  // ── Simulator PMO: Initiation ───────────────────────────────────────────────
  {
    menu_code: 'sim_pmo_section_initiation',
    menu_label: 'Initiation & Business Justification',
    route_path: null,
    parent_code: null,
    menu_icon: 'briefcase',
    sort_order: 50,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    is_container: true,
  },
  {
    menu_code: 'sim_pmo_init_business_case',
    menu_label: 'Practice Business Case',
    route_path: '/simulator/pmo/initiation/business-case',
    parent_code: 'sim_pmo_section_initiation',
    menu_icon: 'briefcase',
    sort_order: 1,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_init_project_brief',
    menu_label: 'Practice Project Brief',
    route_path: '/simulator/pmo/initiation/project-brief',
    parent_code: 'sim_pmo_section_initiation',
    menu_icon: 'file-text',
    sort_order: 2,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_init_benefits_review_plan',
    menu_label: 'Practice Benefits Review Plan',
    route_path: '/simulator/pmo/initiation/benefits-review-plan',
    parent_code: 'sim_pmo_section_initiation',
    menu_icon: 'book-open',
    sort_order: 3,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },

  // ── Simulator PMO: Governance ─────────────────────────────────────────────
  {
    menu_code: 'sim_pmo_section_governance',
    menu_label: 'Governance & Standards',
    route_path: null,
    parent_code: null,
    menu_icon: 'shield',
    sort_order: 40,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    is_container: true,
  },
  {
    menu_code: 'sim_pmo_gov_mandate',
    menu_label: 'Practice Project Mandate',
    route_path: '/simulator/pmo/governance/mandate',
    parent_code: 'sim_pmo_section_governance',
    menu_icon: 'file-text',
    sort_order: 1,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_gov_communication_strategy',
    menu_label: 'Practice Communication Management Strategy',
    route_path: '/simulator/pmo/governance/communication-strategy',
    parent_code: 'sim_pmo_section_governance',
    menu_icon: 'megaphone',
    sort_order: 2,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_gov_configuration_strategy',
    menu_label: 'Practice Configuration Management Strategy',
    route_path: '/simulator/pmo/governance/configuration-strategy',
    parent_code: 'sim_pmo_section_governance',
    menu_icon: 'settings-2',
    sort_order: 3,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_gov_quality_strategy',
    menu_label: 'Practice Quality Management Strategy',
    route_path: '/simulator/pmo/governance/quality-strategy',
    parent_code: 'sim_pmo_section_governance',
    menu_icon: 'check-square',
    sort_order: 4,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_gov_risk_strategy',
    menu_label: 'Practice Risk Management Strategy',
    route_path: '/simulator/pmo/governance/risk-strategy',
    parent_code: 'sim_pmo_section_governance',
    menu_icon: 'alert-triangle',
    sort_order: 5,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_gov_itto_templates',
    menu_label: 'ITTO Templates',
    route_path: '/simulator/pmo/itto/templates',
    parent_code: 'sim_pmo_section_governance',
    menu_icon: 'git-branch',
    sort_order: 6,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_gov_itto_drafts',
    menu_label: 'ITTO Drafts',
    route_path: '/simulator/pmo/itto/drafts',
    parent_code: 'sim_pmo_section_governance',
    menu_icon: 'pause',
    sort_order: 7,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },

  // ── Simulator PMO: Oversight ────────────────────────────────────────────────
  {
    menu_code: 'sim_pmo_section_oversight',
    menu_label: 'Practice Project Oversight',
    route_path: null,
    parent_code: null,
    menu_icon: 'eye',
    sort_order: 55,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    is_container: true,
  },
  {
    menu_code: 'sim_pmo_oversight_risk_register',
    menu_label: 'Practice Risk Register',
    route_path: '/simulator/pmo/oversight/risk-register',
    parent_code: 'sim_pmo_section_oversight',
    menu_icon: 'alert-triangle',
    sort_order: 1,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_oversight_issue_register',
    menu_label: 'Practice Issue Register',
    route_path: '/simulator/pmo/oversight/issue-register',
    parent_code: 'sim_pmo_section_oversight',
    menu_icon: 'alert-circle',
    sort_order: 2,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_oversight_quality_register',
    menu_label: 'Practice Quality Register',
    route_path: '/simulator/pmo/oversight/quality-register',
    parent_code: 'sim_pmo_section_oversight',
    menu_icon: 'clipboard-list',
    sort_order: 3,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_oversight_lessons_log',
    menu_label: 'Practice Lessons Log',
    route_path: '/simulator/pmo/oversight/lessons-log',
    parent_code: 'sim_pmo_section_oversight',
    menu_icon: 'graduation-cap',
    sort_order: 4,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_oversight_delays',
    menu_label: 'Delay Register',
    route_path: '/simulator/pmo/oversight/delays',
    parent_code: 'sim_pmo_section_oversight',
    menu_icon: 'file-clock',
    sort_order: 5,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_oversight_delay_templates',
    menu_label: 'Delay Templates',
    route_path: '/simulator/pmo/delays/templates',
    parent_code: 'sim_pmo_section_oversight',
    menu_icon: 'layers',
    sort_order: 6,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_oversight_scope',
    menu_label: 'Scope Oversight',
    route_path: '/simulator/pmo/oversight/scope',
    parent_code: 'sim_pmo_section_oversight',
    menu_icon: 'clipboard-list',
    sort_order: 7,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_oversight_schedules',
    menu_label: 'Schedule Oversight',
    route_path: '/simulator/pmo/oversight/schedules',
    parent_code: 'sim_pmo_section_oversight',
    menu_icon: 'file-clock',
    sort_order: 8,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },

  // ── Simulator PMO: Process Templates (v635 codes) ─────────────────────────
  {
    menu_code: 'sim_pmo_process_templates_section',
    menu_label: 'Process Templates',
    route_path: null,
    parent_code: null,
    menu_icon: 'layers',
    sort_order: 75,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    is_container: true,
  },
  {
    menu_code: 'sim_pmo_pt_hub',
    menu_label: 'Hub Overview',
    route_path: '/simulator/pmo/process-templates',
    parent_code: 'sim_pmo_process_templates_section',
    menu_icon: 'layers',
    sort_order: 1,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_pt_pre',
    menu_label: 'Pre-Project',
    route_path: '/simulator/pmo/process-templates/pre-project',
    parent_code: 'sim_pmo_process_templates_section',
    menu_icon: 'file-text',
    sort_order: 2,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_pt_init',
    menu_label: 'Initiating',
    route_path: '/simulator/pmo/process-templates/initiating',
    parent_code: 'sim_pmo_process_templates_section',
    menu_icon: 'play-circle',
    sort_order: 3,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_pt_plan',
    menu_label: 'Planning',
    route_path: '/simulator/pmo/process-templates/planning',
    parent_code: 'sim_pmo_process_templates_section',
    menu_icon: 'map',
    sort_order: 4,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_pt_exec',
    menu_label: 'Executing',
    route_path: '/simulator/pmo/process-templates/executing',
    parent_code: 'sim_pmo_process_templates_section',
    menu_icon: 'zap',
    sort_order: 5,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_pt_mon',
    menu_label: 'Monitoring & Control',
    route_path: '/simulator/pmo/process-templates/monitoring-controlling',
    parent_code: 'sim_pmo_process_templates_section',
    menu_icon: 'activity',
    sort_order: 6,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_pt_close',
    menu_label: 'Closing',
    route_path: '/simulator/pmo/process-templates/closing',
    parent_code: 'sim_pmo_process_templates_section',
    menu_icon: 'check-circle',
    sort_order: 7,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },

  // ── Simulator PM: Initiation ────────────────────────────────────────────────
  {
    menu_code: 'sim_pm_section_initiation',
    menu_label: 'Initiation & Business Justification',
    route_path: null,
    parent_code: null,
    menu_icon: 'briefcase',
    sort_order: 27,
    domain: 'simulator',
    roles: ['project_manager'],
    is_container: true,
  },
  {
    menu_code: 'sim_pm_init_business_case',
    menu_label: 'Practice Business Case',
    route_path: '/simulator/pm/initiation/business-case',
    parent_code: 'sim_pm_section_initiation',
    menu_icon: 'briefcase',
    sort_order: 1,
    domain: 'simulator',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pm_init_project_brief',
    menu_label: 'Practice Project Brief',
    route_path: '/simulator/pm/initiation/project-brief',
    parent_code: 'sim_pm_section_initiation',
    menu_icon: 'file-text',
    sort_order: 2,
    domain: 'simulator',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pm_init_pid',
    menu_label: 'Practice Project Initiation Document (PID)',
    route_path: '/simulator/pm/initiation/pid',
    parent_code: 'sim_pm_section_initiation',
    menu_icon: 'file-text',
    sort_order: 3,
    domain: 'simulator',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pm_init_benefits_review_plan',
    menu_label: 'Practice Benefits Review Plan',
    route_path: '/simulator/pm/initiation/benefits-review-plan',
    parent_code: 'sim_pm_section_initiation',
    menu_icon: 'book-open',
    sort_order: 4,
    domain: 'simulator',
    roles: ['project_manager'],
    registry_fallback: true,
  },

  // ── Simulator PM: Process Templates (v635 codes) ────────────────────────────
  {
    menu_code: 'sim_pm_process_templates_section',
    menu_label: 'Process Templates',
    route_path: null,
    parent_code: null,
    menu_icon: 'layers',
    sort_order: 145,
    domain: 'simulator',
    roles: ['project_manager'],
    is_container: true,
  },
  {
    menu_code: 'sim_pm_pt_hub',
    menu_label: 'Hub Overview',
    route_path: '/simulator/pm/process-templates',
    parent_code: 'sim_pm_process_templates_section',
    menu_icon: 'layers',
    sort_order: 1,
    domain: 'simulator',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pm_pt_pre',
    menu_label: 'Pre-Project',
    route_path: '/simulator/pm/process-templates/pre-project',
    parent_code: 'sim_pm_process_templates_section',
    menu_icon: 'file-text',
    sort_order: 2,
    domain: 'simulator',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pm_pt_init',
    menu_label: 'Initiating',
    route_path: '/simulator/pm/process-templates/initiating',
    parent_code: 'sim_pm_process_templates_section',
    menu_icon: 'play-circle',
    sort_order: 3,
    domain: 'simulator',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pm_pt_plan',
    menu_label: 'Planning',
    route_path: '/simulator/pm/process-templates/planning',
    parent_code: 'sim_pm_process_templates_section',
    menu_icon: 'map',
    sort_order: 4,
    domain: 'simulator',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pm_pt_exec',
    menu_label: 'Executing',
    route_path: '/simulator/pm/process-templates/executing',
    parent_code: 'sim_pm_process_templates_section',
    menu_icon: 'zap',
    sort_order: 5,
    domain: 'simulator',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pm_pt_mon',
    menu_label: 'Monitoring & Control',
    route_path: '/simulator/pm/process-templates/monitoring-controlling',
    parent_code: 'sim_pm_process_templates_section',
    menu_icon: 'activity',
    sort_order: 6,
    domain: 'simulator',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pm_pt_close',
    menu_label: 'Closing',
    route_path: '/simulator/pm/process-templates/closing',
    parent_code: 'sim_pm_process_templates_section',
    menu_icon: 'check-circle',
    sort_order: 7,
    domain: 'simulator',
    roles: ['project_manager'],
    registry_fallback: true,
  },

  ...PMIS_GAP_MENU_REGISTRY,
  ...RECORD_LIFECYCLE_MENU_REGISTRY,
]

/**
 * @param {MenuDomain} [domain='platform']
 * @returns {MenuRegistryEntry[]}
 */
export function getMenuRegistryEntries(domain = 'platform') {
  return MENU_REGISTRY.filter((e) => e.domain === domain)
}

/**
 * Registry entries marked for client-side fallback when DB row is missing.
 * @param {MenuDomain} [domain='platform']
 * @returns {MenuRegistryEntry[]}
 */
export function getRegistryFallbackEntries(domain = 'platform') {
  return MENU_REGISTRY.filter((e) => e.domain === domain && e.registry_fallback && e.route_path)
}

/**
 * @param {string} categoryId
 * @param {MenuDomain} [domain='platform']
 * @returns {MenuRegistryEntry[]}
 */
export function getRegistryEntriesForCategory(categoryId, domain = 'platform') {
  return MENU_REGISTRY.filter(
    (e) => e.domain === domain && e.category === categoryId && e.route_path && !e.is_container
  )
}

/**
 * Unique menu_codes from registry (for SQL seed generation).
 * @returns {string[]}
 */
export function getRegistryMenuCodes() {
  return MENU_REGISTRY.map((e) => e.menu_code)
}

export default MENU_REGISTRY
