/**
 * Unified menu registry — build-time source of truth for sidebar items.
 * Runtime menus come from DB (menu_items + role_menu_items); this file seeds and validates them.
 *
 * @see projectplan/v638_Unified_Sidebar_Menu_Implementation_Plan.md
 * @see projectplan/v631_PMIS_Gap_Analysis_Implementation_Plan.md (pmisGapMenuRegistry.js)
 * @deprecated-runtime pmoMenuConfig.js, pmDashboardMenuConfig.js — registry only after v638
 */

import { PMIS_GAP_MENU_REGISTRY } from './pmisGapMenuRegistry.js'
import { RECORD_LIFECYCLE_MENU_REGISTRY } from './recordLifecycleMenuRegistry.js'
import { withRegistryMethodology } from './menuRegistryMethodology.js'

/** @typedef {'platform' | 'simulator'} MenuDomain */

/**
 * @typedef {Object} MenuRegistryEntry
 * @property {string} menu_code
 * @property {string} menu_label
 * @property {string|null} route_path
 * @property {string|null} parent_code
 * @property {string} menu_icon
 * @property {number} sort_order
 * @property {MenuDomain} domain
 * @property {string[]} roles
 * @property {string|null} [category] — PMO layout grouping hint (pmo-cat-*)
 * @property {boolean} [is_container]
 * @property {boolean} [registry_fallback] — catalogue/SQL seed hint only (not injected at runtime after v664)
 * @property {'structured'|'standards_based'|'agile'|'universal'} [methodology] — methodology track (v671)
 */

/** @type {MenuRegistryEntry[]} */
export const MENU_REGISTRY = [
  // ── Initiation & Business Justification (Platform PMO) ─────────────────────
  {
    menu_code: 'pmo_section_initiation',
    menu_label: 'Business Justification',
    route_path: null,
    parent_code: null,
    menu_icon: 'briefcase',
    sort_order: 50,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-initiation',
    is_container: true,
  },
  {
    menu_code: 'pmo_init_project_mandate',
    menu_label: 'Project Mandate',
    route_path: '/platform/mandates/list',
    parent_code: 'pmo_section_initiation',
    menu_icon: 'file-text',
    sort_order: 0,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin', 'project_executive', 'project_manager'],
    category: 'pmo-cat-initiation',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_init_business_case',
    menu_label: 'Business Case',
    route_path: '/pmo/initiation/business-case',
    parent_code: 'pmo_section_initiation',
    menu_icon: 'briefcase',
    sort_order: 1,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-initiation',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_init_project_brief',
    menu_label: 'Project Brief',
    route_path: '/pmo/initiation/project-brief',
    parent_code: 'pmo_section_initiation',
    menu_icon: 'file-text',
    sort_order: 2,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-initiation',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_init_benefits_review_plan',
    menu_label: 'Benefits Review Plan',
    route_path: '/pmo/initiation/benefits-review-plan',
    parent_code: 'pmo_section_initiation',
    menu_icon: 'book-open',
    sort_order: 3,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-initiation',
    registry_fallback: true,
  },

  // ── Governance & Standards (Platform PMO) ────────────────────────────────
  {
    menu_code: 'pmo_section_governance',
    menu_label: 'Governance & Standards',
    route_path: null,
    parent_code: null,
    menu_icon: 'shield',
    sort_order: 40,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    is_container: true,
  },
  {
    menu_code: 'pmo_gov_mandate_approval',
    menu_label: 'Approval / Authorisation',
    route_path: '/pmo/mandates/approvals',
    parent_code: 'pmo_section_governance',
    menu_icon: 'file-check',
    sort_order: 2,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_gov_communication_strategy',
    menu_label: 'Communication Management Strategy',
    route_path: '/pmo/governance/communication-strategy',
    parent_code: 'pmo_section_governance',
    menu_icon: 'megaphone',
    sort_order: 3,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_gov_configuration_strategy',
    menu_label: 'Configuration Management Strategy',
    route_path: '/pmo/governance/configuration-strategy',
    parent_code: 'pmo_section_governance',
    menu_icon: 'settings-2',
    sort_order: 4,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_gov_quality_strategy',
    menu_label: 'Quality Management Strategy',
    route_path: '/pmo/governance/quality-strategy',
    parent_code: 'pmo_section_governance',
    menu_icon: 'check-square',
    sort_order: 5,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_gov_risk_strategy',
    menu_label: 'Risk Management Strategy',
    route_path: '/pmo/governance/risk-strategy',
    parent_code: 'pmo_section_governance',
    menu_icon: 'alert-triangle',
    sort_order: 6,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_gov_itto_templates',
    menu_label: 'ITTO Templates',
    route_path: '/pmo/itto/templates',
    parent_code: 'pmo_section_governance',
    menu_icon: 'git-branch',
    sort_order: 7,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_gov_itto_drafts',
    menu_label: 'ITTO Drafts',
    route_path: '/pmo/itto/drafts',
    parent_code: 'pmo_section_governance',
    menu_icon: 'pause',
    sort_order: 8,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },

  // ── Project Oversight (Platform PMO) ───────────────────────────────────────
  {
    menu_code: 'pmo_section_oversight',
    menu_label: 'Project Oversight',
    route_path: null,
    parent_code: null,
    menu_icon: 'eye',
    sort_order: 55,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-project-oversight',
    is_container: true,
  },
  {
    menu_code: 'pmo_oversight_risk_register',
    menu_label: 'Risk Register',
    route_path: '/pmo/oversight/risk-register',
    parent_code: 'pmo_section_oversight',
    menu_icon: 'alert-triangle',
    sort_order: 1,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-project-oversight',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_oversight_issue_register',
    menu_label: 'Issue Register',
    route_path: '/pmo/oversight/issue-register',
    parent_code: 'pmo_section_oversight',
    menu_icon: 'alert-circle',
    sort_order: 2,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-project-oversight',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_oversight_quality_register',
    menu_label: 'Quality Register',
    route_path: '/pmo/oversight/quality-register',
    parent_code: 'pmo_section_oversight',
    menu_icon: 'clipboard-list',
    sort_order: 3,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-project-oversight',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_oversight_lessons_log',
    menu_label: 'Lessons Log',
    route_path: '/pmo/oversight/lessons-log',
    parent_code: 'pmo_section_oversight',
    menu_icon: 'graduation-cap',
    sort_order: 4,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-project-oversight',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_oversight_delays',
    menu_label: 'Delay Register',
    route_path: '/pmo/oversight/delays',
    parent_code: 'pmo_section_oversight',
    menu_icon: 'file-clock',
    sort_order: 5,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-project-oversight',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_oversight_scope',
    menu_label: 'Scope Oversight',
    route_path: '/pmo/oversight/scope',
    parent_code: 'pmo_section_oversight',
    menu_icon: 'clipboard-list',
    sort_order: 7,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-project-oversight',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_oversight_schedules',
    menu_label: 'Schedule Oversight',
    route_path: '/pmo/oversight/schedules',
    parent_code: 'pmo_section_oversight',
    menu_icon: 'file-clock',
    sort_order: 8,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-project-oversight',
    registry_fallback: true,
  },
  // Change Register (All) — route pending; see pmoMenuConfig pmo-oversight-changes

  // ── Process Templates (Platform PMO) — v629 codes preserved ────────────────
  {
    menu_code: 'pmo_process_templates_section',
    menu_label: 'Process Templates',
    route_path: null,
    parent_code: null,
    menu_icon: 'layers',
    sort_order: 75,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-knowledge-assets',
    is_container: true,
  },
  {
    menu_code: 'pmo_pt_hub',
    menu_label: 'Hub Overview',
    route_path: '/pmo/process-templates',
    parent_code: 'pmo_process_templates_section',
    menu_icon: 'layers',
    sort_order: 1,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-knowledge-assets',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_pt_pre',
    menu_label: 'Pre-Project',
    route_path: '/pmo/process-templates/pre-project',
    parent_code: 'pmo_process_templates_section',
    menu_icon: 'file-text',
    sort_order: 2,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-initiation',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_pt_init',
    menu_label: 'Initiating',
    route_path: '/pmo/process-templates/initiating',
    parent_code: 'pmo_process_templates_section',
    menu_icon: 'play-circle',
    sort_order: 3,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-process-templates',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_pt_plan',
    menu_label: 'Planning',
    route_path: '/pmo/process-templates/planning',
    parent_code: 'pmo_process_templates_section',
    menu_icon: 'map',
    sort_order: 4,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-process-templates',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_pt_exec',
    menu_label: 'Executing',
    route_path: '/pmo/process-templates/executing',
    parent_code: 'pmo_process_templates_section',
    menu_icon: 'zap',
    sort_order: 5,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-process-templates',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_pt_mon',
    menu_label: 'Monitoring & Control',
    route_path: '/pmo/process-templates/monitoring-controlling',
    parent_code: 'pmo_process_templates_section',
    menu_icon: 'activity',
    sort_order: 6,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-process-templates',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_pt_close',
    menu_label: 'Closing',
    route_path: '/pmo/process-templates/closing',
    parent_code: 'pmo_process_templates_section',
    menu_icon: 'check-circle',
    sort_order: 7,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-process-templates',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_oversight_delay_templates',
    menu_label: 'Delay Templates',
    route_path: '/pmo/delays/templates',
    parent_code: 'pmo_process_templates_section',
    menu_icon: 'layers',
    sort_order: 8,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-knowledge-assets',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_pt_browse',
    menu_label: 'Browse Templates',
    route_path: '/platform/templates',
    parent_code: 'pmo_process_templates_section',
    menu_icon: 'layers',
    sort_order: 8,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-knowledge-assets',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_pt_manage',
    menu_label: 'Manage Templates',
    route_path: '/platform/templates/manage',
    parent_code: 'pmo_process_templates_section',
    menu_icon: 'settings-2',
    sort_order: 9,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-knowledge-assets',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_pt_agile',
    menu_label: 'Agile Templates',
    route_path: '/platform/projects/:projectId/scrum/templates',
    parent_code: 'pmo_process_templates_section',
    menu_icon: 'activity',
    sort_order: 10,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-agile-lean',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_pt_new',
    menu_label: 'New Template',
    route_path: '/platform/templates/new',
    parent_code: 'pmo_process_templates_section',
    menu_icon: 'file-plus',
    sort_order: 11,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-knowledge-assets',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_gov_eef_list',
    menu_label: 'Environment Factors',
    route_path: '/platform/eef',
    parent_code: 'pmo_section_governance',
    menu_icon: 'package-open',
    sort_order: 9,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_gov_eef_new',
    menu_label: 'Add EEF',
    route_path: '/platform/eef/new',
    parent_code: 'pmo_section_governance',
    menu_icon: 'file-plus',
    sort_order: 10,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_gov_eef_drafts',
    menu_label: 'EEF Drafts',
    route_path: '/platform/eef/on-hold',
    parent_code: 'pmo_section_governance',
    menu_icon: 'pause',
    sort_order: 11,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_gov_opa_list',
    menu_label: 'Organisational Process Assets (OPA)',
    route_path: '/platform/opa',
    parent_code: 'pmo_section_governance',
    menu_icon: 'library',
    sort_order: 12,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_oversight_changes',
    menu_label: 'Change Register (All)',
    route_path: '/pmo/registers/changes',
    parent_code: 'pmo_section_oversight',
    menu_icon: 'refresh-ccw',
    sort_order: 9,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-project-oversight',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_section_reporting',
    menu_label: 'Reporting & Assurance',
    route_path: null,
    parent_code: null,
    menu_icon: 'bar-chart-3',
    sort_order: 90,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-reporting-intelligence',
    is_container: true,
  },
  {
    menu_code: 'pmo_report_lessons',
    menu_label: 'Lessons Report',
    route_path: '/pm/closure/lessons-report',
    parent_code: 'pmo_section_reporting',
    menu_icon: 'graduation-cap',
    sort_order: 5,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-reporting-intelligence',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_report_sprint_metrics',
    menu_label: 'Sprint Metrics',
    route_path: '/platform/projects/:projectId/scrum/metrics',
    parent_code: 'pmo_section_reporting',
    menu_icon: 'activity',
    sort_order: 6,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-reporting-intelligence',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_section_email',
    menu_label: 'Email & Notifications',
    route_path: null,
    parent_code: null,
    menu_icon: 'mail',
    sort_order: 95,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-email-notifications',
    is_container: true,
  },
  {
    menu_code: 'pmo_comms_section',
    menu_label: 'Communications',
    route_path: null,
    parent_code: 'pmo_section_email',
    menu_icon: 'message-square',
    sort_order: 5,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-email-notifications',
    is_container: true,
  },
  {
    menu_code: 'pmo_comms_messages',
    menu_label: 'Messages',
    route_path: '/platform/comms/messages',
    parent_code: 'pmo_comms_section',
    menu_icon: 'message-square',
    sort_order: 1,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-email-notifications',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_comms_direct',
    menu_label: 'Direct Messages',
    route_path: '/platform/comms/direct',
    parent_code: 'pmo_comms_section',
    menu_icon: 'message-square',
    sort_order: 2,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-email-notifications',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_comms_meetings',
    menu_label: 'Meetings',
    route_path: '/platform/comms/meetings',
    parent_code: 'pmo_comms_section',
    menu_icon: 'clipboard-list',
    sort_order: 3,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-email-notifications',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_delivery_story_map',
    menu_label: 'Story Map',
    route_path: '/platform/projects/:projectId/scrum/story-map',
    parent_code: null,
    menu_icon: 'map',
    sort_order: 10,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-projects',
    registry_fallback: true,
  },

  // ── v660: Knowledge & Assets, System Admin, Agile/Lean, Workflows, Admin extras ──
  {
    menu_code: 'pmo_section_knowledge',
    menu_label: 'Knowledge & Assets',
    route_path: null,
    parent_code: null,
    menu_icon: 'library',
    sort_order: 88,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-knowledge-assets',
    is_container: true,
  },
  {
    menu_code: 'pmo_knowledge_hub',
    menu_label: 'Org Knowledge Hub',
    route_path: '/platform/org-knowledge',
    parent_code: 'pmo_section_knowledge',
    menu_icon: 'book-open',
    sort_order: 1,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-knowledge-assets',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_knowledge_opa',
    menu_label: 'Process Assets',
    route_path: '/platform/opa',
    parent_code: 'pmo_section_knowledge',
    menu_icon: 'library',
    sort_order: 2,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-knowledge-assets',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_knowledge_opa_new',
    menu_label: 'Add OPA',
    route_path: '/platform/opa/new',
    parent_code: 'pmo_section_knowledge',
    menu_icon: 'file-plus',
    sort_order: 3,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-knowledge-assets',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_knowledge_opa_drafts',
    menu_label: 'OPA Drafts',
    route_path: '/platform/opa/on-hold',
    parent_code: 'pmo_section_knowledge',
    menu_icon: 'pause',
    sort_order: 4,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-knowledge-assets',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_knowledge_opa_bulk',
    menu_label: 'OPA Bulk upload',
    route_path: '/platform/opa/bulk-upload',
    parent_code: 'pmo_section_knowledge',
    menu_icon: 'upload',
    sort_order: 5,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-knowledge-assets',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_section_system_admin',
    menu_label: 'System Administration',
    route_path: null,
    parent_code: null,
    menu_icon: 'shield',
    sort_order: 98,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-system-admin',
    is_container: true,
  },
  {
    menu_code: 'pmo_sys_platform_settings',
    menu_label: 'Platform Settings',
    route_path: '/platform/settings',
    parent_code: 'pmo_section_system_admin',
    menu_icon: 'settings-2',
    sort_order: 1,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-system-admin',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_sys_pwa_settings',
    menu_label: 'PWA Settings',
    route_path: '/platform/pwa-settings',
    parent_code: 'pmo_section_system_admin',
    menu_icon: 'settings-2',
    sort_order: 2,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-system-admin',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_sys_documentation_manager',
    menu_label: 'Documentation Manager',
    route_path: '/app/admin/documentation',
    parent_code: 'pmo_section_system_admin',
    menu_icon: 'book-open',
    sort_order: 3,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-system-admin',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_agile_scrum_of_scrums',
    menu_label: 'Scrum of Scrums',
    route_path: '/platform/projects/:projectId/scrum/scrum-of-scrums',
    parent_code: null,
    menu_icon: 'users',
    sort_order: 11,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-agile-lean',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_agile_value_stream',
    menu_label: 'Value Stream Map',
    route_path: '/platform/projects/:projectId/lean/value-stream-map',
    parent_code: null,
    menu_icon: 'git-branch',
    sort_order: 12,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-agile-lean',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_agile_kaizen',
    menu_label: 'Kaizen Board',
    route_path: '/platform/projects/:projectId/lean/kaizen',
    parent_code: null,
    menu_icon: 'refresh-ccw',
    sort_order: 13,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-agile-lean',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_delivery_releases',
    menu_label: 'Releases',
    route_path: '/platform/projects/:projectId/scrum/releases',
    parent_code: null,
    menu_icon: 'rocket',
    sort_order: 14,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-projects',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_report_lean_metrics',
    menu_label: 'Lean Metrics',
    route_path: '/platform/projects/:projectId/lean/metrics',
    parent_code: 'pmo_section_reporting',
    menu_icon: 'trending-up',
    sort_order: 9,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-reporting-intelligence',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_report_agile_metrics',
    menu_label: 'Agile Metrics Hub',
    route_path: '/platform/projects/:projectId/agile/metrics',
    parent_code: 'pmo_section_reporting',
    menu_icon: 'activity',
    sort_order: 10,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-reporting-intelligence',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_comms_pending_ai',
    menu_label: 'Pending AI Reviews',
    route_path: '/platform/comms/pending-review',
    parent_code: 'pmo_comms_section',
    menu_icon: 'sparkles',
    sort_order: 4,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-email-notifications',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_gov_mandates_create',
    menu_label: 'Create Mandate',
    route_path: '/platform/mandates/create',
    parent_code: 'pmo_section_governance',
    menu_icon: 'file-plus',
    sort_order: 0,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_gov_mandates_all',
    menu_label: 'All Mandates',
    route_path: '/platform/mandates/list',
    parent_code: 'pmo_section_governance',
    menu_icon: 'file-text',
    sort_order: 0,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_gov_mandates_unlinked',
    menu_label: 'Unlinked Mandates',
    route_path: '/platform/mandates/unlinked',
    parent_code: 'pmo_section_governance',
    menu_icon: 'git-branch',
    sort_order: 0,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_init_briefs_all',
    menu_label: 'All Briefs',
    route_path: '/platform/briefs/list',
    parent_code: 'pmo_section_initiation',
    menu_icon: 'file-text',
    sort_order: 4,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-initiation',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_section_workflows',
    menu_label: 'Workflows & Approvals',
    route_path: null,
    parent_code: null,
    menu_icon: 'workflow',
    sort_order: 82,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-workflows-approvals',
    is_container: true,
  },
  {
    menu_code: 'pmo_workflows_mandate_pending',
    menu_label: 'Mandate Approvals',
    route_path: '/platform/mandates/approvals',
    parent_code: 'pmo_section_workflows',
    menu_icon: 'file-check',
    sort_order: 1,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-workflows-approvals',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_workflows_brief_pending',
    menu_label: 'Project Brief Approvals',
    route_path: '/platform/briefs/approvals',
    parent_code: 'pmo_section_workflows',
    menu_icon: 'file-check',
    sort_order: 2,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-workflows-approvals',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_admin_project_statuses',
    menu_label: 'Project Statuses',
    route_path: '/platform/pmo-admin/project-statuses',
    parent_code: null,
    menu_icon: 'layers',
    sort_order: 96,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-admin',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_people_assign_roles',
    menu_label: 'Assign Roles to Projects',
    route_path: '/platform/admin/assign-roles-to-projects',
    parent_code: null,
    menu_icon: 'shield',
    sort_order: 93,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-teams',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_people_add_users',
    menu_label: 'Add users to project',
    route_path: '/platform/project-members',
    parent_code: null,
    menu_icon: 'user-plus',
    sort_order: 94,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-teams',
    registry_fallback: true,
  },

  // ── Initiation (Platform PM dashboard) ─────────────────────────────────────
  {
    menu_code: 'pm_section_initiation',
    menu_label: 'Business Justification',
    route_path: null,
    parent_code: null,
    menu_icon: 'briefcase',
    sort_order: 27,
    domain: 'platform',
    roles: ['project_manager'],
    category: null,
    is_container: true,
  },
  {
    menu_code: 'pm_init_business_case',
    menu_label: 'Business Case',
    route_path: '/pm/initiation/business-case',
    parent_code: 'pm_section_initiation',
    menu_icon: 'briefcase',
    sort_order: 1,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'pm_init_project_brief',
    menu_label: 'Project Brief',
    route_path: '/pm/initiation/project-brief',
    parent_code: 'pm_section_initiation',
    menu_icon: 'file-text',
    sort_order: 2,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'pm_init_pid',
    menu_label: 'Project Initiation Document (PID)',
    route_path: '/pm/initiation/pid',
    parent_code: 'pm_section_initiation',
    menu_icon: 'file-box',
    sort_order: 3,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'pm_init_benefits_review_plan',
    menu_label: 'Benefits Review Plan',
    route_path: '/pm/initiation/benefits-review-plan',
    parent_code: 'pm_section_initiation',
    menu_icon: 'book-open',
    sort_order: 4,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },

  // ── Simulator PMO: Initiation ───────────────────────────────────────────────
  {
    menu_code: 'sim_pmo_section_initiation',
    menu_label: 'Business Justification',
    route_path: null,
    parent_code: null,
    menu_icon: 'briefcase',
    sort_order: 50,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    is_container: true,
  },
  {
    menu_code: 'sim_pmo_init_business_case',
    menu_label: 'Practice Business Case',
    route_path: '/simulator/pmo/initiation/business-case',
    parent_code: 'sim_pmo_section_initiation',
    menu_icon: 'briefcase',
    sort_order: 1,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_init_project_brief',
    menu_label: 'Practice Project Brief',
    route_path: '/simulator/pmo/initiation/project-brief',
    parent_code: 'sim_pmo_section_initiation',
    menu_icon: 'file-text',
    sort_order: 2,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_init_benefits_review_plan',
    menu_label: 'Practice Benefits Review Plan',
    route_path: '/simulator/pmo/initiation/benefits-review-plan',
    parent_code: 'sim_pmo_section_initiation',
    menu_icon: 'book-open',
    sort_order: 3,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },

  // ── Simulator PMO: Governance ─────────────────────────────────────────────
  {
    menu_code: 'sim_pmo_section_governance',
    menu_label: 'Governance & Standards',
    route_path: null,
    parent_code: null,
    menu_icon: 'shield',
    sort_order: 40,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    is_container: true,
  },
  {
    menu_code: 'sim_pmo_gov_mandate',
    menu_label: 'Practice Project Mandate',
    route_path: '/simulator/pmo/governance/mandate',
    parent_code: 'sim_pmo_section_governance',
    menu_icon: 'file-text',
    sort_order: 1,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_gov_communication_strategy',
    menu_label: 'Practice Communication Management Strategy',
    route_path: '/simulator/pmo/governance/communication-strategy',
    parent_code: 'sim_pmo_section_governance',
    menu_icon: 'megaphone',
    sort_order: 2,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_gov_configuration_strategy',
    menu_label: 'Practice Configuration Management Strategy',
    route_path: '/simulator/pmo/governance/configuration-strategy',
    parent_code: 'sim_pmo_section_governance',
    menu_icon: 'settings-2',
    sort_order: 3,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_gov_quality_strategy',
    menu_label: 'Practice Quality Management Strategy',
    route_path: '/simulator/pmo/governance/quality-strategy',
    parent_code: 'sim_pmo_section_governance',
    menu_icon: 'check-square',
    sort_order: 4,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_gov_risk_strategy',
    menu_label: 'Practice Risk Management Strategy',
    route_path: '/simulator/pmo/governance/risk-strategy',
    parent_code: 'sim_pmo_section_governance',
    menu_icon: 'alert-triangle',
    sort_order: 5,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_gov_itto_templates',
    menu_label: 'ITTO Templates',
    route_path: '/simulator/pmo/itto/templates',
    parent_code: 'sim_pmo_section_governance',
    menu_icon: 'git-branch',
    sort_order: 6,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_gov_itto_drafts',
    menu_label: 'ITTO Drafts',
    route_path: '/simulator/pmo/itto/drafts',
    parent_code: 'sim_pmo_section_governance',
    menu_icon: 'pause',
    sort_order: 7,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },

  // ── Simulator PMO: Oversight ────────────────────────────────────────────────
  {
    menu_code: 'sim_pmo_section_oversight',
    menu_label: 'Practice Project Oversight',
    route_path: null,
    parent_code: null,
    menu_icon: 'eye',
    sort_order: 55,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    is_container: true,
  },
  {
    menu_code: 'sim_pmo_oversight_risk_register',
    menu_label: 'Practice Risk Register',
    route_path: '/simulator/pmo/oversight/risk-register',
    parent_code: 'sim_pmo_section_oversight',
    menu_icon: 'alert-triangle',
    sort_order: 1,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_oversight_issue_register',
    menu_label: 'Practice Issue Register',
    route_path: '/simulator/pmo/oversight/issue-register',
    parent_code: 'sim_pmo_section_oversight',
    menu_icon: 'alert-circle',
    sort_order: 2,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_oversight_quality_register',
    menu_label: 'Practice Quality Register',
    route_path: '/simulator/pmo/oversight/quality-register',
    parent_code: 'sim_pmo_section_oversight',
    menu_icon: 'clipboard-list',
    sort_order: 3,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_oversight_lessons_log',
    menu_label: 'Practice Lessons Log',
    route_path: '/simulator/pmo/oversight/lessons-log',
    parent_code: 'sim_pmo_section_oversight',
    menu_icon: 'graduation-cap',
    sort_order: 4,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_oversight_delays',
    menu_label: 'Delay Register',
    route_path: '/simulator/pmo/oversight/delays',
    parent_code: 'sim_pmo_section_oversight',
    menu_icon: 'file-clock',
    sort_order: 5,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_oversight_scope',
    menu_label: 'Scope Oversight',
    route_path: '/simulator/pmo/oversight/scope',
    parent_code: 'sim_pmo_section_oversight',
    menu_icon: 'clipboard-list',
    sort_order: 7,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_oversight_schedules',
    menu_label: 'Schedule Oversight',
    route_path: '/simulator/pmo/oversight/schedules',
    parent_code: 'sim_pmo_section_oversight',
    menu_icon: 'file-clock',
    sort_order: 8,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },

  // ── Simulator PMO: Process Templates (v635 codes) ─────────────────────────
  {
    menu_code: 'sim_pmo_process_templates_section',
    menu_label: 'Process Templates',
    route_path: null,
    parent_code: null,
    menu_icon: 'layers',
    sort_order: 75,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    is_container: true,
  },
  {
    menu_code: 'sim_pmo_pt_hub',
    menu_label: 'Hub Overview',
    route_path: '/simulator/pmo/process-templates',
    parent_code: 'sim_pmo_process_templates_section',
    menu_icon: 'layers',
    sort_order: 1,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_pt_pre',
    menu_label: 'Pre-Project',
    route_path: '/simulator/pmo/process-templates/pre-project',
    parent_code: 'sim_pmo_process_templates_section',
    menu_icon: 'file-text',
    sort_order: 2,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_pt_init',
    menu_label: 'Initiating',
    route_path: '/simulator/pmo/process-templates/initiating',
    parent_code: 'sim_pmo_process_templates_section',
    menu_icon: 'play-circle',
    sort_order: 3,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_pt_plan',
    menu_label: 'Planning',
    route_path: '/simulator/pmo/process-templates/planning',
    parent_code: 'sim_pmo_process_templates_section',
    menu_icon: 'map',
    sort_order: 4,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_pt_exec',
    menu_label: 'Executing',
    route_path: '/simulator/pmo/process-templates/executing',
    parent_code: 'sim_pmo_process_templates_section',
    menu_icon: 'zap',
    sort_order: 5,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_pt_mon',
    menu_label: 'Monitoring & Control',
    route_path: '/simulator/pmo/process-templates/monitoring-controlling',
    parent_code: 'sim_pmo_process_templates_section',
    menu_icon: 'activity',
    sort_order: 6,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_pt_close',
    menu_label: 'Closing',
    route_path: '/simulator/pmo/process-templates/closing',
    parent_code: 'sim_pmo_process_templates_section',
    menu_icon: 'check-circle',
    sort_order: 7,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_oversight_delay_templates',
    menu_label: 'Delay Templates',
    route_path: '/simulator/pmo/delays/templates',
    parent_code: 'sim_pmo_process_templates_section',
    menu_icon: 'layers',
    sort_order: 8,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_pt_browse',
    menu_label: 'Browse Templates',
    route_path: '/simulator/pmo/templates/browse',
    parent_code: 'sim_pmo_process_templates_section',
    menu_icon: 'layers',
    sort_order: 8,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_pt_manage',
    menu_label: 'Manage Templates',
    route_path: '/simulator/pmo/templates/manage',
    parent_code: 'sim_pmo_process_templates_section',
    menu_icon: 'settings-2',
    sort_order: 9,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_pt_agile',
    menu_label: 'Agile Templates',
    route_path: '/simulator/pmo/templates/agile',
    parent_code: 'sim_pmo_process_templates_section',
    menu_icon: 'activity',
    sort_order: 10,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_pt_new',
    menu_label: 'New Template',
    route_path: '/simulator/pmo/templates/new',
    parent_code: 'sim_pmo_process_templates_section',
    menu_icon: 'file-plus',
    sort_order: 11,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_oversight_changes',
    menu_label: 'Change Register (All)',
    route_path: '/simulator/pmo/registers/changes',
    parent_code: 'sim_pmo_section_oversight',
    menu_icon: 'refresh-ccw',
    sort_order: 9,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_gov_eef_list',
    menu_label: 'Environment Factors',
    route_path: '/simulator/pmo/eef',
    parent_code: 'sim_pmo_section_governance',
    menu_icon: 'package-open',
    sort_order: 8,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_gov_eef_new',
    menu_label: 'Add EEF',
    route_path: '/simulator/pmo/eef/new',
    parent_code: 'sim_pmo_section_governance',
    menu_icon: 'file-plus',
    sort_order: 9,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_gov_eef_drafts',
    menu_label: 'EEF Drafts',
    route_path: '/simulator/pmo/eef/on-hold',
    parent_code: 'sim_pmo_section_governance',
    menu_icon: 'pause',
    sort_order: 10,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_section_planning',
    menu_label: 'Planning Intelligence',
    route_path: null,
    parent_code: null,
    menu_icon: 'bar-chart-3',
    sort_order: 72,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    is_container: true,
  },
  {
    menu_code: 'sim_pmo_planning_hub',
    menu_label: 'Planning Hub',
    route_path: '/simulator/pmo/planning',
    parent_code: 'sim_pmo_section_planning',
    menu_icon: 'layout-dashboard',
    sort_order: 1,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_planning_intelligence',
    menu_label: 'Intelligence Rules',
    route_path: '/simulator/pmo/planning/intelligence',
    parent_code: 'sim_pmo_section_planning',
    menu_icon: 'search-code',
    sort_order: 2,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_planning_governance_config',
    menu_label: 'Governance Rules Config',
    route_path: '/simulator/pmo/planning/governance-config',
    parent_code: 'sim_pmo_section_planning',
    menu_icon: 'shield-check',
    sort_order: 3,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_section_reporting',
    menu_label: 'Reporting & Assurance',
    route_path: null,
    parent_code: null,
    menu_icon: 'bar-chart-3',
    sort_order: 90,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    is_container: true,
  },
  {
    menu_code: 'sim_pmo_report_highlight',
    menu_label: 'Practice Highlight Reports',
    route_path: '/simulator/pmo/reporting/highlight-reports',
    parent_code: 'sim_pmo_section_reporting',
    menu_icon: 'flag',
    sort_order: 1,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_report_exception',
    menu_label: 'Practice Exception Reports',
    route_path: '/simulator/pmo/reporting/exception-reports',
    parent_code: 'sim_pmo_section_reporting',
    menu_icon: 'file-warning',
    sort_order: 2,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_report_end_stage',
    menu_label: 'Practice End Stage Reports',
    route_path: '/simulator/pmo/reporting/end-stage-reports',
    parent_code: 'sim_pmo_section_reporting',
    menu_icon: 'file-clock',
    sort_order: 3,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_report_end_project',
    menu_label: 'Practice End Project Reports',
    route_path: '/simulator/pmo/reporting/end-project-reports',
    parent_code: 'sim_pmo_section_reporting',
    menu_icon: 'file-check',
    sort_order: 4,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_report_lessons',
    menu_label: 'Practice Lessons Report',
    route_path: '/simulator/pmo/reporting/lessons-report',
    parent_code: 'sim_pmo_section_reporting',
    menu_icon: 'graduation-cap',
    sort_order: 5,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_report_sprint_metrics',
    menu_label: 'Sprint Metrics',
    route_path: '/simulator/pmo/reporting/sprint-metrics',
    parent_code: 'sim_pmo_section_reporting',
    menu_icon: 'activity',
    sort_order: 6,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_report_library',
    menu_label: 'Report Library',
    route_path: '/simulator/reports',
    parent_code: 'sim_pmo_section_reporting',
    menu_icon: 'file-text',
    sort_order: 7,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_report_analytics',
    menu_label: 'Analytics',
    route_path: '/simulator/reports/analytics',
    parent_code: 'sim_pmo_section_reporting',
    menu_icon: 'bar-chart-3',
    sort_order: 8,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_section_email',
    menu_label: 'Email & Notifications',
    route_path: null,
    parent_code: null,
    menu_icon: 'mail',
    sort_order: 95,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    is_container: true,
  },
  {
    menu_code: 'sim_pmo_email_settings',
    menu_label: 'Email Settings',
    route_path: '/simulator/pmo/admin/email-settings',
    parent_code: 'sim_pmo_section_email',
    menu_icon: 'mail',
    sort_order: 1,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_email_sender_profiles',
    menu_label: 'Sender Profiles',
    route_path: '/simulator/pmo/admin/email-sender-profiles',
    parent_code: 'sim_pmo_section_email',
    menu_icon: 'at-sign',
    sort_order: 2,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_email_invitation_templates',
    menu_label: 'Invitation Templates',
    route_path: '/simulator/settings/invitation-templates',
    parent_code: 'sim_pmo_section_email',
    menu_icon: 'file-text',
    sort_order: 3,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_email_invitation_expiry',
    menu_label: 'Invitation Expiry',
    route_path: '/simulator/pmo/admin/invitation-settings',
    parent_code: 'sim_pmo_section_email',
    menu_icon: 'clock',
    sort_order: 4,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_comms_messages',
    menu_label: 'Messages',
    route_path: '/simulator/comms/messages',
    parent_code: 'sim_pmo_section_email',
    menu_icon: 'message-square',
    sort_order: 5,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_comms_direct',
    menu_label: 'Direct Messages',
    route_path: '/simulator/comms/direct',
    parent_code: 'sim_pmo_section_email',
    menu_icon: 'message-square',
    sort_order: 6,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_comms_meetings',
    menu_label: 'Meetings',
    route_path: '/simulator/comms/meetings',
    parent_code: 'sim_pmo_section_email',
    menu_icon: 'clipboard-list',
    sort_order: 7,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_comms_pending_ai',
    menu_label: 'Pending AI Reviews',
    route_path: '/simulator/comms/pending-review',
    parent_code: 'sim_pmo_section_email',
    menu_icon: 'sparkles',
    sort_order: 8,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-email-notifications',
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_section_knowledge',
    menu_label: 'Practice Knowledge & Assets',
    route_path: null,
    parent_code: null,
    menu_icon: 'library',
    sort_order: 88,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-knowledge-assets',
    is_container: true,
  },
  {
    menu_code: 'sim_pmo_knowledge_hub',
    menu_label: 'Org Knowledge Hub',
    route_path: '/simulator/opa',
    parent_code: 'sim_pmo_section_knowledge',
    menu_icon: 'book-open',
    sort_order: 1,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-knowledge-assets',
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_knowledge_opa',
    menu_label: 'Process Assets',
    route_path: '/simulator/opa',
    parent_code: 'sim_pmo_section_knowledge',
    menu_icon: 'library',
    sort_order: 2,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-knowledge-assets',
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_knowledge_opa_new',
    menu_label: 'Add OPA',
    route_path: '/simulator/opa/new',
    parent_code: 'sim_pmo_section_knowledge',
    menu_icon: 'file-plus',
    sort_order: 3,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-knowledge-assets',
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_knowledge_opa_drafts',
    menu_label: 'OPA Drafts',
    route_path: '/simulator/opa/on-hold',
    parent_code: 'sim_pmo_section_knowledge',
    menu_icon: 'pause',
    sort_order: 4,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-knowledge-assets',
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_knowledge_opa_bulk',
    menu_label: 'OPA Bulk upload',
    route_path: '/simulator/opa/bulk-upload',
    parent_code: 'sim_pmo_section_knowledge',
    menu_icon: 'upload',
    sort_order: 5,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-knowledge-assets',
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_section_system_admin',
    menu_label: 'System Administration',
    route_path: null,
    parent_code: null,
    menu_icon: 'shield',
    sort_order: 98,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-system-admin',
    is_container: true,
  },
  {
    menu_code: 'sim_pmo_sys_platform_settings',
    menu_label: 'Platform Settings',
    route_path: '/simulator/pmo/admin/settings',
    parent_code: 'sim_pmo_section_system_admin',
    menu_icon: 'settings-2',
    sort_order: 1,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-system-admin',
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_sys_pwa_settings',
    menu_label: 'PWA Settings',
    route_path: '/simulator/pwa-settings',
    parent_code: 'sim_pmo_section_system_admin',
    menu_icon: 'settings-2',
    sort_order: 2,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-system-admin',
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_agile_scrum_of_scrums',
    menu_label: 'Scrum of Scrums',
    route_path: '/simulator/practice-projects/:projectId/scrum/scrum-of-scrums',
    parent_code: null,
    menu_icon: 'users',
    sort_order: 11,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-agile-lean',
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_agile_value_stream',
    menu_label: 'Value Stream Map',
    route_path: '/simulator/practice-projects/:projectId/lean/value-stream-map',
    parent_code: null,
    menu_icon: 'git-branch',
    sort_order: 12,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-agile-lean',
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_agile_kaizen',
    menu_label: 'Kaizen Board',
    route_path: '/simulator/practice-projects/:projectId/lean/kaizen',
    parent_code: null,
    menu_icon: 'refresh-ccw',
    sort_order: 13,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-agile-lean',
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_delivery_releases',
    menu_label: 'Releases',
    route_path: '/simulator/practice-projects/:projectId/scrum/releases',
    parent_code: null,
    menu_icon: 'rocket',
    sort_order: 14,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-projects',
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_report_lean_metrics',
    menu_label: 'Lean Metrics',
    route_path: '/simulator/practice-projects/:projectId/lean/metrics',
    parent_code: 'sim_pmo_section_reporting',
    menu_icon: 'trending-up',
    sort_order: 9,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-reporting-intelligence',
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_report_agile_metrics',
    menu_label: 'Agile Metrics Hub',
    route_path: '/simulator/practice-projects/:projectId/agile/metrics',
    parent_code: 'sim_pmo_section_reporting',
    menu_icon: 'activity',
    sort_order: 10,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-reporting-intelligence',
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_gov_mandates_create',
    menu_label: 'Create Mandate',
    route_path: '/simulator/mandates/create',
    parent_code: 'sim_pmo_section_governance',
    menu_icon: 'file-plus',
    sort_order: 0,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_gov_mandates_all',
    menu_label: 'All Mandates',
    route_path: '/simulator/mandates/list',
    parent_code: 'sim_pmo_section_governance',
    menu_icon: 'file-text',
    sort_order: 0,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_init_briefs_all',
    menu_label: 'All Briefs',
    route_path: '/simulator/practice-briefs',
    parent_code: 'sim_pmo_section_initiation',
    menu_icon: 'file-text',
    sort_order: 4,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-initiation',
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_section_workflows',
    menu_label: 'Workflows & Approvals',
    route_path: null,
    parent_code: null,
    menu_icon: 'workflow',
    sort_order: 82,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-workflows-approvals',
    is_container: true,
  },
  {
    menu_code: 'sim_pmo_workflows_mandate_pending',
    menu_label: 'Mandate Approvals',
    route_path: '/simulator/mandates/list',
    parent_code: 'sim_pmo_section_workflows',
    menu_icon: 'file-check',
    sort_order: 1,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-workflows-approvals',
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_workflows_brief_pending',
    menu_label: 'Project Brief Approvals',
    route_path: '/simulator/practice-briefs',
    parent_code: 'sim_pmo_section_workflows',
    menu_icon: 'file-check',
    sort_order: 2,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-workflows-approvals',
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_admin_project_statuses',
    menu_label: 'Project Statuses',
    route_path: '/simulator/pmo/admin/project-statuses',
    parent_code: 'sim_pmo_section_admin',
    menu_icon: 'layers',
    sort_order: 7,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-admin',
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_admin_integrations',
    menu_label: 'Integrations Hub',
    route_path: '/simulator/pmo/admin/integrations',
    parent_code: 'sim_pmo_section_admin',
    menu_icon: 'plug',
    sort_order: 11,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-admin',
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_people_assign_roles',
    menu_label: 'Assign Roles to Projects',
    route_path: '/simulator/pmo/manager-assignments',
    parent_code: null,
    menu_icon: 'shield',
    sort_order: 93,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-teams',
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_people_add_users',
    menu_label: 'Add users to project',
    route_path: '/simulator/practice-project-members',
    parent_code: null,
    menu_icon: 'user-plus',
    sort_order: 94,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-teams',
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_section_admin',
    menu_label: 'Administration',
    route_path: null,
    parent_code: null,
    menu_icon: 'settings-2',
    sort_order: 100,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    is_container: true,
  },
  {
    menu_code: 'sim_pmo_admin_local_data',
    menu_label: 'Local Data Extensions',
    route_path: '/simulator/local-data-extensions',
    parent_code: 'sim_pmo_section_admin',
    menu_icon: 'database',
    sort_order: 1,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_admin_form_templates',
    menu_label: 'Form Templates',
    route_path: '/simulator/pmo/admin/form-templates',
    parent_code: 'sim_pmo_section_admin',
    menu_icon: 'file-text',
    sort_order: 2,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_admin_org_settings',
    menu_label: 'Organisation Settings',
    route_path: '/simulator/pmo/admin/settings',
    parent_code: 'sim_pmo_section_admin',
    menu_icon: 'settings-2',
    sort_order: 3,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_admin_users',
    menu_label: 'User Management',
    route_path: '/simulator/pmo/admin/users',
    parent_code: 'sim_pmo_section_admin',
    menu_icon: 'shield',
    sort_order: 4,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_admin_role_menu_access',
    menu_label: 'Role Menu Access',
    route_path: '/simulator/pmo/role-menu-access',
    parent_code: 'sim_pmo_section_admin',
    menu_icon: 'shield-check',
    sort_order: 5,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_admin_project_types',
    menu_label: 'Project Types',
    route_path: '/simulator/pmo/admin/project-types',
    parent_code: 'sim_pmo_section_admin',
    menu_icon: 'layers',
    sort_order: 6,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_admin_funding_sources',
    menu_label: 'Funding Sources',
    route_path: '/simulator/pmo/admin/funding-sources',
    parent_code: 'sim_pmo_section_admin',
    menu_icon: 'dollar-sign',
    sort_order: 7,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_admin_budget_categories',
    menu_label: 'Budget Categories',
    route_path: '/simulator/pmo/admin/budget-categories',
    parent_code: 'sim_pmo_section_admin',
    menu_icon: 'dollar-sign',
    sort_order: 8,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_admin_subscription',
    menu_label: 'Subscription',
    route_path: '/simulator/pmo/admin/subscription',
    parent_code: 'sim_pmo_section_admin',
    menu_icon: 'settings-2',
    sort_order: 9,
    domain: 'simulator',
    roles: ['system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_admin_branding',
    menu_label: 'Branding',
    route_path: '/simulator/pmo/admin/branding',
    parent_code: 'sim_pmo_section_admin',
    menu_icon: 'settings-2',
    sort_order: 10,
    domain: 'simulator',
    roles: ['system_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_admin_documentation_manager',
    menu_label: 'Documentation Manager',
    route_path: '/simulator/admin/documentation',
    parent_code: 'sim_pmo_section_admin',
    menu_icon: 'book-open',
    sort_order: 11,
    domain: 'simulator',
    roles: ['pmo_admin', 'system_admin'],
    registry_fallback: true,
  },

  // ── Simulator PM: Initiation ────────────────────────────────────────────────
  {
    menu_code: 'sim_pm_section_initiation',
    menu_label: 'Business Justification',
    route_path: null,
    parent_code: null,
    menu_icon: 'briefcase',
    sort_order: 27,
    domain: 'simulator',
    roles: ['project_manager'],
    is_container: true,
  },
  {
    menu_code: 'sim_pm_init_business_case',
    menu_label: 'Practice Business Case',
    route_path: '/simulator/pm/initiation/business-case',
    parent_code: 'sim_pm_section_initiation',
    menu_icon: 'briefcase',
    sort_order: 1,
    domain: 'simulator',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pm_init_project_brief',
    menu_label: 'Practice Project Brief',
    route_path: '/simulator/pm/initiation/project-brief',
    parent_code: 'sim_pm_section_initiation',
    menu_icon: 'file-text',
    sort_order: 2,
    domain: 'simulator',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pm_init_pid',
    menu_label: 'Practice Project Initiation Document (PID)',
    route_path: '/simulator/pm/initiation/pid',
    parent_code: 'sim_pm_section_initiation',
    menu_icon: 'file-text',
    sort_order: 3,
    domain: 'simulator',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pm_init_benefits_review_plan',
    menu_label: 'Practice Benefits Review Plan',
    route_path: '/simulator/pm/initiation/benefits-review-plan',
    parent_code: 'sim_pm_section_initiation',
    menu_icon: 'book-open',
    sort_order: 4,
    domain: 'simulator',
    roles: ['project_manager'],
    registry_fallback: true,
  },

  // ── Simulator PM: Process Templates (v635 codes) ────────────────────────────
  {
    menu_code: 'sim_pm_process_templates_section',
    menu_label: 'Process Templates',
    route_path: null,
    parent_code: null,
    menu_icon: 'layers',
    sort_order: 145,
    domain: 'simulator',
    roles: ['project_manager'],
    is_container: true,
  },
  {
    menu_code: 'sim_pm_pt_hub',
    menu_label: 'Hub Overview',
    route_path: '/simulator/pm/process-templates',
    parent_code: 'sim_pm_process_templates_section',
    menu_icon: 'layers',
    sort_order: 1,
    domain: 'simulator',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pm_pt_pre',
    menu_label: 'Pre-Project',
    route_path: '/simulator/pm/process-templates/pre-project',
    parent_code: 'sim_pm_process_templates_section',
    menu_icon: 'file-text',
    sort_order: 2,
    domain: 'simulator',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pm_pt_init',
    menu_label: 'Initiating',
    route_path: '/simulator/pm/process-templates/initiating',
    parent_code: 'sim_pm_process_templates_section',
    menu_icon: 'play-circle',
    sort_order: 3,
    domain: 'simulator',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pm_pt_plan',
    menu_label: 'Planning',
    route_path: '/simulator/pm/process-templates/planning',
    parent_code: 'sim_pm_process_templates_section',
    menu_icon: 'map',
    sort_order: 4,
    domain: 'simulator',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pm_pt_exec',
    menu_label: 'Executing',
    route_path: '/simulator/pm/process-templates/executing',
    parent_code: 'sim_pm_process_templates_section',
    menu_icon: 'zap',
    sort_order: 5,
    domain: 'simulator',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pm_pt_mon',
    menu_label: 'Monitoring & Control',
    route_path: '/simulator/pm/process-templates/monitoring-controlling',
    parent_code: 'sim_pm_process_templates_section',
    menu_icon: 'activity',
    sort_order: 6,
    domain: 'simulator',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pm_pt_close',
    menu_label: 'Closing',
    route_path: '/simulator/pm/process-templates/closing',
    parent_code: 'sim_pm_process_templates_section',
    menu_icon: 'check-circle',
    sort_order: 7,
    domain: 'simulator',
    roles: ['project_manager'],
    registry_fallback: true,
  },

  ...PMIS_GAP_MENU_REGISTRY,
  ...RECORD_LIFECYCLE_MENU_REGISTRY,
]

/**
 * @param {MenuDomain} [domain='platform']
 * @returns {MenuRegistryEntry[]}
 */
export function getMenuRegistryEntries(domain = 'platform') {
  return withRegistryMethodology(MENU_REGISTRY.filter((e) => e.domain === domain))
}

/**
 * Registry entries marked for client-side fallback when DB row is missing.
 * @param {MenuDomain} [domain='platform']
 * @returns {MenuRegistryEntry[]}
 */
export function getRegistryFallbackEntries(_domain = 'platform') {
  // v664+: catalogue entries may retain registry_fallback for SQL/docs; never inject at runtime.
  return []
}

/**
 * @param {string} categoryId
 * @param {MenuDomain} [domain='platform']
 * @returns {MenuRegistryEntry[]}
 */
export function getRegistryEntriesForCategory(categoryId, domain = 'platform') {
  return MENU_REGISTRY.filter(
    (e) => e.domain === domain && e.category === categoryId && e.route_path && !e.is_container
  )
}

/**
 * Unique menu_codes from registry (for SQL seed generation).
 * @returns {string[]}
 */
export function getRegistryMenuCodes() {
  return MENU_REGISTRY.map((e) => e.menu_code)
}

export default MENU_REGISTRY
