/**
 * v631 PMIS gap sidebar menu entries — merged into menuRegistry.js
 * @see projectplan/v631_PMIS_Gap_Analysis_Implementation_Plan.md
 */

/** @type {import('./menuRegistry.js').MenuRegistryEntry[]} */
export const PMIS_GAP_MENU_REGISTRY = [
  // ── PM: Calendar (GAP-09) ───────────────────────────────────────────────────
  {
    menu_code: 'pm_calendar',
    menu_label: 'Calendar',
    route_path: '/pm/calendar',
    parent_code: null,
    menu_icon: 'calendar-days',
    sort_order: 5,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  // ── PM: Automation (GAP-01) ─────────────────────────────────────────────────
  {
    menu_code: 'pm_section_automation',
    menu_label: 'Automation',
    route_path: null,
    parent_code: null,
    menu_icon: 'zap',
    sort_order: 90,
    domain: 'platform',
    roles: ['project_manager'],
    is_container: true,
  },
  {
    menu_code: 'pm_automation_rules',
    menu_label: 'Automation Rules',
    route_path: '/pm/automations',
    parent_code: 'pm_section_automation',
    menu_icon: 'zap',
    sort_order: 1,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'pm_automation_templates',
    menu_label: 'Template Library',
    route_path: '/pm/automations/templates',
    parent_code: 'pm_section_automation',
    menu_icon: 'layers',
    sort_order: 2,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'pm_automation_log',
    menu_label: 'Execution Log',
    route_path: '/pm/automations/log',
    parent_code: 'pm_section_automation',
    menu_icon: 'activity',
    sort_order: 3,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  // ── PM: Strategy & OKRs (GAP-03) ────────────────────────────────────────────
  {
    menu_code: 'pm_section_okr',
    menu_label: 'Strategy & OKRs',
    route_path: null,
    parent_code: null,
    menu_icon: 'target',
    sort_order: 100,
    domain: 'platform',
    roles: ['project_manager'],
    is_container: true,
  },
  {
    menu_code: 'pm_okr_dashboard',
    menu_label: 'OKR Dashboard',
    route_path: '/pm/okr',
    parent_code: 'pm_section_okr',
    menu_icon: 'target',
    sort_order: 1,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'pm_okr_objectives',
    menu_label: 'Objectives & Key Results',
    route_path: '/pm/okr/objectives',
    parent_code: 'pm_section_okr',
    menu_icon: 'list-checks',
    sort_order: 2,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'pm_okr_alignment',
    menu_label: 'Alignment Map',
    route_path: '/pm/okr/alignment',
    parent_code: 'pm_section_okr',
    menu_icon: 'git-branch',
    sort_order: 3,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'pm_okr_checkins',
    menu_label: 'OKR Check-ins',
    route_path: '/pm/okr/checkins',
    parent_code: 'pm_section_okr',
    menu_icon: 'message-square',
    sort_order: 4,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  // ── PM: Resources Hub (GAP-05, 10, 11, 13, 20) ──────────────────────────────
  {
    menu_code: 'pm_section_resources_hub',
    menu_label: 'Resources Hub',
    route_path: null,
    parent_code: null,
    menu_icon: 'users',
    sort_order: 110,
    domain: 'platform',
    roles: ['project_manager'],
    is_container: true,
  },
  {
    menu_code: 'pm_resources_workload',
    menu_label: 'Workload Heatmap',
    route_path: '/pm/resources/workload',
    parent_code: 'pm_section_resources_hub',
    menu_icon: 'layout-grid',
    sort_order: 1,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'pm_resources_raci',
    menu_label: 'RACI Matrix',
    route_path: '/pm/resources/raci',
    parent_code: 'pm_section_resources_hub',
    menu_icon: 'table-2',
    sort_order: 2,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'pm_resources_skills',
    menu_label: 'Skills Matrix',
    route_path: '/pm/resources/skills',
    parent_code: 'pm_section_resources_hub',
    menu_icon: 'book-marked',
    sort_order: 3,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'pm_resources_timesheet_approvals',
    menu_label: 'Timesheet Approvals',
    route_path: '/pm/resources/timesheet-approvals',
    parent_code: 'pm_section_resources_hub',
    menu_icon: 'clock',
    sort_order: 4,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'pm_resources_training',
    menu_label: 'Training Tracker',
    route_path: '/pm/resources/training',
    parent_code: 'pm_section_resources_hub',
    menu_icon: 'graduation-cap',
    sort_order: 5,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  // ── PM: Project Settings (GAP-04, 06, 07, 08, 19, 22) ───────────────────────
  {
    menu_code: 'pm_section_project_settings',
    menu_label: 'Project Settings',
    route_path: null,
    parent_code: null,
    menu_icon: 'settings',
    sort_order: 120,
    domain: 'platform',
    roles: ['project_manager'],
    is_container: true,
  },
  {
    menu_code: 'pm_settings_custom_fields',
    menu_label: 'Custom Fields',
    route_path: '/pm/settings/custom-fields',
    parent_code: 'pm_section_project_settings',
    menu_icon: 'sliders-horizontal',
    sort_order: 1,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'pm_settings_intake_forms',
    menu_label: 'Public Intake Forms',
    route_path: '/pm/settings/intake-forms',
    parent_code: 'pm_section_project_settings',
    menu_icon: 'file-input',
    sort_order: 2,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'pm_settings_intake_submissions',
    menu_label: 'Form Submissions',
    route_path: '/pm/settings/intake-forms/submissions',
    parent_code: 'pm_section_project_settings',
    menu_icon: 'inbox',
    sort_order: 3,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'pm_settings_client_portal',
    menu_label: 'Client Portal',
    route_path: '/pm/settings/client-portal',
    parent_code: 'pm_section_project_settings',
    menu_icon: 'globe',
    sort_order: 4,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'pm_settings_recurring_tasks',
    menu_label: 'Recurring Tasks',
    route_path: '/pm/settings/recurring-tasks',
    parent_code: 'pm_section_project_settings',
    menu_icon: 'repeat',
    sort_order: 5,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'pm_settings_guest_access',
    menu_label: 'Guest Access',
    route_path: '/pm/settings/guest-access',
    parent_code: 'pm_section_project_settings',
    menu_icon: 'user-plus',
    sort_order: 6,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'pm_settings_project_clone',
    menu_label: 'Project Clone',
    route_path: '/pm/settings/project-clone',
    parent_code: 'pm_section_project_settings',
    menu_icon: 'copy',
    sort_order: 7,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  // ── PM: Procurement (GAP-12) ────────────────────────────────────────────────
  {
    menu_code: 'pm_section_procurement',
    menu_label: 'Procurement & Contracts',
    route_path: null,
    parent_code: null,
    menu_icon: 'shopping-cart',
    sort_order: 130,
    domain: 'platform',
    roles: ['project_manager'],
    is_container: true,
  },
  {
    menu_code: 'pm_procurement_vendors',
    menu_label: 'Vendor Register',
    route_path: '/pm/procurement/vendors',
    parent_code: 'pm_section_procurement',
    menu_icon: 'building-2',
    sort_order: 1,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'pm_procurement_requests',
    menu_label: 'Purchase Requests',
    route_path: '/pm/procurement/requests',
    parent_code: 'pm_section_procurement',
    menu_icon: 'file-text',
    sort_order: 2,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'pm_procurement_orders',
    menu_label: 'Purchase Orders',
    route_path: '/pm/procurement/orders',
    parent_code: 'pm_section_procurement',
    menu_icon: 'receipt',
    sort_order: 3,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'pm_procurement_contracts',
    menu_label: 'Contracts',
    route_path: '/pm/procurement/contracts',
    parent_code: 'pm_section_procurement',
    menu_icon: 'file-signature',
    sort_order: 4,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'pm_procurement_invoices',
    menu_label: 'Invoice Tracking',
    route_path: '/pm/procurement/invoices',
    parent_code: 'pm_section_procurement',
    menu_icon: 'banknote',
    sort_order: 5,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  // ── PM: Planning Tools (GAP-14, 15) ───────────────────────────────────────────
  {
    menu_code: 'pm_section_planning_tools',
    menu_label: 'Planning Tools',
    route_path: null,
    parent_code: null,
    menu_icon: 'line-chart',
    sort_order: 140,
    domain: 'platform',
    roles: ['project_manager'],
    is_container: true,
  },
  {
    menu_code: 'pm_planning_s_curve',
    menu_label: 'S-Curve & Baselines',
    route_path: '/pm/planning/s-curve',
    parent_code: 'pm_section_planning_tools',
    menu_icon: 'line-chart',
    sort_order: 1,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'pm_planning_poker',
    menu_label: 'Planning Poker',
    route_path: '/pm/planning/planning-poker',
    parent_code: 'pm_section_planning_tools',
    menu_icon: 'gamepad-2',
    sort_order: 2,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  // ── PM: Dashboards (GAP-16, 23) ─────────────────────────────────────────────
  {
    menu_code: 'pm_section_dashboards',
    menu_label: 'Dashboards & Analytics',
    route_path: null,
    parent_code: null,
    menu_icon: 'layout-dashboard',
    sort_order: 150,
    domain: 'platform',
    roles: ['project_manager'],
    is_container: true,
  },
  {
    menu_code: 'pm_dashboard_builder',
    menu_label: 'Dashboard Builder',
    route_path: '/pm/dashboards/builder',
    parent_code: 'pm_section_dashboards',
    menu_icon: 'layout-grid',
    sort_order: 1,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'pm_portfolio_map',
    menu_label: 'Portfolio Map',
    route_path: '/pm/strategy/portfolio-map',
    parent_code: 'pm_section_dashboards',
    menu_icon: 'map',
    sort_order: 2,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'pm_scheduled_reports',
    menu_label: 'Scheduled Reports',
    route_path: '/pm/reporting/scheduled',
    parent_code: 'pm_section_dashboards',
    menu_icon: 'calendar-clock',
    sort_order: 3,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  // ── PM: Collaboration (GAP-18) ──────────────────────────────────────────────
  {
    menu_code: 'pm_section_collaboration',
    menu_label: 'Collaboration',
    route_path: null,
    parent_code: null,
    menu_icon: 'pen-tool',
    sort_order: 160,
    domain: 'platform',
    roles: ['project_manager'],
    is_container: true,
  },
  {
    menu_code: 'pm_whiteboard',
    menu_label: 'Whiteboard',
    route_path: '/pm/collaboration/whiteboard',
    parent_code: 'pm_section_collaboration',
    menu_icon: 'pen-tool',
    sort_order: 1,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  // ── PM: Integrations (GAP-25) ─────────────────────────────────────────────────
  {
    menu_code: 'pm_section_integrations',
    menu_label: 'Integrations',
    route_path: null,
    parent_code: null,
    menu_icon: 'plug',
    sort_order: 170,
    domain: 'platform',
    roles: ['project_manager'],
    is_container: true,
  },
  {
    menu_code: 'pm_integrations_marketplace',
    menu_label: 'Integration Marketplace',
    route_path: '/pm/integrations',
    parent_code: 'pm_section_integrations',
    menu_icon: 'plug',
    sort_order: 1,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'pm_integrations_connections',
    menu_label: 'My Connections',
    route_path: '/pm/integrations/connections',
    parent_code: 'pm_section_integrations',
    menu_icon: 'link',
    sort_order: 2,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  // ── PM: Notification Preferences (GAP-21) ─────────────────────────────────────
  {
    menu_code: 'pm_notification_prefs',
    menu_label: 'Notification Preferences',
    route_path: '/pm/settings/notifications',
    parent_code: null,
    menu_icon: 'bell',
    sort_order: 180,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },

  // ── PMO gap sections (mirror PM with pmo prefix) ─────────────────────────────
  {
    menu_code: 'pmo_calendar',
    menu_label: 'Calendar',
    route_path: '/pmo/calendar',
    parent_code: null,
    menu_icon: 'calendar-days',
    sort_order: 5,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-delivery',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_section_okr',
    menu_label: 'Strategy & OKRs',
    route_path: null,
    parent_code: null,
    menu_icon: 'target',
    sort_order: 15,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-strategy',
    is_container: true,
  },
  {
    menu_code: 'pmo_okr_dashboard',
    menu_label: 'OKR Dashboard',
    route_path: '/pmo/okr',
    parent_code: 'pmo_section_okr',
    menu_icon: 'target',
    sort_order: 1,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-strategy',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_okr_objectives',
    menu_label: 'Objectives & KRs',
    route_path: '/pmo/okr/objectives',
    parent_code: 'pmo_section_okr',
    menu_icon: 'list-checks',
    sort_order: 2,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-strategy',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_okr_alignment',
    menu_label: 'Alignment Map',
    route_path: '/pmo/okr/alignment',
    parent_code: 'pmo_section_okr',
    menu_icon: 'git-branch',
    sort_order: 3,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-strategy',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_okr_checkins',
    menu_label: 'OKR Check-ins',
    route_path: '/pmo/okr/checkins',
    parent_code: 'pmo_section_okr',
    menu_icon: 'message-square',
    sort_order: 4,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-strategy',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_portfolio_map',
    menu_label: 'Portfolio Map',
    route_path: '/pmo/strategy/portfolio-map',
    parent_code: 'pmo_section_okr',
    menu_icon: 'map',
    sort_order: 5,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-strategy',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_section_platform_config',
    menu_label: 'Platform Configuration',
    route_path: null,
    parent_code: null,
    menu_icon: 'settings-2',
    sort_order: 135,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    is_container: true,
  },
  {
    menu_code: 'pmo_admin_automations',
    menu_label: 'Automation Rules',
    route_path: '/pmo/admin/automations',
    parent_code: 'pmo_section_platform_config',
    menu_icon: 'zap',
    sort_order: 1,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_admin_custom_fields',
    menu_label: 'Custom Fields',
    route_path: '/pmo/admin/custom-fields',
    parent_code: 'pmo_section_platform_config',
    menu_icon: 'sliders-horizontal',
    sort_order: 2,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_admin_intake_forms',
    menu_label: 'Public Intake Forms',
    route_path: '/pmo/admin/intake-forms',
    parent_code: 'pmo_section_platform_config',
    menu_icon: 'file-input',
    sort_order: 3,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_admin_client_portals',
    menu_label: 'Client Portals',
    route_path: '/pmo/admin/client-portals',
    parent_code: 'pmo_section_platform_config',
    menu_icon: 'globe',
    sort_order: 4,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_admin_integrations',
    menu_label: 'Integrations Hub',
    route_path: '/pmo/admin/integrations',
    parent_code: 'pmo_section_platform_config',
    menu_icon: 'plug',
    sort_order: 5,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_section_resources_hub',
    menu_label: 'Resources & Capacity',
    route_path: null,
    parent_code: null,
    menu_icon: 'users',
    sort_order: 145,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-resources',
    is_container: true,
  },
  {
    menu_code: 'pmo_resources_workload',
    menu_label: 'Workload Heatmap',
    route_path: '/pmo/resources/workload',
    parent_code: 'pmo_section_resources_hub',
    menu_icon: 'layout-grid',
    sort_order: 1,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-resources',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_resources_raci',
    menu_label: 'RACI Matrix (All Projects)',
    route_path: '/pmo/resources/raci',
    parent_code: 'pmo_section_resources_hub',
    menu_icon: 'table-2',
    sort_order: 2,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-resources',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_resources_skills',
    menu_label: 'Skills Matrix',
    route_path: '/pmo/resources/skills',
    parent_code: 'pmo_section_resources_hub',
    menu_icon: 'book-marked',
    sort_order: 3,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-resources',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_section_procurement',
    menu_label: 'Procurement Management',
    route_path: null,
    parent_code: null,
    menu_icon: 'shopping-cart',
    sort_order: 105,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    is_container: true,
  },
  {
    menu_code: 'pmo_procurement_vendors',
    menu_label: 'Vendor Register',
    route_path: '/pmo/procurement/vendors',
    parent_code: 'pmo_section_procurement',
    menu_icon: 'building-2',
    sort_order: 1,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_procurement_requests',
    menu_label: 'Purchase Requests',
    route_path: '/pmo/procurement/requests',
    parent_code: 'pmo_section_procurement',
    menu_icon: 'file-text',
    sort_order: 2,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_procurement_orders',
    menu_label: 'Purchase Orders',
    route_path: '/pmo/procurement/orders',
    parent_code: 'pmo_section_procurement',
    menu_icon: 'receipt',
    sort_order: 3,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_procurement_contracts',
    menu_label: 'Contracts',
    route_path: '/pmo/procurement/contracts',
    parent_code: 'pmo_section_procurement',
    menu_icon: 'file-signature',
    sort_order: 4,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_procurement_invoices',
    menu_label: 'Invoice Tracking',
    route_path: '/pmo/procurement/invoices',
    parent_code: 'pmo_section_procurement',
    menu_icon: 'banknote',
    sort_order: 5,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_section_dashboards',
    menu_label: 'Dashboards & Analytics',
    route_path: null,
    parent_code: null,
    menu_icon: 'layout-dashboard',
    sort_order: 85,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-oversight',
    is_container: true,
  },
  {
    menu_code: 'pmo_dashboard_builder',
    menu_label: 'Dashboard Builder',
    route_path: '/pmo/dashboards/builder',
    parent_code: 'pmo_section_dashboards',
    menu_icon: 'layout-grid',
    sort_order: 1,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-oversight',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_planning_s_curve',
    menu_label: 'S-Curve & Baselines',
    route_path: '/pmo/planning/s-curve',
    parent_code: 'pmo_section_dashboards',
    menu_icon: 'line-chart',
    sort_order: 2,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-oversight',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_scheduled_reports',
    menu_label: 'Scheduled Reports',
    route_path: '/pmo/reporting/scheduled',
    parent_code: 'pmo_section_dashboards',
    menu_icon: 'calendar-clock',
    sort_order: 3,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-oversight',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_whiteboard',
    menu_label: 'Whiteboard',
    route_path: '/pmo/collaboration/whiteboard',
    parent_code: 'pmo_section_collaboration',
    menu_icon: 'pen-tool',
    sort_order: 1,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-delivery',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_section_collaboration',
    menu_label: 'Collaboration',
    route_path: null,
    parent_code: null,
    menu_icon: 'pen-tool',
    sort_order: 155,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-delivery',
    is_container: true,
  },
  {
    menu_code: 'pmo_planning_poker',
    menu_label: 'Planning Poker',
    route_path: '/pmo/planning/planning-poker',
    parent_code: 'pmo_section_collaboration',
    menu_icon: 'gamepad-2',
    sort_order: 2,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-delivery',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_notification_prefs',
    menu_label: 'Notification Preferences',
    route_path: '/pmo/settings/notifications',
    parent_code: null,
    menu_icon: 'bell',
    sort_order: 160,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance-standards',
    registry_fallback: true,
  },

  // ── Platform DB-driven roles ────────────────────────────────────────────────
  {
    menu_code: 'platform_calendar',
    menu_label: 'Calendar',
    route_path: '/platform/calendar',
    parent_code: null,
    menu_icon: 'calendar-days',
    sort_order: 20,
    domain: 'platform',
    roles: ['executive', 'project_sponsor', 'stakeholder', 'team_member', 'team_lead'],
    registry_fallback: true,
  },
  {
    menu_code: 'platform_okr',
    menu_label: 'OKR & Goals',
    route_path: '/platform/okr',
    parent_code: null,
    menu_icon: 'target',
    sort_order: 21,
    domain: 'platform',
    roles: ['executive', 'project_sponsor'],
    registry_fallback: true,
  },
  {
    menu_code: 'platform_workload',
    menu_label: 'Workload Heatmap',
    route_path: '/platform/resources/workload',
    parent_code: null,
    menu_icon: 'layout-grid',
    sort_order: 22,
    domain: 'platform',
    roles: ['project_sponsor', 'team_member', 'team_lead'],
    registry_fallback: true,
  },
  {
    menu_code: 'platform_notification_prefs',
    menu_label: 'Notification Preferences',
    route_path: '/platform/settings/notifications',
    parent_code: null,
    menu_icon: 'bell',
    sort_order: 23,
    domain: 'platform',
    roles: ['executive', 'project_sponsor', 'stakeholder', 'team_member', 'team_lead'],
    registry_fallback: true,
  },

  // ── Simulator general (GAP-26 to 29, 09, 03, etc.) ─────────────────────────
  {
    menu_code: 'sim_calendar',
    menu_label: 'Practice Calendar',
    route_path: '/simulator/calendar',
    parent_code: null,
    menu_icon: 'calendar-days',
    sort_order: 25,
    domain: 'simulator',
    roles: ['simulator_user'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_section_okr',
    menu_label: 'Practice OKR & Goals',
    route_path: null,
    parent_code: null,
    menu_icon: 'target',
    sort_order: 26,
    domain: 'simulator',
    roles: ['simulator_user'],
    is_container: true,
  },
  {
    menu_code: 'sim_okr_dashboard',
    menu_label: 'OKR Dashboard',
    route_path: '/simulator/okr',
    parent_code: 'sim_section_okr',
    menu_icon: 'target',
    sort_order: 1,
    domain: 'simulator',
    roles: ['simulator_user'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_team_mode_setup',
    menu_label: 'Team Mode (Multiplayer)',
    route_path: '/simulator/team-mode/setup',
    parent_code: 'sim_live_simulation',
    menu_icon: 'users',
    sort_order: 10,
    domain: 'simulator',
    roles: ['simulator_user'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_scenario_marketplace',
    menu_label: 'Scenario Marketplace',
    route_path: '/simulator/scenarios/marketplace',
    parent_code: 'sim_scenarios',
    menu_icon: 'store',
    sort_order: 10,
    domain: 'simulator',
    roles: ['simulator_user'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_section_cert_exams',
    menu_label: 'Certification Exams',
    route_path: null,
    parent_code: null,
    menu_icon: 'award',
    sort_order: 35,
    domain: 'simulator',
    roles: ['simulator_user'],
    is_container: true,
  },
  {
    menu_code: 'sim_exams_browse',
    menu_label: 'Browse Exams',
    route_path: '/simulator/exams',
    parent_code: 'sim_section_cert_exams',
    menu_icon: 'book-open',
    sort_order: 1,
    domain: 'simulator',
    roles: ['simulator_user'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_exams_results',
    menu_label: 'My Exam Results',
    route_path: '/simulator/exams/results',
    parent_code: 'sim_section_cert_exams',
    menu_icon: 'clipboard-list',
    sort_order: 2,
    domain: 'simulator',
    roles: ['simulator_user'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_run_analytics',
    menu_label: 'Cross-Run Analytics',
    route_path: '/simulator/profile/run-analytics',
    parent_code: 'sim_profile',
    menu_icon: 'bar-chart-2',
    sort_order: 10,
    domain: 'simulator',
    roles: ['simulator_user'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_improvement_insights',
    menu_label: 'Improvement Insights',
    route_path: '/simulator/profile/improvement',
    parent_code: 'sim_profile',
    menu_icon: 'trending-up',
    sort_order: 11,
    domain: 'simulator',
    roles: ['simulator_user'],
    registry_fallback: true,
  },

  // ── Simulator PM gap menus ────────────────────────────────────────────────────
  {
    menu_code: 'sim_pm_calendar',
    menu_label: 'Practice Calendar',
    route_path: '/simulator/pm/calendar',
    parent_code: null,
    menu_icon: 'calendar-days',
    sort_order: 5,
    domain: 'simulator',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pm_section_automation',
    menu_label: 'Practice Automation',
    route_path: null,
    parent_code: null,
    menu_icon: 'zap',
    sort_order: 140,
    domain: 'simulator',
    roles: ['project_manager'],
    is_container: true,
  },
  {
    menu_code: 'sim_pm_automation_rules',
    menu_label: 'My Automation Rules',
    route_path: '/simulator/pm/automations',
    parent_code: 'sim_pm_section_automation',
    menu_icon: 'zap',
    sort_order: 1,
    domain: 'simulator',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pm_okr_dashboard',
    menu_label: 'Practice OKR Dashboard',
    route_path: '/simulator/pm/okr',
    parent_code: 'sim_pm_section_okr',
    menu_icon: 'target',
    sort_order: 1,
    domain: 'simulator',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pm_section_okr',
    menu_label: 'Practice Strategy & OKRs',
    route_path: null,
    parent_code: null,
    menu_icon: 'target',
    sort_order: 90,
    domain: 'simulator',
    roles: ['project_manager'],
    is_container: true,
  },
  {
    menu_code: 'sim_pm_resources_workload',
    menu_label: 'Workload Heatmap',
    route_path: '/simulator/pm/resources/workload',
    parent_code: 'sim_pm_section_resources',
    menu_icon: 'layout-grid',
    sort_order: 1,
    domain: 'simulator',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pm_section_resources',
    menu_label: 'Practice Resources Hub',
    route_path: null,
    parent_code: null,
    menu_icon: 'users',
    sort_order: 100,
    domain: 'simulator',
    roles: ['project_manager'],
    is_container: true,
  },
]

export default PMIS_GAP_MENU_REGISTRY
