/**
 * v639 Record lifecycle sidebar menu entries
 * @see projectplan/v639_Record_Lifecycle_Management_Plan.md
 */

/** @type {import('./menuRegistry.js').MenuRegistryEntry[]} */
export const RECORD_LIFECYCLE_MENU_REGISTRY = [
  // ── Platform PMO ─────────────────────────────────────────────────────────────
  {
    menu_code: 'pmo_section_authorisation',
    menu_label: 'Authorisation & Lifecycle',
    route_path: null,
    parent_code: null,
    menu_icon: 'shield-check',
    sort_order: 5,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance',
    is_container: true,
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_auth_queue',
    menu_label: 'Authorisation Queue',
    route_path: '/pmo/authorisation/queue',
    parent_code: 'pmo_section_authorisation',
    menu_icon: 'inbox',
    sort_order: 1,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_auth_dashboard',
    menu_label: 'Lifecycle Dashboard',
    route_path: '/pmo/authorisation/dashboard',
    parent_code: 'pmo_section_authorisation',
    menu_icon: 'bar-chart-2',
    sort_order: 2,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_auth_configure',
    menu_label: 'Configure Lifecycle Rules',
    route_path: '/pmo/authorisation/configure',
    parent_code: 'pmo_section_authorisation',
    menu_icon: 'settings',
    sort_order: 3,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_auth_chains',
    menu_label: 'Approval Chains',
    route_path: '/pmo/authorisation/chains',
    parent_code: 'pmo_section_authorisation',
    menu_icon: 'git-branch',
    sort_order: 4,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_auth_archive_retention',
    menu_label: 'Archive Retention Rules',
    route_path: '/pmo/authorisation/archive-retention',
    parent_code: 'pmo_section_authorisation',
    menu_icon: 'archive',
    sort_order: 5,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance',
    registry_fallback: true,
  },
  {
    menu_code: 'pmo_auth_archive_vault',
    menu_label: 'Archive Vault',
    route_path: '/pmo/authorisation/archive',
    parent_code: 'pmo_section_authorisation',
    menu_icon: 'database',
    sort_order: 6,
    domain: 'platform',
    roles: ['pmo_admin', 'system_admin'],
    category: 'pmo-cat-governance',
    registry_fallback: true,
  },

  // ── Platform PM ──────────────────────────────────────────────────────────────
  {
    menu_code: 'pm_section_authorisation',
    menu_label: 'Authorisation',
    route_path: null,
    parent_code: null,
    menu_icon: 'shield-check',
    sort_order: 5,
    domain: 'platform',
    roles: ['project_manager'],
    is_container: true,
    registry_fallback: true,
  },
  {
    menu_code: 'pm_auth_queue',
    menu_label: 'Pending My Approval',
    route_path: '/pm/authorisation/queue',
    parent_code: 'pm_section_authorisation',
    menu_icon: 'inbox',
    sort_order: 1,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'pm_auth_submitted',
    menu_label: 'My Submitted Records',
    route_path: '/pm/authorisation/submitted',
    parent_code: 'pm_section_authorisation',
    menu_icon: 'send',
    sort_order: 2,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'pm_auth_chains',
    menu_label: 'Approval Chains',
    route_path: '/pm/authorisation/chains',
    parent_code: 'pm_section_authorisation',
    menu_icon: 'git-branch',
    sort_order: 3,
    domain: 'platform',
    roles: ['project_manager'],
    registry_fallback: true,
  },

  // ── Simulator PMO ───────────────────────────────────────────────────────────
  {
    menu_code: 'sim_pmo_section_authorisation',
    menu_label: 'Practice Authorisation',
    route_path: null,
    parent_code: null,
    menu_icon: 'shield-check',
    sort_order: 5,
    domain: 'simulator',
    roles: ['sim_pmo_admin', 'simulator_admin'],
    is_container: true,
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_auth_queue',
    menu_label: 'Authorisation Queue',
    route_path: '/simulator/pmo/authorisation/queue',
    parent_code: 'sim_pmo_section_authorisation',
    menu_icon: 'inbox',
    sort_order: 1,
    domain: 'simulator',
    roles: ['sim_pmo_admin', 'simulator_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_auth_dashboard',
    menu_label: 'Lifecycle Dashboard',
    route_path: '/simulator/pmo/authorisation/dashboard',
    parent_code: 'sim_pmo_section_authorisation',
    menu_icon: 'bar-chart-2',
    sort_order: 2,
    domain: 'simulator',
    roles: ['sim_pmo_admin', 'simulator_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_auth_configure',
    menu_label: 'Configure Lifecycle Rules',
    route_path: '/simulator/pmo/authorisation/configure',
    parent_code: 'sim_pmo_section_authorisation',
    menu_icon: 'settings',
    sort_order: 3,
    domain: 'simulator',
    roles: ['sim_pmo_admin', 'simulator_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_auth_chains',
    menu_label: 'Approval Chains',
    route_path: '/simulator/pmo/authorisation/chains',
    parent_code: 'sim_pmo_section_authorisation',
    menu_icon: 'git-branch',
    sort_order: 4,
    domain: 'simulator',
    roles: ['sim_pmo_admin', 'simulator_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_auth_archive_retention',
    menu_label: 'Archive Retention Rules',
    route_path: '/simulator/pmo/authorisation/archive-retention',
    parent_code: 'sim_pmo_section_authorisation',
    menu_icon: 'archive',
    sort_order: 5,
    domain: 'simulator',
    roles: ['sim_pmo_admin', 'simulator_admin'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pmo_auth_archive_vault',
    menu_label: 'Archive Vault',
    route_path: '/simulator/pmo/authorisation/archive',
    parent_code: 'sim_pmo_section_authorisation',
    menu_icon: 'database',
    sort_order: 6,
    domain: 'simulator',
    roles: ['sim_pmo_admin', 'simulator_admin'],
    registry_fallback: true,
  },

  // ── Simulator PM ──────────────────────────────────────────────────────────────
  {
    menu_code: 'sim_pm_section_authorisation',
    menu_label: 'Practice Authorisation',
    route_path: null,
    parent_code: null,
    menu_icon: 'shield-check',
    sort_order: 5,
    domain: 'simulator',
    roles: ['sim_project_manager'],
    is_container: true,
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pm_auth_queue',
    menu_label: 'Pending My Approval',
    route_path: '/simulator/pm/authorisation/queue',
    parent_code: 'sim_pm_section_authorisation',
    menu_icon: 'inbox',
    sort_order: 1,
    domain: 'simulator',
    roles: ['sim_project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pm_auth_submitted',
    menu_label: 'My Submitted Records',
    route_path: '/simulator/pm/authorisation/submitted',
    parent_code: 'sim_pm_section_authorisation',
    menu_icon: 'send',
    sort_order: 2,
    domain: 'simulator',
    roles: ['sim_project_manager'],
    registry_fallback: true,
  },
  {
    menu_code: 'sim_pm_auth_chains',
    menu_label: 'Approval Chains',
    route_path: '/simulator/pm/authorisation/chains',
    parent_code: 'sim_pm_section_authorisation',
    menu_icon: 'git-branch',
    sort_order: 3,
    domain: 'simulator',
    roles: ['sim_project_manager'],
    registry_fallback: true,
  },

  // ── Simulator TM ──────────────────────────────────────────────────────────────
  {
    menu_code: 'sim_tm_auth_submitted',
    menu_label: 'My Submitted Records',
    route_path: '/simulator/tm/authorisation/submitted',
    parent_code: null,
    menu_icon: 'send',
    sort_order: 15,
    domain: 'simulator',
    roles: ['sim_team_member'],
    registry_fallback: true,
  },
]

export default RECORD_LIFECYCLE_MENU_REGISTRY
