import {
  LayoutDashboard,
  CheckSquare,
  Layout,
  BookOpen,
  Lightbulb,
  AlertTriangle,
  FolderKanban,
  Users,
  GitBranch,
  UserSquare,
  Network,
  LayoutGrid,
  ShieldAlert,
  AlertCircle,
  GitPullRequest,
  Clock4,
  Bug,
  Gavel,
  FileText,
  PlayCircle,
  Map,
  Zap,
  Activity,
  CheckCircle,
  FileClock,
  ShieldCheck,
  FileEdit,
  MessageCircle,
  Video,
  Phone,
  BarChart2,
  CheckSquare as CheckSq,
  Library,
  Clock,
  PlusCircle,
  Layers,
  MailCheck,
  Settings,
  Send,
} from 'lucide-react'

const simulatorTMMenuConfig = [
  {
    id: 'sim-tm-dashboard',
    label: 'Dashboard',
    path: '/simulator/tm/dashboard',
    icon: LayoutDashboard,
  },
  {
    id: 'sim-tm-my-work',
    label: 'My Work',
    path: null,
    icon: CheckSquare,
    children: [
      { id: 'sim-tm-tasks', label: 'My Tasks', path: '/simulator/tm/tasks', icon: CheckSquare },
      { id: 'sim-tm-board', label: 'Task Board', path: '/simulator/tm/tasks/board', icon: Layout },
      { id: 'sim-tm-daily-log', label: 'Daily Log', path: '/simulator/tm/daily-log', icon: BookOpen },
      { id: 'sim-tm-lesson-actions', label: 'My Lesson Actions', path: '/simulator/tm/lessons/my-actions', icon: Lightbulb },
      { id: 'sim-tm-issue-actions', label: 'My Issue Actions', path: '/simulator/tm/issues/my-actions', icon: AlertTriangle },
      { id: 'sim-tm-auth-submitted', label: 'My Submitted Records', path: '/simulator/tm/authorisation/submitted', icon: Send },
    ],
  },
  {
    id: 'sim-tm-my-projects',
    label: 'My Projects',
    path: null,
    icon: FolderKanban,
    children: [
      { id: 'sim-tm-proj-list', label: 'My Projects', path: '/simulator/tm/projects', icon: FolderKanban },
      { id: 'sim-tm-proj-members', label: 'Project Members', path: '/simulator/tm/project-members', icon: Users },
    ],
  },
  {
    id: 'sim-tm-plans',
    label: 'Plans',
    path: null,
    icon: GitBranch,
    children: [
      { id: 'sim-tm-my-plans',    label: 'My Plans',        path: '/simulator/tm/plans/my-plans',               icon: UserSquare },
      { id: 'sim-tm-new-plan',    label: 'Create New Plan', path: '/simulator/tm/plans/new',                    icon: PlusCircle },
      { id: 'sim-tm-draft-plans', label: 'Draft Plans',     path: '/simulator/pm/planning/microplans/drafts',   icon: FileClock },
      { id: 'sim-tm-plans-overview', label: 'Plans Overview', path: '/simulator/pm/planning/microplans',        icon: LayoutGrid },
    ],
  },
  {
    id: 'sim-tm-controls',
    label: 'Controls & Registers',
    path: null,
    icon: ShieldAlert,
    children: [
      { id: 'sim-tm-risk', label: 'Risk Register', path: '/simulator/pm/risks', icon: ShieldAlert },
      { id: 'sim-tm-issues', label: 'Issue Log', path: '/simulator/pm/issues', icon: AlertCircle },
      { id: 'sim-tm-change', label: 'Change Log', path: '/simulator/pm/changes', icon: GitPullRequest },
      { id: 'sim-tm-delay', label: 'Delay Log', path: '/simulator/pm/delays', icon: Clock4 },
      { id: 'sim-tm-defect', label: 'Defect Register', path: '/simulator/pm/testing/defects', icon: Bug },
      { id: 'sim-tm-decision',     label: 'Decision Log',  path: '/simulator/tm/decisions',     icon: Gavel },
      { id: 'sim-tm-new-decision', label: 'New Decision',  path: '/simulator/tm/decisions/new', icon: PlusCircle },
    ],
  },
  {
    id: 'sim-tm-forms',
    label: 'Process Group Forms',
    path: null,
    icon: FileText,
    children: [
      { id: 'sim-tm-form-init', label: 'Initiating', path: '/simulator/pm/projects/:projectId/forms?group=Initiating', icon: PlayCircle },
      { id: 'sim-tm-form-plan', label: 'Planning', path: '/simulator/pm/projects/:projectId/forms?group=Planning', icon: Map },
      { id: 'sim-tm-form-exec', label: 'Executing', path: '/simulator/pm/projects/:projectId/forms?group=Executing', icon: Zap },
      { id: 'sim-tm-form-mon', label: 'Monitoring & Control', path: '/simulator/pm/projects/:projectId/forms?group=Monitoring', icon: Activity },
      { id: 'sim-tm-form-close', label: 'Closing', path: '/simulator/pm/projects/:projectId/forms?group=Closing', icon: CheckCircle },
      { id: 'sim-tm-draft-forms', label: 'My Draft Forms', path: '/simulator/pm/projects/:projectId/forms/drafts', icon: FileClock },
    ],
  },
  {
    id: 'sim-tm-process-templates',
    label: 'Process Templates',
    path: null,
    icon: Layers,
    children: [
      { id: 'sim-tm-pt-all', label: 'All Process Templates', path: '/simulator/pm/process-templates', icon: Layers },
      { id: 'sim-tm-pt-pre', label: 'Pre-Project', path: '/simulator/pm/process-templates/pre-project', icon: FileText },
      { id: 'sim-tm-pt-init', label: 'Initiating', path: '/simulator/pm/process-templates/initiating', icon: PlayCircle },
      { id: 'sim-tm-pt-plan', label: 'Planning', path: '/simulator/pm/process-templates/planning', icon: Map },
      { id: 'sim-tm-pt-exec', label: 'Executing', path: '/simulator/pm/process-templates/executing', icon: Zap },
      { id: 'sim-tm-pt-mon', label: 'Monitoring & Control', path: '/simulator/pm/process-templates/monitoring-controlling', icon: Activity },
      { id: 'sim-tm-pt-close', label: 'Closing', path: '/simulator/pm/process-templates/closing', icon: CheckCircle },
    ],
  },
  {
    id: 'sim-tm-charter',
    label: 'Team Charter',
    path: null,
    icon: ShieldCheck,
    children: [
      { id: 'sim-tm-charter-view', label: 'Team Charter', path: '/simulator/tm/team-charter', icon: ShieldCheck },
    ],
  },
  {
    id: 'sim-tm-comms',
    label: 'Communications',
    path: null,
    icon: MessageCircle,
    children: [
      { id: 'sim-tm-chat', label: 'Team Chat', path: '/simulator/tm/communications/chat', icon: MessageCircle },
      { id: 'sim-tm-video', label: 'Video Calls', path: '/simulator/tm/communications/video-calls', icon: Video },
      { id: 'sim-tm-voice', label: 'Voice Calls', path: '/simulator/tm/communications/voice-calls', icon: Phone },
    ],
  },
  {
    id: 'sim-tm-stakeholders',
    label: 'Stakeholders',
    path: null,
    icon: Network,
    children: [
      { id: 'sim-tm-stakeholder-reg', label: 'Stakeholder Register', path: '/simulator/pm/stakeholders/register', icon: Network },
      { id: 'sim-tm-stakeholder-ana', label: 'Stakeholder Analysis', path: '/simulator/pm/stakeholders/analysis', icon: BarChart2 },
    ],
  },
  {
    id: 'sim-tm-reporting',
    label: 'Reporting & Status',
    path: null,
    icon: BarChart2,
    children: [
      { id: 'sim-tm-highlight', label: 'Highlight Reports', path: '/simulator/pm/reporting/highlight-reports', icon: BarChart2 },
      { id: 'sim-tm-checkpoint', label: 'Checkpoint Reports', path: '/simulator/pm/reporting/checkpoint-reports', icon: CheckSq },
      { id: 'sim-tm-reports-lib', label: 'Reports Library', path: '/simulator/pm/reports', icon: Library },
    ],
  },
  {
    id: 'sim-tm-timesheets',
    label: 'Timesheets',
    path: null,
    icon: Clock,
    children: [
      { id: 'sim-tm-my-time', label: 'My Timesheets', path: '/simulator/tm/timesheets', icon: Clock },
      { id: 'sim-tm-log-time', label: 'Log Time', path: '/simulator/tm/timesheets/new', icon: PlusCircle },
    ],
  },
  {
    id: 'sim-tm-knowledge',
    label: 'Knowledge & Resources',
    path: null,
    icon: Layers,
    children: [
      { id: 'sim-tm-ind-temp', label: 'Industry Templates', path: '/simulator/pm/planning/industry-templates', icon: Layers },
    ],
  },
]

export default simulatorTMMenuConfig
