/**
 * Lessons Report Document Info Section
 * Document control information
 */

import { useState, useEffect } from 'react'
import { FileText, Calendar, User } from 'lucide-react'
import { generateReportReference } from '../../services/lessonsReportService'

export default function LessonsReportDocumentInfoSection({
  formData,
  onChange,
  errors = {},
  reportId = null,
  readOnly = false
}) {
  const [reference, setReference] = useState(formData.report_reference || '')

  useEffect(() => {
    if (!reportId && !reference) {
      // Generate reference for new reports
      generateReference()
    } else if (formData.report_reference) {
      setReference(formData.report_reference)
    }
  }, [formData.report_reference, reportId])

  const generateReference = async () => {
    try {
      // Need projectId from parent - check if it's in formData or get from context
      // For now, skip if no project_id - will be generated by trigger on save
      if (!formData.project_id && !reportId) {
        // Reference will be auto-generated on save via database trigger
        return
      }
      
      const result = await generateReportReference(
        formData.project_id || projectId,
        formData.stage_boundary_id,
        formData.report_type || 'project'
      )
      if (result.success) {
        setReference(result.data)
        onChange('report_reference', result.data)
      }
    } catch (error) {
      console.error('Error generating reference:', error)
      // Reference will be auto-generated on save via database trigger
    }
  }

  return (
    <div className="space-y-6">
      <div>
        <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-4 flex items-center gap-2">
          <FileText className="w-5 h-5" />
          Document Information
        </h3>
        <p className="text-sm text-gray-600 dark:text-gray-400 mb-6">
          Document control and metadata for the Lessons Report
        </p>
      </div>

      {/* Report Reference */}
      <div>
        <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
          Report Reference <span className="text-red-500">*</span>
        </label>
        {readOnly ? (
          <p className="text-gray-900 dark:text-white font-mono">{reference || 'N/A'}</p>
        ) : (
          <div className="flex gap-2">
            <input
              type="text"
              value={reference}
              onChange={(e) => {
                setReference(e.target.value)
                onChange('report_reference', e.target.value)
              }}
              className="flex-1 px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white font-mono"
              placeholder="Auto-generated"
            />
            {!reportId && (
              <button
                onClick={generateReference}
                className="px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700"
              >
                Generate
              </button>
            )}
          </div>
        )}
      </div>

      {/* Version Number */}
      <div>
        <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
          Version Number
        </label>
        {readOnly ? (
          <p className="text-gray-900 dark:text-white">{formData.version_no || '1.0'}</p>
        ) : (
          <input
            type="text"
            value={formData.version_no || '1.0'}
            onChange={(e) => onChange('version_no', e.target.value)}
            className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
            placeholder="1.0"
          />
        )}
      </div>

      {/* Report Date */}
      <div>
        <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1 flex items-center gap-2">
          <Calendar className="w-4 h-4" />
          Report Date <span className="text-red-500">*</span>
        </label>
        {readOnly ? (
          <p className="text-gray-900 dark:text-white">
            {formData.report_date ? new Date(formData.report_date).toLocaleDateString() : 'N/A'}
          </p>
        ) : (
          <input
            type="date"
            value={formData.report_date || ''}
            onChange={(e) => onChange('report_date', e.target.value)}
            className={`w-full px-3 py-2 border rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white ${
              errors.report_date ? 'border-red-500' : 'border-gray-300 dark:border-gray-600'
            }`}
            required
          />
        )}
        {errors.report_date && (
          <p className="mt-1 text-sm text-red-600">{errors.report_date}</p>
        )}
      </div>

      {/* Report Type */}
      <div>
        <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
          Report Type <span className="text-red-500">*</span>
        </label>
        {readOnly ? (
          <p className="text-gray-900 dark:text-white capitalize">{formData.report_type || 'N/A'}</p>
        ) : (
          <select
            value={formData.report_type || 'project'}
            onChange={(e) => onChange('report_type', e.target.value)}
            className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
          >
            <option value="stage">Stage Report</option>
            <option value="project">Project Report</option>
            <option value="interim">Interim Report</option>
          </select>
        )}
      </div>

      {/* Reporting Period (for stage reports) */}
      {formData.report_type === 'stage' && (
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
              Reporting Period Start
            </label>
            {readOnly ? (
              <p className="text-gray-900 dark:text-white">
                {formData.reporting_period_start ? new Date(formData.reporting_period_start).toLocaleDateString() : 'N/A'}
              </p>
            ) : (
              <input
                type="date"
                value={formData.reporting_period_start || ''}
                onChange={(e) => onChange('reporting_period_start', e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
              />
            )}
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
              Reporting Period End
            </label>
            {readOnly ? (
              <p className="text-gray-900 dark:text-white">
                {formData.reporting_period_end ? new Date(formData.reporting_period_end).toLocaleDateString() : 'N/A'}
              </p>
            ) : (
              <input
                type="date"
                value={formData.reporting_period_end || ''}
                onChange={(e) => onChange('reporting_period_end', e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
              />
            )}
          </div>
        </div>
      )}

      {/* Author and Prepared By */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1 flex items-center gap-2">
            <User className="w-4 h-4" />
            Author
          </label>
          {readOnly ? (
            <p className="text-gray-900 dark:text-white">
              {formData.author_name || formData.author?.full_name || 'N/A'}
            </p>
          ) : (
            <input
              type="text"
              value={formData.author_name || ''}
              onChange={(e) => onChange('author_name', e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
              placeholder="Author name"
            />
          )}
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
            Prepared By
          </label>
          {readOnly ? (
            <p className="text-gray-900 dark:text-white">
              {formData.prepared_by_name || formData.prepared_by?.full_name || 'N/A'}
            </p>
          ) : (
            <input
              type="text"
              value={formData.prepared_by_name || ''}
              onChange={(e) => onChange('prepared_by_name', e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
              placeholder="Prepared by name"
            />
          )}
        </div>
      </div>
    </div>
  )
}
