-- ============================================================================
-- Payment Transactions Table
-- Version: v117
-- Description: Creates table to track payment transactions for Paynow integration
-- Author: Development Team
-- Date: 2025-01-XX
-- ============================================================================

-- Purpose:
-- This table stores payment transaction records for tracking Paynow payments,
-- subscription creation, and payment verification.

-- ============================================================================
-- TABLE: payment_transactions
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.payment_transactions (
    -- Primary Key
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Payment Reference (unique identifier for this transaction)
    reference VARCHAR(255) UNIQUE NOT NULL,

    -- Paynow Reference (returned by Paynow)
    paynow_reference VARCHAR(255),

    -- Payment Details
    amount DECIMAL(10, 2) NOT NULL,
    currency VARCHAR(3) DEFAULT 'USD',
    status VARCHAR(50) DEFAULT 'pending' CHECK (status IN (
        'pending',
        'paid',
        'cancelled',
        'failed',
        'expired'
    )),

    -- Payment Provider
    payment_provider VARCHAR(50) DEFAULT 'paynow' CHECK (payment_provider IN (
        'paynow',
        'stripe',
        'paypal'
    )),

    -- Metadata (stores plan info, organisation ID, project ID, etc.)
    metadata JSONB DEFAULT '{}'::jsonb,

    -- Paynow Poll URL (for status checking)
    poll_url TEXT,

    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_payment_transactions_reference ON public.payment_transactions(reference);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_status ON public.payment_transactions(status);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_paynow_reference ON public.payment_transactions(paynow_reference);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_created_at ON public.payment_transactions(created_at);

-- Create GIN index on entire metadata JSONB column for efficient JSON queries
-- This supports queries like: metadata @> '{"organisation_id": "value"}'::jsonb
CREATE INDEX IF NOT EXISTS idx_payment_transactions_metadata ON public.payment_transactions 
    USING GIN (metadata);

-- Create btree indexes on extracted metadata values for exact match queries
-- These support queries like: metadata->>'organisation_id' = 'value'
CREATE INDEX IF NOT EXISTS idx_payment_transactions_metadata_org ON public.payment_transactions 
    ((metadata->>'organisation_id'))
    WHERE metadata->>'organisation_id' IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_payment_transactions_metadata_project ON public.payment_transactions 
    ((metadata->>'project_id'))
    WHERE metadata->>'project_id' IS NOT NULL;

-- Create trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_payment_transactions_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_payment_transactions_updated_at ON public.payment_transactions;
CREATE TRIGGER trigger_update_payment_transactions_updated_at
    BEFORE UPDATE ON public.payment_transactions
    FOR EACH ROW
    EXECUTE FUNCTION update_payment_transactions_updated_at();

-- Enable Row Level Security
ALTER TABLE public.payment_transactions ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Users can only see their own payment transactions
-- (via metadata->>'organisation_id' matching their account)
CREATE POLICY policy_payment_transactions_select ON public.payment_transactions
    FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.accounts a
            WHERE a.id::text = (metadata->>'organisation_id')
            AND a.owner_user_id = auth.uid()
        )
    );

-- RLS Policy: Service role can insert/update (for webhooks)
-- Note: This is handled by service role key, but we add a policy for completeness
CREATE POLICY policy_payment_transactions_service_role ON public.payment_transactions
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- Add comments
COMMENT ON TABLE public.payment_transactions IS 'Stores payment transaction records for Paynow and other payment providers';
COMMENT ON COLUMN public.payment_transactions.reference IS 'Unique reference for this payment transaction (generated by application)';
COMMENT ON COLUMN public.payment_transactions.paynow_reference IS 'Reference returned by Paynow payment gateway';
COMMENT ON COLUMN public.payment_transactions.status IS 'Current status of the payment: pending, paid, cancelled, failed, expired';
COMMENT ON COLUMN public.payment_transactions.metadata IS 'JSONB field storing plan info, organisation ID, project ID, and other transaction metadata';
COMMENT ON COLUMN public.payment_transactions.poll_url IS 'Paynow poll URL for checking payment status';

-- Register in database_tables
INSERT INTO public.database_tables (table_name, table_description, is_system_table, is_active)
VALUES ('payment_transactions', 'Stores payment transaction records for Paynow and other payment providers', false, true)
ON CONFLICT (table_name) DO UPDATE SET
    table_description = EXCLUDED.table_description,
    updated_at = NOW();

