-- =============================================================================
-- v833: Remove "PMBOK" text from process_template demo content (public + sim)
-- Plan: projectplan/v836_pmbok_process_template_content_naming_compliance_fix_plan.md
-- Companion Admin fixes (Global Template Library side): v199/v200 in
-- project-nidus-admin/SQL — this file is the third and final wave, fixing the
-- process_template *content* tables' own demo/seed rows (public.project_charters
-- etc., not admin.global_template_library).
--
-- Root cause: v633/v634_*_process_templates_master_seed_data.sql (generated by
-- scripts/generate-v633-process-templates-seed.mjs) seeded one demo master row per
-- process_template content table (24 tables x 1 row each, marked
-- reference_code LIKE 'SEED633-%' / 'SEED634-%'). Every row's document_data JSONB had
-- a `"pmbok_group"` key, and the project_charters row's `description` column read
-- "Standard PMBOK project charter for authorising a new project or phase.".
-- Rule 26/27 (CLAUDE.md): PMBOK(R) is a PMI trademark, same category as PRINCE2.
--
-- Fixed at source: the generator script + its two already-applied output files
-- (v633 public, v634 sim, plus v635's sidebar menu_description) were regenerated in
-- place — no "pmbok" text remains in any of them. This migration is only for the rows
-- that already exist in the live database from a prior run of v633/v634.
--
-- Idempotent: matches by reference_code pattern; no-op if nothing matches (e.g. if
-- v633/v634 were never run, or already fixed by a prior run of this file).
-- =============================================================================

-- ============================================================
-- public schema
-- ============================================================
DO $$
DECLARE
  v_tables TEXT[] := ARRAY[
    'project_charters','assumption_logs','project_management_plans','requirements_management_plans',
    'requirements_documentation','wbs_dictionary_entries','activity_attributes','activity_resource_requirements',
    'resource_breakdown_structure','activity_duration_estimates','cost_management_plans','activity_cost_estimates',
    'cost_baselines','resource_management_plans','procurement_management_plans','stakeholder_engagement_plans',
    'quality_checklists','team_performance_assessments','make_or_buy_decisions','variance_analysis_reports',
    'evm_status_reports','scope_acceptance_forms','project_closure_checklists','contract_closure_documents'
  ];
  v_table TEXT;
  v_count INT;
  v_total INT := 0;
BEGIN
  FOREACH v_table IN ARRAY v_tables LOOP
    EXECUTE format(
      $f$
      UPDATE public.%I
      SET document_data = (document_data - 'pmbok_group')
            || jsonb_build_object('standards_based_group', document_data->'pmbok_group'),
          updated_at = NOW()
      WHERE reference_code LIKE 'SEED633-%%'
        AND document_data ? 'pmbok_group'
      $f$,
      v_table
    );
    GET DIAGNOSTICS v_count = ROW_COUNT;
    v_total := v_total + v_count;
  END LOOP;

  UPDATE public.project_charters
  SET description = 'Standards-Based project charter template for authorising a new project or phase.',
      updated_at = NOW()
  WHERE reference_code LIKE 'SEED633-%'
    AND description ILIKE '%pmbok%';

  RAISE NOTICE 'public: renamed pmbok_group -> standards_based_group on % row(s) across 24 process_template tables', v_total;
END $$;

-- ============================================================
-- sim schema
-- ============================================================
DO $$
DECLARE
  v_tables TEXT[] := ARRAY[
    'project_charters','assumption_logs','project_management_plans','requirements_management_plans',
    'requirements_documentation','wbs_dictionary_entries','activity_attributes','activity_resource_requirements',
    'resource_breakdown_structure','activity_duration_estimates','cost_management_plans','activity_cost_estimates',
    'cost_baselines','resource_management_plans','procurement_management_plans','stakeholder_engagement_plans',
    'quality_checklists','team_performance_assessments','make_or_buy_decisions','variance_analysis_reports',
    'evm_status_reports','scope_acceptance_forms','project_closure_checklists','contract_closure_documents'
  ];
  v_table TEXT;
  v_count INT;
  v_total INT := 0;
BEGIN
  FOREACH v_table IN ARRAY v_tables LOOP
    EXECUTE format(
      $f$
      UPDATE sim.%I
      SET document_data = (document_data - 'pmbok_group')
            || jsonb_build_object('standards_based_group', document_data->'pmbok_group'),
          updated_at = NOW()
      WHERE reference_code LIKE 'SEED634-%%'
        AND document_data ? 'pmbok_group'
      $f$,
      v_table
    );
    GET DIAGNOSTICS v_count = ROW_COUNT;
    v_total := v_total + v_count;
  END LOOP;

  UPDATE sim.project_charters
  SET description = 'Standards-Based project charter template for authorising a new project or phase.',
      updated_at = NOW()
  WHERE reference_code LIKE 'SEED634-%'
    AND description ILIKE '%pmbok%';

  RAISE NOTICE 'sim: renamed pmbok_group -> standards_based_group on % row(s) across 24 process_template tables', v_total;
END $$;

-- ============================================================
-- sidebar menu_description (v635's row, if it exists live with the old text)
-- ============================================================
UPDATE public.menu_items
SET menu_description = 'Simulator PMO — Standards-Based process templates hub',
    updated_at = NOW()
WHERE menu_code = 'sim_pmo_process_templates_section'
  AND menu_description ILIKE '%pmbok%';

DO $$
BEGIN
  RAISE NOTICE 'v833_pmbok_process_template_content_naming_compliance_fix.sql applied';
END $$;
